



--  Recuperação (REC)
--  PAP - REC DE APRENDIZAGEM
--  RP AUTORAL CIENC HUM --556
--  RP AUTORAL CIENC NAT -- 555
--  RP AUTORAL MAT -- 554
--  RP AUTORAL PORTUGUES --553
--  Atividade Complementar (ATCOMP)

--WHERE CD_TIPO_PROGAMA IN (553,554,555,556,426)

--SELECT * FROM D_TIPO_PROGRAMA WHERE SG_tipo_programa LIKE '%AT CO%'

SELECT 
C.DRE,
C.CD_ESCOLA,
C.SG_TP_ESCOLA,
C.NOMESC,
B.dc_tipo_programa,
COUNT(DISTINCT CASE WHEN A.CD_TIPO_PROGRAMA IN (553,554,555,556,426) THEN CD_TURMA_ESCOLA ELSE NULL END) AS CL,
COUNT(DISTINCT CASE WHEN A.CD_TIPO_PROGRAMA IN (553,554,555,556,426) THEN CD_ALUNO ELSE NULL END) AS MT,
CONVERT(VARCHAR, A.CRDATE-1, 103) AS DT_BASE
INTO ##TUR_MAT_REC
FROM SME_ALUNOS_DIARIO A
JOIN D_TIPO_PROGRAMA B ON A.CD_TIPO_PROGRAMA=B.cd_tipo_programa
JOIN SME_ESCOLA_DIARIO C ON A.CD_ESCOLA=C.CD_ESCOLA
WHERE A.CD_TIPO_PROGRAMA IN (553,554,555,556,426) 
GROUP BY 
C.DRE,
C.CD_ESCOLA,
C.SG_TP_ESCOLA,
C.NOMESC,
B.dc_tipo_programa,
A.CRDATE

--select * from ##TUR_MAT_REC

--SELECT * FROM SME_ALUNOS_DIARIO  WHERE SG_ETAPA IS NULL