/*
Geração de tabelas com dados de matriculas de alunos migrantes - tabela geral com nomes dos alunos e resumos
*/

-------------------------------------------------------
--ALUNOS ESTRANGEIROS COM IDADE, SEXO, RAÇA, PAIS
--------------------------------------------------------
USE Db_Local

DROP TABLE ##ALUNOS_MIGRANTES_POR_UE
SELECT DISTINCT
B.DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
A.CD_ALUNO,
A.SG_ETAPA,
A.SG_SERIE_ENSINO AS SÉRIE,
CONVERT(VARCHAR, A.DT_NASCIMENTO_ALUNO, 103) AS DT_NASC,
DATEDIFF(YEAR, A.DT_NASCIMENTO_ALUNO, GETDATE()) AS IDADE,
--CAST(DATEDIFF(DD, A.DT_NASCIMENTO_ALUNO, GETDATE())/365.25 AS INT) AS IDADE1,
A.CD_SEXO_ALUNO AS SEXO,
C.dc_raca_cor,
D.nm_pais_mec AS PAÍS,
CONVERT(VARCHAR, A.CRDATE, 103) AS CRDATE
INTO ##ALUNOS_MIGRANTES_POR_UE
FROM SME_ALUNOS_DIARIO A
LEFT JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
left JOIN tipo_raca_cor C ON A.TP_RACA_COR=C.tp_raca_cor
left JOIN [dbo].[PAIS_MEC] D ON A.cd_pais_mec = D.cd_pais_mec
WHERE A.CD_PAIS_MEC <>10 AND SG_ETAPA IS NOT NULL AND B.TP_ESCOLA IN (1,2,3,4,10,11,12,13,16,17,18,28,30,31)-- AND DATEDIFF(YEAR, A.DT_NASCIMENTO_ALUNO, GETDATE())<=18
--SELECT * FROM ##ALUNOS_MIGRANTES_POR_UE
---------------------------------------------------------------------
DROP TABLE ##RESUMO_FAIXA_ETARIA
SELECT 

SG_ETAPA,
Count (DISTINCT CASE WHEN IDADE BETWEEN 0 AND 5 THEN CD_ALUNO ELSE NULL END) AS '0 A 5',
Count (DISTINCT CASE WHEN IDADE BETWEEN 6 AND 14 THEN CD_ALUNO ELSE NULL END) AS '6 A 14',
Count (DISTINCT CASE WHEN IDADE BETWEEN 15 AND 18 THEN CD_ALUNO ELSE NULL END) AS '15 A 18',
Count (DISTINCT CASE WHEN IDADE >18 THEN CD_ALUNO ELSE NULL END) AS '>18 ANOS',
Count (CD_ALUNO) AS 'TOTAL'

INTO ##RESUMO_FAIXA_ETARIA

FROM ##ALUNOS_MIGRANTES_POR_UE
GROUP BY 

SG_ETAPA WITH ROLLUP
--SELECT * FROM ##RESUMO_FAIXA_ETARIA

-------------------------------------------------
DROP TABLE ##RESUMO_FAIXA_ETARIA_TP_ESCOLA
SELECT 

SG_TP_ESCOLA,
Count (DISTINCT CASE WHEN IDADE BETWEEN 0 AND 5 THEN CD_ALUNO ELSE NULL END) AS '0 A 5',
Count (DISTINCT CASE WHEN IDADE BETWEEN 6 AND 14 THEN CD_ALUNO ELSE NULL END) AS '6 A 14',
Count (DISTINCT CASE WHEN IDADE BETWEEN 15 AND 18 THEN CD_ALUNO ELSE NULL END) AS '15 A 18',
Count (DISTINCT CASE WHEN IDADE >18 THEN CD_ALUNO ELSE NULL END) AS '>18 ANOS',
Count (CD_ALUNO) AS 'TOTAL'

INTO ##RESUMO_FAIXA_ETARIA_TP_ESCOLA

FROM ##ALUNOS_MIGRANTES_POR_UE
GROUP BY 

SG_TP_ESCOLA WITH ROLLUP
--SELECT * FROM ##RESUMO_FAIXA_ETARIA_TP_ESCOLA
-------------------------------------------------------

DROP TABLE ##RESUMO_FAIXA_ETARIA_DRE
SELECT 

DRE,
Count (DISTINCT CASE WHEN IDADE BETWEEN 0 AND 5 THEN CD_ALUNO ELSE NULL END) AS '0 A 5',
Count (DISTINCT CASE WHEN IDADE BETWEEN 6 AND 14 THEN CD_ALUNO ELSE NULL END) AS '6 A 14',
Count (DISTINCT CASE WHEN IDADE BETWEEN 15 AND 18 THEN CD_ALUNO ELSE NULL END) AS '15 A 18',
Count (DISTINCT CASE WHEN IDADE >18 THEN CD_ALUNO ELSE NULL END) AS '>18 ANOS',
Count (CD_ALUNO) AS 'TOTAL'

INTO ##RESUMO_FAIXA_ETARIA_DRE

FROM ##ALUNOS_MIGRANTES_POR_UE
GROUP BY 

DRE WITH ROLLUP
--SELECT * FROM ##RESUMO_FAIXA_ETARIA_DRE
--------------------------------------

DROP TABLE ##RESUMO_FAIXA_ETARIA_DRE
SELECT 

PAÍS,
Count (DISTINCT CASE WHEN IDADE BETWEEN 0 AND 5 THEN CD_ALUNO ELSE NULL END) AS '0 A 5',
Count (DISTINCT CASE WHEN IDADE BETWEEN 6 AND 14 THEN CD_ALUNO ELSE NULL END) AS '6 A 14',
Count (DISTINCT CASE WHEN IDADE BETWEEN 15 AND 18 THEN CD_ALUNO ELSE NULL END) AS '15 A 18',
Count (DISTINCT CASE WHEN IDADE >18 THEN CD_ALUNO ELSE NULL END) AS '>18 ANOS',
Count (CD_ALUNO) AS 'TOTAL'

INTO ##RESUMO_FAIXA_ETARIA_PAIS

FROM ##ALUNOS_MIGRANTES_POR_UE
GROUP BY 

PAÍS WITH ROLLUP
--SELECT * FROM ##RESUMO_FAIXA_ETARIA_PAIS ORDER BY TOTAL DESC

-----------------------------------------------
DROP TABLE ##RESUMO_SEXO
SELECT 

SEXO,
Count (DISTINCT CASE WHEN IDADE BETWEEN 0 AND 5 THEN CD_ALUNO ELSE NULL END) AS '0 A 5',
Count (DISTINCT CASE WHEN IDADE BETWEEN 6 AND 14 THEN CD_ALUNO ELSE NULL END) AS '6 A 14',
Count (DISTINCT CASE WHEN IDADE BETWEEN 15 AND 18 THEN CD_ALUNO ELSE NULL END) AS '15 A 18',
Count (DISTINCT CASE WHEN IDADE >18 THEN CD_ALUNO ELSE NULL END) AS '>18 ANOS',
Count (CD_ALUNO) AS 'TOTAL'

INTO ##RESUMO_SEXO

FROM ##ALUNOS_MIGRANTES_POR_UE
GROUP BY 

SEXO WITH ROLLUP
--SELECT * FROM ##RESUMO_SEXO

--------------------------------------------------------------
SELECT 

SEXO,
Count (DISTINCT CASE WHEN IDADE BETWEEN 0 AND 5 THEN CD_ALUNO ELSE NULL END) AS '0 A 5',
Count (DISTINCT CASE WHEN IDADE BETWEEN 6 AND 14 THEN CD_ALUNO ELSE NULL END) AS '6 A 14',
Count (DISTINCT CASE WHEN IDADE BETWEEN 15 AND 17 THEN CD_ALUNO ELSE NULL END) AS '15 A 17',
Count (DISTINCT CASE WHEN IDADE >17 THEN CD_ALUNO ELSE NULL END) AS '>17 ANOS',
Count (CD_ALUNO) AS 'TOTAL'

--INTO ##RESUMO_SEXO

FROM ##ALUNOS_MIGRANTES_POR_UE
GROUP BY 

SEXO WITH ROLLUP

------------------------------------------------------------

SELECT 

SEXO,
--Count (DISTINCT CASE WHEN IDADE BETWEEN 0 AND 5 THEN CD_ALUNO ELSE NULL END) AS '0 A 5',
--Count (DISTINCT CASE WHEN IDADE BETWEEN 6 AND 14 THEN CD_ALUNO ELSE NULL END) AS '6 A 14',
Count (DISTINCT CASE WHEN IDADE < 17 THEN CD_ALUNO ELSE NULL END) AS '<= 17',
Count (DISTINCT CASE WHEN IDADE >17 THEN CD_ALUNO ELSE NULL END) AS '>17 ANOS',
Count (CD_ALUNO) AS 'TOTAL'

--INTO ##RESUMO_SEXO

FROM ##ALUNOS_MIGRANTES_POR_UE
GROUP BY 

SEXO WITH ROLLUP

-------------------------------------------------------------
DROP TABLE ##RESUMO_SEXO_IDADE_POR_UE
SELECT DISTINCT
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
SEXO,
--Count (DISTINCT CASE WHEN IDADE BETWEEN 0 AND 5 THEN CD_ALUNO ELSE NULL END) AS '0 A 5',
--Count (DISTINCT CASE WHEN IDADE BETWEEN 6 AND 14 THEN CD_ALUNO ELSE NULL END) AS '6 A 14',
Count (DISTINCT CASE WHEN IDADE < 17 THEN CD_ALUNO ELSE NULL END) AS '<= 17 ANOS',
Count (DISTINCT CASE WHEN IDADE >17 THEN CD_ALUNO ELSE NULL END) AS '>17 ANOS'


INTO ##RESUMO_SEXO_IDADE_POR_UE

FROM ##ALUNOS_MIGRANTES_POR_UE
GROUP BY
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
SEXO
ORDER BY CD_ESCOLA
--SELECT * FROM ##RESUMO_SEXO_IDADE_POR_UE

-------------------------------------------------------------------------------------------------
SELECT 
PAÍS,
Count (DISTINCT CD_ALUNO) AS 'MATRIC'
INTO ##QTDE_MATRIC_MIGRANTES_POR_PAIS
FROM ##ALUNOS_MIGRANTES_POR_UE
GROUP BY PAÍS