
DROP TABLE ##ALUNOS_ATE_6MESES_DISTR_PRIORITARIOS
SELECT 
B.DRE,
B.DISTR,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
SG_ETAPA,
SG_SERIE_ENSINO,
CD_ALUNO,
NM_ALUNO,
CONVERT(VARCHAR,DT_NASCIMENTO_ALUNO,103) AS DT_NASC,
DATEDIFF(MM,DT_NASCIMENTO_ALUNO,GETDATE()) AS [Idade(meses)]

--INTO ##ALUNOS_ATE_6MESES_DISTR_PRIORITARIOS

FROM SME_ALUNOS_DIARIO A

LEFT JOIN D_MISME_ESCOLA_TOTAL B ON A.CD_ESCOLA = B.CD_ESCOLA
WHERE 
B.DISTR IN ('PERUS','JARAGUA','BRASILANDIA','SAPOPEMBA','SAO RAFAEL','IGUATEMI','CIDADE TIRADENTES','LAJEADO','ITAIM PAULISTA','JARDIM HELENA','CAPAO REDONDO','JARDIM ANGELA','PEDREIRA','GRAJAU','PARELHEIROS')
AND SG_SERIE_ENSINO IN ('BERC I','BERC II','BI E D','BII E D','MG I','MG I ED','MG II','MG II ED','MG UNIF','MG UNIF ED')

AND DATEDIFF(MM,DT_NASCIMENTO_ALUNO,GETDATE())<=6
--SELECT * FROM ##ALUNOS_ATE_6MESES_DISTR_PRIORITARIOS


DROP TABLE ##RESUMO_ESCOLAS_MATRIC_DISTR_PRIPRITARIOS
SELECT DRE,DISTR,
COUNT (DISTINCT CD_ESCOLA) AS QT_ESCOLAS,
COUNT (DISTINCT CD_ALUNO) AS MATR
INTO ##RESUMO_ESCOLAS_MATRIC_DISTR_PRIPRITARIOS

 FROM ##ALUNOS_ATE_6MESES_DISTR_PRIORITARIOS
 GROUP BY DRE,DISTR
 ORDER BY 1,2
 --SELECT * FROM ##RESUMO_ESCOLAS_MATRIC_DISTR_PRIPRITARIOS

 
 
----------------------------------------------------------------------------------
DROP TABLE ##ALUNOS_ATE_6MESES_TODOS_DISTRITOS
SELECT 
B.DRE,
B.DISTR,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
SG_ETAPA,
SG_SERIE_ENSINO,
CD_ALUNO,
NM_ALUNO,
CONVERT(VARCHAR,DT_NASCIMENTO_ALUNO,103) AS DT_NASC,
DATEDIFF(MM,DT_NASCIMENTO_ALUNO,GETDATE()) AS [Idade(meses)]

INTO ##ALUNOS_ATE_6MESES_TODOS_DISTRITOS

FROM SME_ALUNOS_DIARIO A

LEFT JOIN D_MISME_ESCOLA_TOTAL B ON A.CD_ESCOLA = B.CD_ESCOLA
WHERE DATEDIFF(MM,DT_NASCIMENTO_ALUNO,GETDATE())<=6
--SELECT * FROM ##ALUNOS_ATE_6MESES_TODOS_DISTRITOS
---------------------------------------------------------------
DROP TABLE ##RESUMO_ALUNOS_ATE_6MESES_TODOS_DISTRITOS
SELECT DRE,DISTR,
COUNT (DISTINCT CD_ESCOLA) AS QT_ESCOLAS,
COUNT (DISTINCT CD_ALUNO) AS MATR
INTO ##RESUMO_ALUNOS_ATE_6MESES_TODOS_DISTRITOS

 FROM ##ALUNOS_ATE_6MESES_TODOS_DISTRITOS
 GROUP BY DRE,DISTR
 ORDER BY 1,2
 --SELECT * FROM ##RESUMO_ALUNOS_ATE_6MESES_TODOS_DISTRITOS

------------------------------------------------------


DROP TABLE ##RESUMO_ESCOLAS_MATRIC_DISTR_PRIPRITARIOS
SELECT DISTR,DRE,
COUNT (DISTINCT CASE WHEN SG_TP_ESCOLA IN ('CECI','CEU CEI', 'CEI DIRET','CEMEI','CEU CEMEI','CR.P.CONV', 'CEI INDIR') THEN CD_ESCOLA END) AS 'Nº DE CRECHES',
COUNT (DISTINCT CASE WHEN SG_TP_ESCOLA IN ('CECI','CEU CEI', 'CEI DIRET','CEMEI','CEU CEMEI') THEN CD_ALUNO END ) AS 'QUANTIDADE DE BEBÊS POR CRECHE DIRETA',
COUNT (DISTINCT CASE WHEN SG_TP_ESCOLA IN ('CR.P.CONV', 'CEI INDIR') THEN CD_ESCOLA END) AS UNIDADES_INDIRETAS,
COUNT (DISTINCT CASE WHEN SG_TP_ESCOLA IN ('CR.P.CONV', 'CEI INDIR') THEN CD_ALUNO END ) AS MATR_INDIRETAS

--INTO ##RESUMO_ESCOLAS_MATRIC_DISTR_PRIPRITARIOS

 FROM ##ALUNOS_ATE_6MESES_DISTR_PRIORITARIOS
 GROUP BY DRE,DISTR
 ORDER BY 1,2
 --SELECT * FROM ##RESUMO_ESCOLAS_MATRIC_DISTR_PRIPRITARIOS