

SELECT 

DRE,
SG_TP_ESCOLA,
COUNT(DISTINCT CASE WHEN DIST_ESCOLA <1000 THEN COD_ALUNO ELSE NULL END) AS '<1 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 1000 AND 2000 THEN COD_ALUNO ELSE NULL END) AS '1 a 2 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 2000 AND 3000 THEN COD_ALUNO ELSE NULL END) AS '2 a 3 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 3000 AND 4000 THEN COD_ALUNO ELSE NULL END) AS '3 a 4 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 4000 AND 5000 THEN COD_ALUNO ELSE NULL END) AS '4 a 5 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 5000 AND 6000 THEN COD_ALUNO ELSE NULL END) AS '5 a 6 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA > 6000 THEN COD_ALUNO ELSE NULL END) AS '> 6 km'
FROM VW_ENDERECOS_ALUNOS_COM_RESPONSAVEIS
GROUP BY DRE,SG_TP_ESCOLA


SELECT 

SG_TP_ESCOLA,
COUNT(DISTINCT CASE WHEN DIST_ESCOLA <1500 THEN COD_ALUNO ELSE NULL END) AS '<1,5 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 1500 AND 2000 THEN COD_ALUNO ELSE NULL END) AS '1,5 a 2 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 2000 AND 3000 THEN COD_ALUNO ELSE NULL END) AS '2 a 3 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 3000 AND 4000 THEN COD_ALUNO ELSE NULL END) AS '3 a 4 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 4000 AND 5000 THEN COD_ALUNO ELSE NULL END) AS '4 a 5 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 5000 AND 6000 THEN COD_ALUNO ELSE NULL END) AS '5 a 6 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA > 6000 THEN COD_ALUNO ELSE NULL END) AS '> 6 km'
INTO ##RESUMO_DISTANCIA_POR_TP_ESCOLA
FROM VW_ENDERECOS_ALUNOS_COM_RESPONSAVEIS
GROUP BY SG_TP_ESCOLA WITH ROLLUP
--SELECT * FROM ##RESUMO_DISTANCIA_POR_TP_ESCOLA

SELECT 

DRE,
COUNT(DISTINCT CASE WHEN DIST_ESCOLA <1500 THEN COD_ALUNO ELSE NULL END) AS '<1,5 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 1500 AND 2000 THEN COD_ALUNO ELSE NULL END) AS '1,5 a 2 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 2000 AND 3000 THEN COD_ALUNO ELSE NULL END) AS '2 a 3 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 3000 AND 4000 THEN COD_ALUNO ELSE NULL END) AS '3 a 4 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 4000 AND 5000 THEN COD_ALUNO ELSE NULL END) AS '4 a 5 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 5000 AND 6000 THEN COD_ALUNO ELSE NULL END) AS '5 a 6 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA > 6000 THEN COD_ALUNO ELSE NULL END) AS '> 6 km'
INTO ##RESUMO_DISTANCIA_POR_DRE
FROM VW_ENDERECOS_ALUNOS_COM_RESPONSAVEIS
GROUP BY DRE WITH ROLLUP
--SELECT * FROM ##RESUMO_DISTANCIA_POR_DRE

SELECT 

ETAPA,
COUNT(DISTINCT CASE WHEN DIST_ESCOLA <1500 THEN COD_ALUNO ELSE NULL END) AS '<1,5 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 1500 AND 2000 THEN COD_ALUNO ELSE NULL END) AS '1,5 a 2 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 2000 AND 3000 THEN COD_ALUNO ELSE NULL END) AS '2 a 3 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 3000 AND 4000 THEN COD_ALUNO ELSE NULL END) AS '3 a 4 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 4000 AND 5000 THEN COD_ALUNO ELSE NULL END) AS '4 a 5 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA BETWEEN 5000 AND 6000 THEN COD_ALUNO ELSE NULL END) AS '5 a 6 km',
COUNT(DISTINCT CASE WHEN DIST_ESCOLA > 6000 THEN COD_ALUNO ELSE NULL END) AS '> 6 km'
INTO ##RESUMO_DISTANCIA_POR_ETAPA
FROM VW_ENDERECOS_ALUNOS_COM_RESPONSAVEIS
GROUP BY ETAPA WITH ROLLUP
--SELECT * FROM ##RESUMO_DISTANCIA_POR_ETAPA

--SELECT * FROM VW_ENDERECOS_ALUNOS_COM_RESPONSAVEIS
