DROP TABLE ##LISTA_ALUNOS_CCA
SELECT 
DRE AS DRE_CCA,
A.CD_ESCOLA AS CD_CCA,
CONCAT(SG_TP_ESCOLA,NOMESC) AS NM_CCA,
A.CD_TURMA_ESCOLA AS TURMA_CCA,
CD_ALUNO,
NM_ALUNO,
CONVERT(DATE,DT_NASCIMENTO_ALUNO,103) AS DT_NASC,
CASE WHEN CD_TIPO_TURNO=1 THEN 'MANHÃ'
     WHEN CD_TIPO_TURNO=2 THEN 'INTERMEDIARIO'
	 WHEN CD_TIPO_TURNO=3 THEN 'TARDE'
	 WHEN CD_TIPO_TURNO=4 THEN 'VESPERTINO'
	 WHEN CD_TIPO_TURNO=5 THEN 'NOITE'
	 WHEN CD_TIPO_TURNO=6 THEN 'INTEGRAL'
ELSE NULL END AS TURNO
INTO ##LISTA_ALUNOS_CCA
FROM SME_ALUNOS_DIARIO A
JOIN SME_CLASSES_DIARIO B ON A.CD_TURMA_ESCOLA=B.CD_TURMA_ESCOLA
JOIN SME_ESCOLA_DIARIO C ON A.CD_ESCOLA=C.CD_ESCOLA
WHERE A.CD_TIPO_PROGRAMA=430
--SELECT * FROM ##LISTA_ALUNOS_CCA

DROP TABLE ##LISTA_ALUNOS_ESC
SELECT 
DRE AS DRE_ESC,
A.CD_ESCOLA,
CONCAT(SG_TP_ESCOLA,NOMESC) AS NM_ESCOLA,
A.CD_TURMA_ESCOLA AS TURMA,
A.SG_ETAPA,
SG_SERIE_ENSINO,
CD_ALUNO,
NM_ALUNO,
CONVERT(DATE,DT_NASCIMENTO_ALUNO,103) AS DT_NASC,
CASE WHEN CD_TIPO_TURNO=1 THEN 'MANHÃ'
     WHEN CD_TIPO_TURNO=2 THEN 'INTERMEDIARIO'
	 WHEN CD_TIPO_TURNO=3 THEN 'TARDE'
	 WHEN CD_TIPO_TURNO=4 THEN 'VESPERTINO'
	 WHEN CD_TIPO_TURNO=5 THEN 'NOITE'
	 WHEN CD_TIPO_TURNO=6 THEN 'INTEGRAL'
ELSE NULL END AS TURNO_ESC,
A.CRDATE
INTO ##LISTA_ALUNOS_ESC
FROM SME_ALUNOS_DIARIO A
JOIN SME_CLASSES_DIARIO B ON A.CD_TURMA_ESCOLA=B.CD_TURMA_ESCOLA
JOIN SME_ESCOLA_DIARIO C ON A.CD_ESCOLA=C.CD_ESCOLA
WHERE A.CD_TIPO_PROGRAMA IS NULL
--SELECT * FROM ##LISTA_ALUNOS_ESC


DROP TABLE ##ALUNOS_CCA_TURMAS_ESCOLARICACAO
SELECT 
A.*,
DRE_ESC,
CD_ESCOLA,
NM_ESCOLA,
TURMA,
SG_ETAPA,
SG_SERIE_ENSINO,
TURNO_ESC,
CONVERT(DATE,CRDATE,103) AS DT_BASE
INTO ##ALUNOS_CCA_TURMAS_ESCOLARICACAO
FROM ##LISTA_ALUNOS_CCA A
LEFT JOIN ##LISTA_ALUNOS_ESC B ON A.CD_ALUNO=B.CD_ALUNO
--SELECT * FROM ##ALUNOS_CCA_TURMAS_ESCOLARICACAO

DROP TABLE ##ALUNOS_ESCOLARIZACAO_NOS_CCA
SELECT * 
INTO ##ALUNOS_ESCOLARIZACAO_NOS_CCA 
FROM ##ALUNOS_CCA_TURMAS_ESCOLARICACAO WHERE SG_ETAPA IS NOT NULL
--SELECT * FROM ##ALUNOS_ESCOLARIZACAO_NOS_CCA