USE Db_Local

DROP TABLE ##ALUNO_NM_SOCIAL
 SELECT * INTO ##ALUNO_NM_SOCIAL FROM DB_EDUCACAO_1_PRODAM.SE1426.DBO.ALUNO WHERE nm_social_aluno is not null

 --LISTA DE ALUNOS COM INDICAÇÃO DE NOME SOCIAL - EDUCAÇÃO INFANTIL - VERIFICAR

 DROP TABLE ##ALUNOS_INF_NOME_SOCIAL
 SELECT DISTINCT C.DRE, C.CD_ESCOLA,C.SG_TP_ESCOLA,C.NOMESC,SG_ETAPA,SG_SERIE_ENSINO,A.CD_ALUNO,A.NM_ALUNO,A.nm_social_aluno, CONVERT(VARCHAR,B.CRDATE-1,103) AS DT_BASE
 INTO ##ALUNOS_INF_NOME_SOCIAL
 FROM ##ALUNO_NM_SOCIAL A
 JOIN SME_ALUNOS_DIARIO B ON A.CD_ALUNO=B.CD_ALUNO
 JOIN SME_ESCOLA_DIARIO C ON B.CD_ESCOLA=C.CD_ESCOLA
 WHERE SG_ETAPA = 'ED INF' AND TP_ESCOLA IN (1,2,3,4,10,11,12,15,16,17,18,28,30,31) AND B.ST_MATRICULA=1 AND B.CD_SITUACAO_ALUNO=1
 ORDER BY 1,3,4

 --SELECT * FROM ##ALUNOS_INF_NOME_SOCIAL

 -------------------------------------------
 --LISTA DE ALUNOS COM IDENTIFICAÇÃO DE NOME SOCIAL
DROP TABLE ##ALUNOS_NOME_SOCIAL_
 SELECT C.DRE, C.CD_ESCOLA,C.SG_TP_ESCOLA,C.NOMESC,SG_ETAPA,SG_SERIE_ENSINO,A.CD_ALUNO,A.NM_ALUNO,A.nm_social_aluno, CONVERT(VARCHAR,B.CRDATE-1,103) AS DT_BASE
 INTO ##ALUNOS_NOME_SOCIAL_
 FROM ##ALUNO_NM_SOCIAL A
 JOIN SME_ALUNOS_DIARIO B ON A.CD_ALUNO=B.CD_ALUNO
 JOIN SME_ESCOLA_DIARIO C ON B.CD_ESCOLA=C.CD_ESCOLA
 WHERE SG_ETAPA <> 'ED INF' AND TP_ESCOLA IN (1,2,3,4,10,11,12,15,16,17,18,28,30,31) AND B.ST_MATRICULA=1 AND B.CD_SITUACAO_ALUNO=1

 --SELECT DISTINCT * FROM ##ALUNOS_NOME_SOCIAL_
 ----------------------------------------------------------------------------------------------
 DROP TABLE ##ALU_NM_SOCIAL_RESUMO 
 SELECT 
 SG_ETAPA,
 COUNT (CD_ALUNO) AS MATR
 INTO ##ALU_NM_SOCIAL_RESUMO
 FROM ##ALUNOS_NOME_SOCIAL_
 GROUP BY SG_ETAPA WITH ROLLUP
  --SELECT * FROM ##ALU_NM_SOCIAL_RESUMO
-------------------------------------------------------------------------------------------------







SELECT CD_ALUNO,CD_MATRICULA, ST_MATRICULA FROM D_MATRICULA WHERE CD_ALUNO IN (7622670,7622657,7579468,8033426,20020081) ORDER BY 1,2
 
SELECT * FROM ##ALUNOS_NOME_SOCIAL_ WHERE CD_ALUNO IN (7622670,7622657,7579468,8033426,20020081) ORDER BY CD_ALUNO

SELECT * FROM D_ALUNO WHERE CD_ALUNO IN (7622670,7622657,7579468,8033426,20020081)
SELECT * FROM SME_ALUNOS_DIARIO WHERE CD_ALUNO IN (7622670,7622657,7579468,8033426,20020081)



  