
/*
haveria possibilidade de nos 
enviar uma  lista de todos os alunos 
que não possuem o nome de pai 
no sistema EOL Capela do Socorro 
*/

DROP TABLE ##ALUNOS_SEM_NM_PAI_CS
SELECT
DRE,
A.CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
CD_ALUNO,
C.dc_raca_cor AS RACA_COR,
CD_SEXO_ALUNO AS SEXO,
D.nm_pais_mec AS PAÍS_ORIGEM,
CONVERT(VARCHAR,DT_NASCIMENTO_ALUNO,103) AS DT_NASC,
SG_ETAPA,
SG_SERIE_ENSINO,
NM_ALUNO,
NM_MAE_ALUNO,
NM_PAI_ALUNO,
CONVERT(VARCHAR,A.CRDATE,103) AS DT_BASE

INTO ##ALUNOS_SEM_NM_PAI_CS
FROM SME_ALUNOS_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN tipo_raca_cor C ON A.TP_RACA_COR= C.tp_raca_cor
JOIN PAIS_MEC D ON A.CD_PAIS_MEC=D.cd_pais_mec

WHERE A.CD_SERIE_ENSINO IS NOT NULL AND DRE = 'DRE - CS' AND NM_PAI_ALUNO IS NULL
--SELECT * FROM ##ALUNOS_SEM_NM_PAI_CS