/*
solicitamos que um relatório com a quantidade de crianças de Educação Infantil 
que residem no setor Pedreira 4  e que são atendidas pelo TEG por distância.
*/

--drop table ##ALUNOS_ED_INFANTIL_SETOR_5804_TEG
SELECT 
A.DRE,
A.CD_ESCOLA,
A.SG_TP_ESCOLA,
NOMESC,
SG_ETAPA,
SG_SERIE_ENSINO,
CD_ALUNO,
NOME_ALUNO,
TP_LOGRADOURO,
ENDEREÇO,
NR,
COMPL,
BAIRRO,
CEP,
B.DIST_SETOR,
A.DIST_ESCOLA,
A.FAIXA,
TEG,
TEG_BARREIRA,
DC_MOTIVO_TRANSPORTE

INTO ##ALUNOS_ED_INFANTIL_SETOR_5804_TEG

FROM ALUNOS_COM_TEG A
JOIN VW_ALUNOS_ENDERECOS_DISTRITO_SETOR B ON A.CD_ALUNO=B.COD_ALUNO
WHERE B.CD_DIST_SETOR = 5804 AND TEG_BARREIRA ='NAO' AND SG_ETAPA='ED INF'

--SELECT * FROM ##ALUNOS_ED_INFANTIL_SETOR_5804_TEG

-------------------------------------------------------------------------------------

--SELECT TOP 10 * FROM VW_ALUNOS_ENDERECOS_DISTRITO_SETOR WHERE DIST_SETOR LIKE 'BRASILANDIA%'

