/*Prezado José, 

Peço seus préstimos para nos fornecer relatório 
para os alunos matriculados no CEI ALPS PARELHEIROS, 
com unidades a distancia linear  de 1km para os endereços dos alunos:
No relatório deve constar:
Nome do aluno
EOL do aluno
Agrupamento
Endereço do aluno (separado por coluna, nome da rua, numero, bairro e CEP)
Distância para as Unidades;
Se possui TEG
Se tem deficiência
*/


DROP TABLE ##LISTA_ALUNOS_309222
SELECT 
A.AN_LETIVO,
C.DRE,
A.CD_ESCOLA,
C.SG_TP_ESCOLA,
C.NOMESC,
A.SG_ETAPA,
A.SG_SERIE_ENSINO,
D.DC_SERIE_ENSINO,
A.CD_ALUNO,
NM_ALUNO,
NM_MAE_ALUNO,
NM_PAI_ALUNO,
CONVERT(DATE,DT_NASCIMENTO_ALUNO,103) AS DT_NASC,
B.ENDERECO,
B.NR,
B.COMPL,
B.BAIRRO,
B.CEP,
B.DIST_ESCOLA,
CASE WHEN DEF1 IS NOT NULL THEN 'SIM' ELSE NULL END AS DEFICIENCIA,
E.TEG,
B.LAT_ALUNO,
B.LON_ALUNO,
CONVERT(DATE,A.CRDATE, 103) AS DT_BASE
INTO ##LISTA_ALUNOS_309222
FROM SME_ALUNOS_2025 A
JOIN (SELECT DISTINCT
      COD_ALUNO,
      CONCAT(TP_LOGRADOURO,' ',ENDEREÇO) AS ENDERECO,
      NR,
      COMPL,
      BAIRRO,
      CEP,
      DIST_ESCOLA,
      LAT_ALUNO,
      LON_ALUNO
      FROM VW_ALUNOS_ENDERECOS) B ON A.CD_ALUNO=B.COD_ALUNO
JOIN SME_ESCOLA_DIARIO C ON A.CD_ESCOLA=C.CD_ESCOLA

JOIN (SELECT	DISTINCT --EM TESE NÃO DEVERIA HAVER DUPLICADAS, MAS POR SEGURANÇA
       	CD_FAIXA,
       	CONVERT(DATETIME,CONVERT(VARCHAR(4),DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA) + CONVERT(VARCHAR(2), MM_INICIO_FAIXA) + CONVERT(VARCHAR(2), DD_INICIO_FAIXA)) AS DT_INICIO_FAIXA,
       	CONVERT(DATETIME,CONVERT(VARCHAR(4),DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_FIM_FAIXA) + CONVERT(VARCHAR(2), MM_FIM_FAIXA) + CONVERT(VARCHAR(2), DD_FIM_FAIXA)) AS DT_FIM_FAIXA,
       	CASE 
       		WHEN (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ - (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA)) = 1 THEN '0 E 1 ANO'
       		ELSE CONVERT(VARCHAR(2),(DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ - (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA))) + ' ANOS' 
       		END AS IDADE,
       	T1.CD_SERIE_ENSINO, 
       	T2.DC_SERIE_ENSINO,
       	T2.CD_CICLO_ENSINO,
       	T2.SG_SERIE_ENSINO,
       	T2.cd_etapa_ensino,
       	T3.dc_etapa_ensino
       FROM	D_FAIXA_SERIE AS T1
       INNER JOIN D_SERIE_ENSINO AS T2 ON T1.CD_SERIE_ENSINO = T2.CD_SERIE_ENSINO
       INNER JOIN D_ETAPA_ENSINO AS T3 ON T2.cd_etapa_ensino = T3.cd_etapa_ensino
       WHERE	T1.DT_INICIO <= GETDATE()
       		AND (T1.DT_FIM IS NULL OR T1.DT_FIM >= CONVERT(DATE,GETDATE()))
       		AND TP_FAIXA =5) D ON A.DT_NASCIMENTO_ALUNO BETWEEN D.DT_INICIO_FAIXA AND D.DT_FIM_FAIXA
LEFT JOIN ALUNOS_COM_TEG E ON A.CD_ALUNO=E.CD_ALUNO

WHERE 
A.CD_ESCOLA=309222

--SELECT * FROM ##LISTA_ALUNOS_309222

DROP TABLE ##DESTINOS
SELECT 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
CD_COORDENADA_GEO_Y,
CD_COORDENADA_GEO_X 
INTO ##DESTINOS
FROM SME_ESCOLA_DIARIO
WHERE DRE='DRE - CS' AND TP_ESCOLA IN (10,11,12,18,28,31) AND CD_SIT=1
--SELECT * FROM ##DESTINOS
--------------------------------------------------------------------------------


drop table ##lista_alunos_distsncia_1000_m_dre_cs
SELECT 
A.AN_LETIVO,
A.DRE,
A.CD_ESCOLA,
A.SG_TP_ESCOLA,
A.NOMESC,
A.NM_ALUNO,
A.SG_ETAPA,
A.SG_SERIE_ENSINO,
A.ENDERECO,
A.NR,
A.BAIRRO,
A.DIST_ESCOLA,
A.TEG,
A.DEFICIENCIA,
CONCAT(B.SG_TP_ESCOLA,B.NOMESC) AS ESCOLA_DESTINO,
FLOOR(FLOOR(SQRT(POWER((LAT_ALUNO * 1000000 - ( CD_COORDENADA_GEO_Y * 1000000) ),2) +  POWER((LON_ALUNO * 1000000  - (CD_COORDENADA_GEO_X * 1000000)),2)) / 10)/0.6) AS DIST_NOVO_DESTINO,
A.DT_BASE
INTO ##lista_alunos_distsncia_1000_m_dre_cs
FROM ##LISTA_ALUNOS_309222 A, ##DESTINOS B
WHERE
FLOOR(FLOOR(SQRT(POWER((LAT_ALUNO * 1000000 - ( CD_COORDENADA_GEO_Y * 1000000) ),2) +  POWER((LON_ALUNO * 1000000  - (CD_COORDENADA_GEO_X * 1000000)),2)) / 10)/0.6)<=1000
--SELECT * FROM ##lista_alunos_distsncia_1000_m_dre_cs