/*

Peço seus préstimos para nos fornecer relatório para alunos matriculados no MG2 em 2024, com distância linear a menos 1km para o endereço 
RUA ALBA VALDEZ, 5 - CEP: 04845-200  --> -23.751254995709367, -46.69653150353766
No relatório deve constar:

Nome do aluno
EOL do aluno
Agrupamento
Endereço do aluno (separado por coluna, nome da rua, numero, bairro e CEP)
Unidade de matrícula
Distância da Unidade de matrícula
Distância para o endereço indicado
Se possui TEG
Se tem deficiência
*/
DROP TABLE ##LISTA_ALUNOS_MGII_CS
SELECT 
C.DRE,
A.CD_ESCOLA,
C.SG_TP_ESCOLA,
C.NOMESC,
A.SG_ETAPA,
A.SG_SERIE_ENSINO,
D.DC_SERIE_ENSINO,
A.CD_ALUNO,
NM_ALUNO,
NM_MAE_ALUNO,
NM_PAI_ALUNO,
CONVERT(DATE,DT_NASCIMENTO_ALUNO,103) AS DT_NASC,
B.ENDERECO,
B.NR,
B.COMPL,
B.BAIRRO,
B.CEP,
B.DIST_ESCOLA,
CASE WHEN DEF1 IS NOT NULL THEN 'SIM' ELSE NULL END AS DEFICIENCIA,
E.TEG,
B.LAT_ALUNO,
B.LON_ALUNO,



CONVERT(DATE,A.CRDATE, 103) AS DT_BASE



INTO ##LISTA_ALUNOS_MGII_CS

FROM SME_ALUNOS_DIARIO A
JOIN (SELECT DISTINCT
      COD_ALUNO,
      CONCAT(TP_LOGRADOURO,' ',ENDEREÇO) AS ENDERECO,
      NR,
      COMPL,
      BAIRRO,
      CEP,
      DIST_ESCOLA,
      LAT_ALUNO,
      LON_ALUNO
      FROM VW_ALUNOS_ENDERECOS) B ON A.CD_ALUNO=B.COD_ALUNO
JOIN SME_ESCOLA_DIARIO C ON A.CD_ESCOLA=C.CD_ESCOLA

JOIN (SELECT	DISTINCT --EM TESE NÃO DEVERIA HAVER DUPLICADAS, MAS POR SEGURANÇA
       	CD_FAIXA,
       	CONVERT(DATETIME,CONVERT(VARCHAR(4),DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA) + CONVERT(VARCHAR(2), MM_INICIO_FAIXA) + CONVERT(VARCHAR(2), DD_INICIO_FAIXA)) AS DT_INICIO_FAIXA,
       	CONVERT(DATETIME,CONVERT(VARCHAR(4),DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_FIM_FAIXA) + CONVERT(VARCHAR(2), MM_FIM_FAIXA) + CONVERT(VARCHAR(2), DD_FIM_FAIXA)) AS DT_FIM_FAIXA,
       	CASE 
       		WHEN (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ - (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA)) = 1 THEN '0 E 1 ANO'
       		ELSE CONVERT(VARCHAR(2),(DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ - (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA))) + ' ANOS' 
       		END AS IDADE,
       	T1.CD_SERIE_ENSINO, 
       	T2.DC_SERIE_ENSINO,
       	T2.CD_CICLO_ENSINO,
       	T2.SG_SERIE_ENSINO,
       	T2.cd_etapa_ensino,
       	T3.dc_etapa_ensino
       FROM	D_FAIXA_SERIE AS T1
       INNER JOIN D_SERIE_ENSINO AS T2 ON T1.CD_SERIE_ENSINO = T2.CD_SERIE_ENSINO
       INNER JOIN D_ETAPA_ENSINO AS T3 ON T2.cd_etapa_ensino = T3.cd_etapa_ensino
       WHERE	T1.DT_INICIO <= GETDATE()
       		AND (T1.DT_FIM IS NULL OR T1.DT_FIM >= CONVERT(DATE,GETDATE()))
       		AND TP_FAIXA =5) D ON A.DT_NASCIMENTO_ALUNO BETWEEN D.DT_INICIO_FAIXA AND D.DT_FIM_FAIXA
LEFT JOIN ALUNOS_COM_TEG E ON A.CD_ALUNO=E.CD_ALUNO

WHERE 
C.DRE = 'DRE - CS'
AND C.REDE IN ('DIR','CONV')
AND D.CD_FAIXA=4

--SELECT * FROM ##LISTA_ALUNOS_MGII_CS

DROP TABLE ##alunos_lista_alunos_mg2_dre_cs_para_rua_alba_valdez_5_ate_1000_m
SELECT 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
SG_ETAPA,
SG_SERIE_ENSINO,
dc_serie_ensino,
CD_ALUNO,
NM_ALUNO,
ENDERECO,
NR,
COMPL,
BAIRRO,
CEP,
DIST_ESCOLA,
'RUA ALBA VALDEZ, 5' AS DESTINO,
FLOOR(FLOOR(SQRT(POWER((LAT_ALUNO * 1000000 - ( -23.751254995709367 * 1000000) ),2) +  POWER((LON_ALUNO * 1000000  - (-46.69653150353766 * 1000000)),2)) / 10)/0.6) AS DIST_DESTINO,
TEG,
DEFICIENCIA,
DT_BASE
INTO ##alunos_lista_alunos_mg2_dre_cs_para_rua_alba_valdez_5_ate_1000_m
 FROM ##LISTA_ALUNOS_MGII_CS 
WHERE FLOOR(FLOOR(SQRT(POWER((LAT_ALUNO * 1000000 - ( -23.751254995709367 * 1000000) ),2) +  POWER((LON_ALUNO * 1000000  - (-46.69653150353766 * 1000000)),2)) / 10)/0.6)<=1000

--SELECT * FROM ##alunos_lista_alunos_mg2_dre_cs_para_rua_alba_valdez_5_ate_1000_m
