DROP TABLE ##alunos_qtde_raca_cor
SELECT 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
COUNT (DISTINCT CASE WHEN dc_raca_cor ='AMARELA' THEN CD_ALUNO ELSE NULL END ) AS AMARELA,
COUNT (DISTINCT CASE WHEN dc_raca_cor ='BRANCA' THEN CD_ALUNO ELSE NULL END ) AS BRANCA,
COUNT (DISTINCT CASE WHEN dc_raca_cor ='INDIGENA' THEN CD_ALUNO ELSE NULL END ) AS INDIGENAA,
COUNT (DISTINCT CASE WHEN dc_raca_cor ='PARDA' THEN CD_ALUNO ELSE NULL END ) AS PARDA,
COUNT (DISTINCT CASE WHEN dc_raca_cor ='PRETA' THEN CD_ALUNO ELSE NULL END ) AS PRETA,
COUNT (DISTINCT CASE WHEN dc_raca_cor ='NAO INFORMADA' THEN CD_ALUNO ELSE NULL END ) AS 'NÃO INFORMADA',
COUNT (DISTINCT CASE WHEN dc_raca_cor ='RECUSOU INFORMAR'  THEN CD_ALUNO ELSE NULL END ) AS 'RECUSOU INFORMAR',

DT_BASE
into ##alunos_qtde_raca_cor
FROM [dbo].[VW_ALUNOS_ORIGEM_RACA_IDADE]
GROUP BY 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
DT_BASE
--select * from ##alunos_qtde_raca_cor
--SELECT DISTINCT DC_RACA_COR FROM [dbo].[VW_ALUNOS_ORIGEM_RACA_IDADE]