
/*
 Solicitamos para estudo de demanda uma planilha que conste todos os alunos por agrupamento Infantil I e Infantil II , 
 com código EOL da criança, nome completo, filiação, endereço completo e data de nascimento das EMEIs abaixo:

 - EMEI PEDROSO DE MORAES ( 090441 );

 - EMEI COMANDANTE MORENO ( 018384);

 - EMEI PERO NETO ( 097144)

 
  */
  DROP TABLE ##ALUNOS_INFANTIL_UNIDADES_090441_018384_097144
  SELECT 
  DRE,
  CD_ESCOLA,
  SG_TP_ESCOLA,
  NOME_ESCOLA,
  COD_ALUNO AS 'COD_EOL_CRIANCA', 
  NOME_ALUNO AS 'NOME_ALUNO', 
  nm_mae_aluno AS NOME_MÃE,
  nm_pai_aluno AS NOME_PAI,
  CONCAT (TP_LOGRADOURO,' ',ENDEREÇO,', ',NR,' ',COMPL, ' ',BAIRRO) AS 'ENDERECO',
  DT_NASCIMENTO_ALUNO AS 'DATA_NASCIMENTO',
  ETAPA,
  SERIE_ANO,
  DC_SERIE_ENSINO,
  CRDATE

  INTO ##ALUNOS_INFANTIL_UNIDADES_090441_018384_097144
   
  FROM 
  VW_ALUNOS_ENDERECOS_DISTRITO_SETOR A
  JOIN (SELECT	DISTINCT --EM TESE NÃO DEVERIA HAVER DUPLICADAS, MAS POR SEGURANÇA
       	CD_FAIXA,
       	CONVERT(DATETIME,CONVERT(VARCHAR(4),DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA) + CONVERT(VARCHAR(2), MM_INICIO_FAIXA) + CONVERT(VARCHAR(2), DD_INICIO_FAIXA)) AS DT_INICIO_FAIXA,
       	CONVERT(DATETIME,CONVERT(VARCHAR(4),DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_FIM_FAIXA) + CONVERT(VARCHAR(2), MM_FIM_FAIXA) + CONVERT(VARCHAR(2), DD_FIM_FAIXA)) AS DT_FIM_FAIXA,
       	CASE 
       		WHEN (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ - (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA)) = 1 THEN '0 E 1 ANO'
       		ELSE CONVERT(VARCHAR(2),(DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ - (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA))) + ' ANOS' 
       		END AS IDADE,
       	T1.CD_SERIE_ENSINO, 
       	T2.DC_SERIE_ENSINO,
       	T2.CD_CICLO_ENSINO,
       	T2.SG_SERIE_ENSINO,
       	T2.cd_etapa_ensino,
       	T3.dc_etapa_ensino
       FROM	D_FAIXA_SERIE AS T1
       INNER JOIN D_SERIE_ENSINO AS T2 ON T1.CD_SERIE_ENSINO = T2.CD_SERIE_ENSINO
       INNER JOIN D_ETAPA_ENSINO AS T3 ON T2.cd_etapa_ensino = T3.cd_etapa_ensino
       WHERE	T1.DT_INICIO <= GETDATE()
       		AND (T1.DT_FIM IS NULL OR T1.DT_FIM >= CONVERT(DATE,GETDATE()))
       		AND TP_FAIXA =5) B ON A.DT_NASCIMENTO_ALUNO BETWEEN B.DT_INICIO_FAIXA AND B.DT_FIM_FAIXA 
JOIN (SELECT DISTINCT cd_aluno,nm_mae_aluno,nm_pai_aluno FROM D_ALUNO) C ON A.COD_ALUNO=C.cd_aluno
  WHERE CD_ESCOLA IN(090441,018384,097144) AND CD_FAIXA IN(5,6)

--SELECT * FROM ##ALUNOS_INFANTIL_UNIDADES_090441_018384_097144 
/*
Necessitamos de uma planilha indicando a quantidade de MGII matriculados  por CEI, dos seguintes Distritos:
 
  - Distrito Vila Andrade;

  - Distrito  PInheiros;

  - Distrito Raposo Tavares;

  - Distrito Morumbi;

*/
  DROP TABLE ##MATRICULAS_MG2_DISTR_VILA_ANDRADE_PINHEIROS_RAPOSO_TAVARES_MORUMBI
  SELECT 
  DRE,
  CD_ESCOLA,
  SG_TP_ESCOLA,
  NOME_ESCOLA,
  DISTR AS DISTRITO,
  DC_SERIE_ENSINO,
  COUNT(COD_ALUNO) AS MATR,
  CRDATE
  INTO ##MATRICULAS_MG2_DISTR_VILA_ANDRADE_PINHEIROS_RAPOSO_TAVARES_MORUMBI
   FROM VW_ALUNOS_ENDERECOS_DISTRITO_SETOR A
  JOIN (SELECT	DISTINCT --EM TESE NÃO DEVERIA HAVER DUPLICADAS, MAS POR SEGURANÇA
       	CD_FAIXA,
       	CONVERT(DATETIME,CONVERT(VARCHAR(4),DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA) + CONVERT(VARCHAR(2), MM_INICIO_FAIXA) + CONVERT(VARCHAR(2), DD_INICIO_FAIXA)) AS DT_INICIO_FAIXA,
       	CONVERT(DATETIME,CONVERT(VARCHAR(4),DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_FIM_FAIXA) + CONVERT(VARCHAR(2), MM_FIM_FAIXA) + CONVERT(VARCHAR(2), DD_FIM_FAIXA)) AS DT_FIM_FAIXA,
       	CASE 
       		WHEN (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ - (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA)) = 1 THEN '0 E 1 ANO'
       		ELSE CONVERT(VARCHAR(2),(DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ - (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA))) + ' ANOS' 
       		END AS IDADE,
       	T1.CD_SERIE_ENSINO, 
       	T2.DC_SERIE_ENSINO,
       	T2.CD_CICLO_ENSINO,
       	T2.SG_SERIE_ENSINO,
       	T2.cd_etapa_ensino,
       	T3.dc_etapa_ensino
       FROM	D_FAIXA_SERIE AS T1
       INNER JOIN D_SERIE_ENSINO AS T2 ON T1.CD_SERIE_ENSINO = T2.CD_SERIE_ENSINO
       INNER JOIN D_ETAPA_ENSINO AS T3 ON T2.cd_etapa_ensino = T3.cd_etapa_ensino
       WHERE	T1.DT_INICIO <= GETDATE()
       		AND (T1.DT_FIM IS NULL OR T1.DT_FIM >= CONVERT(DATE,GETDATE()))
       		AND TP_FAIXA =5) B ON A.DT_NASCIMENTO_ALUNO BETWEEN B.DT_INICIO_FAIXA AND B.DT_FIM_FAIXA 
WHERE cd_faixa=4 AND DISTR IN ('VILA ANDRADE','PINHEIROS','RAPOSO TAVARES','MORUMBI')
GROUP BY 
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOME_ESCOLA,
DISTR,
dc_serie_ensino,
CRDATE
--SELECT TABLE ##MATRICULAS_MG2_DISTR_VILA_ANDRADE_PINHEIROS_RAPOSO_TAVARES_MORUMBI
