/*A Yasmin de ASCOM nos solicitou os dados de número de estudantes do Portas Abertas separados por nível básico, intermediário e avançado. Podem nos ajudar, por gentileza?

Ela disse que precisa desse retorno ainda hoje.
*/
DROP TABLE ##PORTAS_ABERTAS_RESUMO
SELECT DISTINCT
B.DRE,

COUNT (DISTINCT CASE WHEN A.CD_TIPO_PROGRAMA=399 THEN A.CD_ALUNO ELSE NULL END) AS [NIVEL BÁSICO],
COUNT (DISTINCT CASE WHEN A.CD_TIPO_PROGRAMA=400 THEN A.CD_ALUNO ELSE NULL END) AS [NIVEL INTERMEDIÁRIO],
COUNT (DISTINCT CASE WHEN A.CD_TIPO_PROGRAMA=401 THEN A.CD_ALUNO ELSE NULL END) AS [NIVEL AVANÇADO],
COUNT (DISTINCT CASE WHEN A.CD_TIPO_PROGRAMA IN (399,400,401) THEN A.CD_ALUNO ELSE NULL END) AS TOTAL
INTO ##PORTAS_ABERTAS_RESUMO
FROM SME_ALUNOS_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN tipo_programa C ON A.CD_TIPO_PROGRAMA=C.cd_tipo_programa
WHERE A.CD_TIPO_PROGRAMA IN(399,400,401)
GROUP BY
B.DRE WITH ROLLUP

--SELECT * FROM ##PORTAS_ABERTAS_RESUMO

DROP TABLE ##PORTAS_ABERTAS_LISTA
SELECT DISTINCT
B.DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
C.dc_tipo_programa,
A.CD_ALUNO,
D.nm_pais_mec,
CONVERT(VARCHAR,A.CRDATE-1,103) AS DT_BASE
INTO ##PORTAS_ABERTAS_LISTA
FROM SME_ALUNOS_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN tipo_programa C ON A.CD_TIPO_PROGRAMA=C.cd_tipo_programa
JOIN PAIS_MEC D ON A.CD_PAIS_MEC=D.CD_PAIS_MEC
WHERE A.CD_TIPO_PROGRAMA IN(399,400,401)
--SELECT * FROM ##PORTAS_ABERTAS_LISTA