

DROP TABLE ##ALUNOS_BERCARIO_DISTRITOS_PRIORITARIOS
SELECT 
B.DRE,
B.DISTR,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
SG_ETAPA,
SG_SERIE_ENSINO,
CD_ALUNO,
NM_ALUNO,
CONVERT(VARCHAR,DT_NASCIMENTO_ALUNO,103) AS DT_NASC,
DATEDIFF(MM,DT_NASCIMENTO_ALUNO,GETDATE()) AS [Idade(meses)]

INTO ##ALUNOS_BERCARIO_DISTRITOS_PRIORITARIOS

FROM SME_ALUNOS_DIARIO A

LEFT JOIN D_MISME_ESCOLA_TOTAL B ON A.CD_ESCOLA = B.CD_ESCOLA
WHERE 
B.DISTR IN ('PERUS','JARAGUA','BRASILANDIA','SAPOPEMBA','SAO RAFAEL','IGUATEMI','CIDADE TIRADENTES','LAJEADO','ITAIM PAULISTA','JARDIM HELENA','CAPAO REDONDO','JARDIM ANGELA','PEDREIRA','GRAJAU','PARELHEIROS')
AND SG_TP_ESCOLA IN ('CECI','CEU CEI', 'CEI DIRET','CEMEI','CEU CEMEI','CR.P.CONV', 'CEI INDIR')
AND SG_SERIE_ENSINO IN ('BERC I','BERC II')
--SELECT * FROM ##ALUNOS_BERCARIO_DISTRITOS_PRIORITARIOS




AND DATEDIFF(MM,DT_NASCIMENTO_ALUNO,GETDATE())<=6
--SELECT * FROM ##ALUNOS_ATE_6MESES_DISTR_PRIORITARIOS



DROP TABLE ##RESUMO_ALUNOS_BERCARIO_DISTRITOS_PRIORITARIOS
SELECT DISTR,DRE,
COUNT (DISTINCT CASE WHEN SG_TP_ESCOLA IN ('CECI','CEU CEI', 'CEI DIRET','CEMEI','CEU CEMEI','CR.P.CONV', 'CEI INDIR') THEN CD_ESCOLA END) AS 'Nº DE CRECHES',
COUNT (DISTINCT CASE WHEN SG_TP_ESCOLA IN ('CECI','CEU CEI', 'CEI DIRET','CEMEI','CEU CEMEI') THEN CD_ESCOLA END) AS 'CRECHES_DIR',
COUNT (DISTINCT CASE WHEN SG_TP_ESCOLA IN ('CR.P.CONV', 'CEI INDIR') THEN CD_ESCOLA END) AS 'CRECHES_INDIR',
COUNT (DISTINCT CASE WHEN SG_TP_ESCOLA IN ('CECI','CEU CEI', 'CEI DIRET','CEMEI','CEU CEMEI') THEN CD_ALUNO END ) AS 'QUANTIDADE DE BEBÊS POR CRECHE DIRETA',
COUNT (DISTINCT CASE WHEN (SG_TP_ESCOLA IN ('CECI','CEU CEI', 'CEI DIRET','CEMEI','CEU CEMEI') AND [Idade(meses)]<6) THEN CD_ALUNO END ) AS 'QUANTIDADE DE BEBÊS MENORES DE 6 MESES  - CRECHE DIRETA',
COUNT (DISTINCT CASE WHEN SG_TP_ESCOLA IN ('CR.P.CONV', 'CEI INDIR') THEN CD_ALUNO END) AS 'QUANTIDADE DE BEBÊS POR CRECHE INDIRETA/PARCEIRA',
COUNT (DISTINCT CASE WHEN (SG_TP_ESCOLA IN ('CR.P.CONV', 'CEI INDIR') AND [Idade(meses)]<6) THEN CD_ALUNO END) AS 'QUANTIDADE DE BEBÊS MENORES DE 6 MESES  - CRECHE INDIRETA/PARCEIRA'

INTO ##RESUMO_ALUNOS_BERCARIO_DISTRITOS_PRIORITARIOS

 FROM ##ALUNOS_BERCARIO_DISTRITOS_PRIORITARIOS

 GROUP BY DISTR,DRE

 --SELECT * FROM ##RESUMO_ALUNOS_BERCARIO_DISTRITOS_PRIORITARIOS
