
DROP TABLE ##TURMAS_MATRICULAS_MOVA
SELECT 
DRE,
A.CD_ESCOLA,
B.SG_TP_ESCOLA,
NOMESC,
B.ENDERECO,
B.NR,
B.COMPL,
B.BAIRRO,
COUNT(CD_TURMA_ESCOLA) AS TURMAS,
SUM(QT_VAGA_OFERECIDA) AS VAG_OFER,
SUM(AL_AT) AS MATR,
CONVERT(VARCHAR,A.CRDATE-1, 103) AS DT_BASE
INTO ##TURMAS_MATRICULAS_MOVA
FROM SME_CLASSES_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
WHERE TP_ESCOLA = 22
GROUP BY
DRE,
A.CD_ESCOLA,
B.SG_TP_ESCOLA,
NOMESC,
B.ENDERECO,
B.NR,
B.COMPL,
B.BAIRRO,
A.CRDATE
--SELECT * FROM ##TURMAS_MATRICULAS_MOVA


