
/*
-Quantas crianças (menores de 18 anos) estão hoje matriculadas no sistema municipal de ensino?
-Desse número, quantas são meninas e quantos são meninos?

*/
DROP TABLE ##ALUNOS_ATE_18_ANOS
SELECT 
DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
A.SG_ETAPA,
COUNT (DISTINCT CASE WHEN B.IDADE <18 AND B.CD_SEXO_ALUNO = 'F' THEN B.CD_ALUNO ELSE NULL END) AS 'ATÉ 18 ANOS FEM',
COUNT (DISTINCT CASE WHEN B.IDADE <18 AND B.CD_SEXO_ALUNO = 'M' THEN B.CD_ALUNO ELSE NULL END) AS 'ATÉ 18 ANOS MASC'

INTO ##ALUNOS_ATE_18_ANOS
FROM SME_ALUNOS_DIARIO A
JOIN VW_ALUNOS_ORIGEM_RACA_IDADE B ON A.CD_ALUNO=B.CD_ALUNO
WHERE A.SG_ETAPA IS NOT NULL AND B.TP_ESCOLA IN (1,2,3,4,10,11,12,13,16,17,18,28,31,31) AND nm_pais_mec <>'BRASIL'
GROUP BY 
DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
A.SG_ETAPA
--SELECT * FROM ##ALUNOS_ATE_18_ANOS

---------------------------------
/*me perdoe, preciso do número de crianças imigrantes:

Quantas crianças imigrantes (menores de 18 anos) estão hoje matriculadas no sistema municipal de ensino?
-Desse número, quantas são meninas e quantos são meninos?
*/
DROP TABLE ##ALUNOS_ATE_18_ANOS_MIGRANTES
SELECT 
DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
A.SG_ETAPA,
NM_PAIS_MEC AS PAÍS_ORIGEM,
COUNT (DISTINCT CASE WHEN B.IDADE <18 AND B.CD_SEXO_ALUNO = 'F' THEN B.CD_ALUNO ELSE NULL END) AS 'ATÉ 18 ANOS FEM',
COUNT (DISTINCT CASE WHEN B.IDADE <18 AND B.CD_SEXO_ALUNO = 'M' THEN B.CD_ALUNO ELSE NULL END) AS 'ATÉ 18 ANOS MASC'

INTO ##ALUNOS_ATE_18_ANOS_MIGRANTES
FROM SME_ALUNOS_DIARIO A
JOIN VW_ALUNOS_ORIGEM_RACA_IDADE B ON A.CD_ALUNO=B.CD_ALUNO
WHERE A.SG_ETAPA IS NOT NULL AND B.TP_ESCOLA IN (1,2,3,4,10,11,12,13,16,17,18,28,31,31) AND nm_pais_mec <>'BRASIL'
GROUP BY 
DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
A.SG_ETAPA,
NM_PAIS_MEC

--SELECT * FROM ##ALUNOS_ATE_18_ANOS_MIGRANTES

--SELECT * FROM VW_ALUNOS_ORIGEM_RACA_IDADE
