/*

Solicitamos relatório de alunos matriculados na EMEI CANAL DO COCAIA para o endereço Rua Alba Valdez, 05

Neste relatório deve constar 
NOME DO ALUNO
EOL DO ALUNO
ENDEREÇO RESIDENCIA (separado em colunas rua, número e bairro)
DISTANCIA APRA UNDIADE DE MATRÍCULA ATUAL
DISTANCIA PARA O ENDERÇEO MENCIONADO
USO DO TEG
*/
DROP TABLE ##ALUNOS_UNIDADE_019536_NOVO_DESTINO
SELECT 
nm_aluno AS 'NOME DO ALUNO',
COD_ALUNO AS 'EOL DO ALUNO',
CONCAT (UPPER (TP_LOGRADOURO),' ',ENDEREÇO) AS ENDEREÇO,
NR AS NÚMERO,
COMPL AS COMPLEMENTO,
DIST_ESCOLA AS 'DISTÂNCIA ESCOLA',
FLOOR(FLOOR(SQRT(POWER((LAT_ALUNO * 1000000 - (-23.75135319699197  * 1000000) ),2) +  POWER((LON_ALUNO * 1000000  - (-46.69657441887718 * 1000000)),2)) / 10)/0.6) AS 'DIST_RUA ALBA VALDEZ, 05',
BAIRRO,
TEG AS 'USO DO TEG'
INTO ##ALUNOS_UNIDADE_019536_NOVO_DESTINO
FROM VW_ALUNOS_ENDERECOS A
LEFT JOIN (SELECT 
	       CD_ESCOLA,
		   CD_ALUNO,
		   TEG FROM ALUNOS_COM_TEG WHERE CD_ESCOLA=019536) B ON A.COD_ALUNO=B.CD_ALUNO
WHERE A.cd_escola=019536

--SELECT * FROM ##ALUNOS_UNIDADE_019536_NOVO_DESTINO

