

Poderia encaminhar arquivo com os matriculados dos distritos BR 02, 03 e 04?


DROP TABLE ##ALUNOS_ED_INFANTIL_SETORRES_1102_1103_1104_TEG
SELECT 
A.DRE,
A.CD_ESCOLA,
A.SG_TP_ESCOLA,
NOMESC,
SG_ETAPA,
SG_SERIE_ENSINO,
CD_ALUNO,
NOME_ALUNO,
TP_LOGRADOURO,
ENDEREÇO,
NR,
COMPL,
BAIRRO,
CEP,
B.DIST_SETOR,
A.DIST_ESCOLA,
A.FAIXA,
TEG,
TEG_BARREIRA,
DC_MOTIVO_TRANSPORTE

INTO ##ALUNOS_ED_INFANTIL_SETORRES_1102_1103_1104_TEG

FROM ALUNOS_COM_TEG A
JOIN VW_ALUNOS_ENDERECOS_DISTRITO_SETOR B ON A.CD_ALUNO=B.COD_ALUNO
WHERE B.CD_DIST_SETOR IN(1102,1103,1104) AND TEG_BARREIRA ='NAO' AND SG_ETAPA='ED INF'

--SELECT * FROM ##ALUNOS_ED_INFANTIL_SETORRES_1102_1103_1104_TEG