Use Db_Loca
/*
Solicito arquivo com as seguintes informações sobre MOVA:
DRE,
OSC,
NOME DA UNIDADE MOVA,
ENDEREÇO,
BAIRRO,
CEP,
QUANTIDADE TURMAS MANHÃ,
QUANTIDADE ALUNOS MANHÃ,
QUANTIDADE TURMAS TARDE,
QUANTIDADEDE ALUNOS TARDE,
QUANTIDADE TURMAS NOITE,
QUANTIDADE ALUNOS NOITE
*/

DROP TABLE ##TUR_MATR_MOVA
SELECT 
DRE,
A.CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
ENDERECO,
NR,
BAIRRO,
CEP,
TUR_MANHA,
MATR_MANHA,
TUR_INTERM,
MATR_INTERM,
TUR_TARDE,
MATR_TARDE,
TUR_VESP,
MATR_VESP,
TUR_NOITE,
MATR_NOITE,
TUR_TOTAL,
MATR_TOTAL,
DT_BASE

INTO ##TUR_MATR_MOVA

FROM SME_ESCOLA_DIARIO A
JOIN (
      SELECT 
      CD_ESCOLA,
      ISNULL(COUNT (DISTINCT CASE WHEN (CD_TIPO_PROGRAMA=45 AND CD_TIPO_TURNO = 1) THEN CD_TURMA_ESCOLA ELSE NULL END),0) AS TUR_MANHA,
      ISNULL(SUM (CASE WHEN (CD_TIPO_PROGRAMA=45 AND CD_TIPO_TURNO = 1) THEN AL_AT ELSE NULL END),0) AS MATR_MANHA,
      ISNULL(COUNT (DISTINCT CASE WHEN (CD_TIPO_PROGRAMA=45 AND CD_TIPO_TURNO = 2) THEN CD_TURMA_ESCOLA ELSE NULL END),0) AS TUR_INTERM,
      ISNULL(SUM (CASE WHEN (CD_TIPO_PROGRAMA=45 AND CD_TIPO_TURNO = 2) THEN AL_AT ELSE NULL END),0) AS MATR_INTERM,
      ISNULL(COUNT (DISTINCT CASE WHEN (CD_TIPO_PROGRAMA=45 AND CD_TIPO_TURNO = 3) THEN CD_TURMA_ESCOLA ELSE NULL END),0) AS TUR_TARDE,
      ISNULL(SUM (CASE WHEN (CD_TIPO_PROGRAMA=45 AND CD_TIPO_TURNO = 3) THEN AL_AT ELSE NULL END),0) AS MATR_TARDE,
      ISNULL(COUNT (DISTINCT CASE WHEN (CD_TIPO_PROGRAMA=45 AND CD_TIPO_TURNO = 4) THEN CD_TURMA_ESCOLA ELSE NULL END),0) AS TUR_VESP,
      ISNULL(SUM (CASE WHEN (CD_TIPO_PROGRAMA=45 AND CD_TIPO_TURNO = 4) THEN AL_AT ELSE NULL END),0) AS MATR_VESP,
      ISNULL(COUNT (DISTINCT CASE WHEN (CD_TIPO_PROGRAMA=45 AND CD_TIPO_TURNO = 5) THEN CD_TURMA_ESCOLA ELSE NULL END),0) AS TUR_NOITE,
      ISNULL(SUM (CASE WHEN (CD_TIPO_PROGRAMA=45 AND CD_TIPO_TURNO = 5) THEN AL_AT ELSE NULL END),0) AS MATR_NOITE,
      COUNT (DISTINCT CASE WHEN CD_TIPO_PROGRAMA=45 THEN CD_TURMA_ESCOLA ELSE NULL END) AS TUR_TOTAL,
      SUM (CASE WHEN CD_TIPO_PROGRAMA=45 THEN AL_AT ELSE NULL END) AS MATR_TOTAL,
	  CONVERT(VARCHAR,CRDATE-1, 103) AS DT_BASE
      FROM SME_CLASSES_DIARIO 
      WHERE CD_TIPO_PROGRAMA=45
      GROUP BY
      CD_ESCOLA,CRDATE) B ON A.CD_ESCOLA=B.CD_ESCOLA
WHERE A.TP_ESCOLA=22
--SELECT * FROM ##TUR_MATR_MOVA

                             /*
                             cd_tipo_turno	dc_tipo_turno
                                   1	            Manhã               
                                   2	            Intermediário       
                                   3	            Tarde               
                                   4	            Vespertino          
                                   5	            Noite               
                                   6	            Integral            
                             */
---------------------------------------------------------------------------------------------------------------









