/*Solicitamos, se possível, um arquivo que demonstre as vagas oferecidas 
e o numero de matriculados da Unidade 200182- CIEJA - ROSE MARY FRASSON, PROFA. 
entre os anos de 2020 e 2024, para que possamos finalizar estudo de Demanda
*/


SELECT 
B.CODLOC,
TIPO,
DESLOC,
SUM(VAGOFER) AS VAGAS,
SUM(MATRIC) AS MATRIC,
YEAR(A.[DATABASE]) AS ANO
FROM [dbo].[turma_05_2024] A 
JOIN [dbo].[aj30_052024] B ON A.CODLOC=B.CODLOC
WHERE 
A.CODLOC=200182
GROUP BY
B.CODLOC,
TIPO,
DESLOC,
A.[DATABASE]
UNION
SELECT 
B.CODLOC,
TIPO,
DESLOC,
SUM(VAGOFER) AS VAGAS,
SUM(MATRIC) AS MATRIC,
YEAR(A.[DATABASE]) AS ANO
FROM [dbo].[turma_052023] A 
JOIN [dbo].[aj30_052024] B ON A.CODLOC=B.CODLOC
WHERE 
A.CODLOC=200182
GROUP BY
B.CODLOC,
TIPO,
DESLOC,
A.[DATABASE]
UNION
SELECT 
B.CODLOC,
TIPO,
DESLOC,
SUM(VAGOFER) AS VAGAS,
SUM(MATRIC) AS MATRIC,
YEAR(A.[DATABASE]) AS ANO
FROM [dbo].[turma_052022] A 
JOIN [dbo].[aj30_052024] B ON A.CODLOC=B.CODLOC
WHERE 
A.CODLOC=200182
GROUP BY
B.CODLOC,
TIPO,
DESLOC,
A.[DATABASE]
UNION
SELECT 
B.CODLOC,
TIPO,
DESLOC,
SUM(VAGOFER) AS VAGAS,
SUM(MATRIC) AS MATRIC,
YEAR(A.[DATABASE]) AS ANO
FROM [dbo].[turma_052021] A 
JOIN [dbo].[aj30_052024] B ON A.CODLOC=B.CODLOC
WHERE 
A.CODLOC=200182
GROUP BY
B.CODLOC,
TIPO,
DESLOC,
A.[DATABASE]
UNION
SELECT 
B.CODLOC,
TIPO,
DESLOC,
SUM(VAGOFER) AS VAGAS,
SUM(MATRIC) AS MATRIC,
YEAR(A.[DATABASE]) AS ANO
FROM [dbo].[turma_052020] A 
JOIN [dbo].[aj30_052024] B ON A.CODLOC=B.CODLOC
WHERE 
A.CODLOC=200182
GROUP BY
B.CODLOC,
TIPO,
DESLOC,
A.[DATABASE]


