
--CALCULA A IDADE DOS ALUNOS EM DIAS, MESES E ANOS


                DROP TABLE ##IDADES_ALUNOS
                SELECT 
                CD_ALUNO,
                DT_NASCIMENTO_ALUNO,
                CD_ESCOLA,
                DATEDIFF(DD,DT_NASCIMENTO_ALUNO,GETDATE()) AS DIAS,
                DATEDIFF(MM,DT_NASCIMENTO_ALUNO,GETDATE()) AS MESES,
                DATEDIFF(YY,DT_NASCIMENTO_ALUNO,GETDATE()) AS ANOS 
                INTO ##IDADES_ALUNOS
                FROM SME_ALUNOS_DIARIO
                --SELECT * FROM ##IDADES_ALUNOS
                --SELECT DT_NASCIMENTO_ALUNO,ANOS,MESES, DIAS FROM ##IDADES_ALUNOS ORDER BY ANOS desc

--------------------------------------------------------------------------------------------------------------------
--ALUNOS DE 0 A 3 MESES

DROP TABLE ##ALUNOS_0_A_3_MESES_POR_DRE_ESCOLA
SELECT 
B.DRE,
A.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
COUNT (DISTINCT CASE WHEN C.MESES=0 THEN C.CD_ALUNO ELSE NULL END) AS [< 1 MÊS],
COUNT (DISTINCT CASE WHEN C.MESES=1 THEN C.CD_ALUNO ELSE NULL END) AS [1 MÊS],
COUNT (DISTINCT CASE WHEN C.MESES=2 THEN C.CD_ALUNO ELSE NULL END) AS [2 MESES],
COUNT (DISTINCT CASE WHEN C.MESES=3 THEN C.CD_ALUNO ELSE NULL END) AS [3 MESES]
INTO ##ALUNOS_0_A_3_MESES_POR_DRE_ESCOLA
FROM SME_ALUNOS_DIARIO A 
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN ##IDADES_ALUNOS C ON A.CD_ALUNO=C.CD_ALUNO
WHERE C.MESES<=3 AND A.SG_ETAPA IS NOT NULL
GROUP BY B.DRE,
A.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC
--select * from ##ALUNOS_0_A_3_MESES_POR_DRE_ESCOLA
------------------------------------------------------------------------------------SELECT 
DROP TABLE ##ALUNOS_0_A_3_MESES_POR_DRE_ESCOLA_RESUMO
SELECT
B.SG_TP_ESCOLA,
COUNT (DISTINCT CASE WHEN C.MESES=0 THEN C.CD_ALUNO ELSE NULL END) AS [< 1 MÊS],
COUNT (DISTINCT CASE WHEN C.MESES=1 THEN C.CD_ALUNO ELSE NULL END) AS [1 MÊS],
COUNT (DISTINCT CASE WHEN C.MESES=2 THEN C.CD_ALUNO ELSE NULL END) AS [2 MESES],
COUNT (DISTINCT CASE WHEN C.MESES=3 THEN C.CD_ALUNO ELSE NULL END) AS [3 MESES]
INTO ##ALUNOS_0_A_3_MESES_POR_DRE_ESCOLA_RESUMO
FROM SME_ALUNOS_DIARIO A 
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN ##IDADES_ALUNOS C ON A.CD_ALUNO=C.CD_ALUNO
WHERE C.MESES<=3 AND A.SG_ETAPA IS NOT NULL
GROUP BY 
B.SG_TP_ESCOLA WITH ROLLUP
--select * from ##ALUNOS_0_A_3_MESES_POR_DRE_ESCOLA_RESUMO
------------------------------------------------------------------------------
--ALUNOS DE 0 A 3 ANOS
DROP TABLE  ##ALUNOS_0_A_3ANOS_POR_DRE_ESCOLA
SELECT 
B.DRE,
A.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
COUNT (DISTINCT CASE WHEN C.ANOS=0 THEN C.CD_ALUNO ELSE NULL END) AS [< 1 ANO],
COUNT (DISTINCT CASE WHEN C.ANOS=1 THEN C.CD_ALUNO ELSE NULL END) AS [1 ANO],
COUNT (DISTINCT CASE WHEN C.ANOS=2 THEN C.CD_ALUNO ELSE NULL END) AS [2 ANOS],
COUNT (DISTINCT CASE WHEN C.ANOS=3 THEN C.CD_ALUNO ELSE NULL END) AS [3 ANOS]
INTO ##ALUNOS_0_A_3ANOS_POR_DRE_ESCOLA
FROM SME_ALUNOS_DIARIO A 
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN ##IDADES_ALUNOS C ON A.CD_ALUNO=C.CD_ALUNO
WHERE C.ANOS<=3 AND A.SG_ETAPA IS NOT NULL

GROUP BY B.DRE,
A.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC
--SELECT * FROM ##ALUNOS_0_A_3ANOS_POR_DRE_ESCOLA
------------------------------------------------------------------------------------ 
DROP TABLE ##ALUNOS_0_A_3ANOS_POR_DRE_ESCOLA_RESUMO
SELECT
B.SG_TP_ESCOLA,
COUNT (DISTINCT CASE WHEN C.ANOS=0 THEN C.CD_ALUNO ELSE NULL END) AS [< 1 ANO],
COUNT (DISTINCT CASE WHEN C.ANOS=1 THEN C.CD_ALUNO ELSE NULL END) AS [1 ANO],
COUNT (DISTINCT CASE WHEN C.ANOS=2 THEN C.CD_ALUNO ELSE NULL END) AS [2 ANOS],
COUNT (DISTINCT CASE WHEN C.ANOS=3 THEN C.CD_ALUNO ELSE NULL END) AS [3 ANOS]
INTO ##ALUNOS_0_A_3ANOS_POR_DRE_ESCOLA_RESUMO
FROM SME_ALUNOS_DIARIO A 
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN ##IDADES_ALUNOS C ON A.CD_ALUNO=C.CD_ALUNO
WHERE C.ANOS<=3 AND A.SG_ETAPA IS NOT NULL

GROUP BY 
B.SG_TP_ESCOLA WITH ROLLUP
--SELECT * FROM ##ALUNOS_0_A_3ANOS_POR_DRE_ESCOLA_RESUMO
----------------------------------------------------------------------------------------------