
/*

Solicitamos uma planilha com a relação dos Estudantes dos CEU EMEF, EMEF, EMEFM,  EMEBS, EJA e CIEJA 
com os seguintes dados: Código Eol; Nome; Código Unidade Escolar; Sexo; Raça; NEE.
*/
DROP TABLE ##ESTUDANTES_FUND_EJA
SELECT 
DRE,
A.CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
SG_ETAPA,
SG_SERIE_ENSINO,
CD_ALUNO,
NM_ALUNO,
CD_SEXO_ALUNO AS SEXO,
c.dc_raca_cor as [RAÇA/COR],
DEF1,
DEF2,
DEF3,
DEF4,
DEF5,
DEF6,
DEF7,
DEF8,
DEF9,
DEF10,
CONVERT(VARCHAR,A.CRDATE-1,103) AS DT_BASE
INTO ##ESTUDANTES_FUND_EJA
FROM SME_ALUNOS_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN tipo_raca_cor C ON A.TP_RACA_COR=c.tp_raca_cor
WHERE A.CD_ETAPA_ENSINO  IN (2,3,5,13)
--SELECT * FROM ##ESTUDANTES_FUND_EJA

/*Por gentileza, envie-nos o número de estudantes por tipo de 
Unidades Educacionais EMEFs, EMEFMs, EMEMBSs e CIEJAs.
*/

SELECT DISTINCT
DRE,
COUNT(DISTINCT CASE WHEN SG_TP_ESCOLA IN ('EMEF','CEU EMEF') THEN CD_ALUNO ELSE NULL END) AS MT_EMEF,
COUNT(DISTINCT CASE WHEN SG_TP_ESCOLA ='EMEFM' THEN CD_ALUNO ELSE NULL END) AS MT_EMEFM,
COUNT(DISTINCT CASE WHEN SG_TP_ESCOLA ='EMEBS' THEN CD_ALUNO ELSE NULL END) AS MT_EMEBS,
COUNT(DISTINCT CASE WHEN SG_TP_ESCOLA ='CIEJA' THEN CD_ALUNO ELSE NULL END) AS MT_CIEJA
INTO ##MATR_FUND_EJA_POR_DRE
FROM ##ESTUDANTES_FUND_EJA

GROUP BY DRE WITH ROLLUP

SELECT DISTINCT
SG_ETAPA,
COUNT(DISTINCT CASE WHEN SG_TP_ESCOLA IN ('EMEF','CEU EMEF') THEN CD_ALUNO ELSE NULL END) AS MT_EMEF,
COUNT(DISTINCT CASE WHEN SG_TP_ESCOLA ='EMEFM' THEN CD_ALUNO ELSE NULL END) AS MT_EMEFM,
COUNT(DISTINCT CASE WHEN SG_TP_ESCOLA ='EMEBS' THEN CD_ALUNO ELSE NULL END) AS MT_EMEBS,
COUNT(DISTINCT CASE WHEN SG_TP_ESCOLA ='CIEJA' THEN CD_ALUNO ELSE NULL END) AS MT_CIEJA
INTO ##MATR_FUND_EJA_POR_ETAPA
FROM ##ESTUDANTES_FUND_EJA

GROUP BY SG_ETAPA WITH ROLLUP



SELECT
tp_necessidade_especial AS COD_DEF,
dc_necessidade_especial AS DEFICIENCIA
INTO CODIGOS_DEFICIENCIA
FROM tipo_necessidade_especial WHERE dt_cancelamento IS NULL AND tp_necessidade_especial <>15.



SELECT DISTINCT CD_ETAPA_ENSINO, SG_ETAPA FROM SME_ALUNOS_DIARIO


