
DROP TABLE ##ALUNOS_EJA_SEM_RA
SELECT 
DRE,
A.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
A.SG_ETAPA,
A.SG_SERIE_ENSINO,
A.CD_TURMA_ESCOLA,
A.NM_ALUNO,
A.CD_ALUNO,
A.RA,
A.CRDATE

INTO ##ALUNOS_EJA_SEM_RA

FROM SME_ALUNOS_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA

 WHERE SG_ETAPA LIKE'%EJA%' AND RA IS NULL

 --SELECT * FROM ##ALUNOS_EJA_SEM_RA