





DROP TABLE ##ALUNOS_CPF
SELECT DISTINCT
A.AN_LETIVO,
B.DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
SG_ETAPA,
SG_SERIE_ENSINO,
NM_ALUNO,
C.cd_cpf_aluno,
CONVERT(VARCHAR,A.CRDATE-1,103) AS DT_BASE
INTO ##ALUNOS_CPF

FROM SME_ALUNOS_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN (SELECT CD_ALUNO, CD_CPF_ALUNO FROM D_ALUNO) C ON A.CD_ALUNO=C.cd_aluno

WHERE A.SG_ETAPA IS NOT NULL AND B.TP_ESCOLA IN (1,2,3,4,10,11,12,13,16,17,18,28,30,31)
--SELECT * FROM ##ALUNOS_CPF