
--QUANTIDADE DE TURMAS E MATRICULAS DE ATIVIDADES COMPLEMENTARES - ATCOMP
DROP TABLE ##TURMAS_MATR_ATCOMP
SELECT 
B.DRE AS DIRETORIA,
'ATCOMP'AS MODAL,
C.dc_tipo_programa AS DESCRICAO,
COUNT (DISTINCT A.CD_TURMA_ESCOLA) AS TURMAS,
COUNT (DISTINCT A.CD_ALUNO) AS MATRÍCULAS,
CONVERT(VARCHAR,A.CRDATE-1,103) AS DT_BASE
INTO ##TURMAS_MATR_ATCOMP
FROM SME_ALUNOS_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN D_TIPO_PROGRAMA C ON A.CD_TIPO_PROGRAMA=C.cd_tipo_programa
WHERE A.SG_ETAPA IS NULL
GROUP BY
B.DRE,
C.dc_tipo_programa,
A.CRDATE
--SELECT * FROM ##TURMAS_MATR_ATCOMP

--SELECT * FROM SME_ESCOLA_DIARIO