
--RESUMO
SELECT SUM(MT_MEDI) AS MT_MEDIO, SUM(MT_FUND) AS MT_FUND, SUM(MT_EI) AS MT_EI, SUM(MT_EJA) AS MT_EJA, SUM(MT_MOVA) AS MT_MOVA FROM D_MISME_EE_ESCOLA_TOTAL
--WHERE REDE IS NOT NULL
UNION
SELECT SUM(MT_MEDI) AS MT_MEDIO, SUM(MT_FUND) AS MT_FUND, SUM(MT_EI) AS MT_EI, SUM(MT_EJA) AS MT_EJA, SUM(MT_MOVA) AS MT_MOVA FROM D_MISME_ESCOLA_TOTAL
--WHERE REDE IS NOT NULL
--GROUP BY REDE WITH ROLLUP

-----------------------------------------------
--MATRICULAS MEDIO POR ESCOLA
select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC, SUM(MT_MEDI) AS MT_MEDIO, CRDATE from D_MISME_EE_ESCOLA_TOTAL
WHERE MT_MEDI>0
GROUP BY DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC,CRDATE
UNION
select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC, SUM(MT_MEDI) AS MT_MEDIO, CRDATE from D_MISME_ESCOLA_TOTAL
WHERE MT_MEDI>0
GROUP BY DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC,CRDATE

--MATRICULAS FUND POR ESCOLA

select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC, SUM(MT_FUND) AS MT_FUND, SUM(MT_FINI) AS MT_F1, SUM(MT_FFIN) AS MT_F2, CRDATE from D_MISME_EE_ESCOLA_TOTAL
WHERE MT_FUND>0
GROUP BY DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC,CRDATE
UNION
select DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC, SUM(MT_FUND) AS MT_FUND,SUM(MT_FINI) AS MT_F1, SUM(MT_FFIN) AS MT_F2, CRDATE from D_MISME_ESCOLA_TOTAL
WHERE MT_FUND>0
GROUP BY DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC,CRDATE


--MATRICULAS ED INFANTIL POR ESCOLA


select REDE,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC, SUM(MT_EI) AS MT_ED_INF, SUM(MT_CRECHE) AS MT_CRECHE, SUM(MT_PRE) AS MT_PRE, CRDATE from D_MISME_EE_ESCOLA_TOTAL
WHERE MT_EI>0
GROUP BY REDE,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC,CRDATE
UNION
select REDE,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC, SUM(MT_EI) AS MT_ED_INF, SUM(MT_CRECHE) AS MT_CRECHE, SUM(MT_PRE) AS MT_PRE, CRDATE from D_MISME_ESCOLA_TOTAL
WHERE MT_EI>0
GROUP BY REDE,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC,CRDATE


--MATRICULAS MOVA POR ESCOLA

select REDE,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC, SUM(MT_MOVA) AS MT_MOVA, CRDATE from D_MISME_ESCOLA_TOTAL
WHERE  MT_MOVA>0
GROUP BY REDE,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC,CRDATE

--MATRICULAS EJA POR ESCOLA

select REDE,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC, SUM(MT_EJA) AS MT_EJA,  CRDATE from D_MISME_ESCOLA_TOTAL
WHERE MT_EJA>0
GROUP BY REDE,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC,CRDATE



--SELECT * FROM MISME_ESCOLA_TOTAL