/*Prezados(as), boa tarde!

Solicito a gentileza de enviarem dados atualizados, no sistema EOL, com as seguintes informações das 5 formas de atendimento da EJA (EJA Regular, EJA Modular, CIEJA, CMCT e MOVA-SP):
Gênero;
Nacionalidade;
Raça / cor;
Pessoa com deficiência;
Aluno maior de idade.
Desde já agradeço a costumeira parceria.

Atenciosamente,
*/
SELECT 
DRE,
A.CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
CD_ALUNO,
CD_SEXO_ALUNO AS SEXO,
C.nm_pais_mec AS 'PAÍS ORIGEM', 
CASE WHEN TP_RACA_COR=1 THEN 'BRANCA'
     WHEN TP_RACA_COR=2 THEN 'PRETA'
	 WHEN TP_RACA_COR=3 THEN 'PARDA'
	 WHEN TP_RACA_COR=4 THEN 'AMARELA'
	 WHEN TP_RACA_COR=5 THEN 'INDÍGENA'
	 WHEN TP_RACA_COR=6 THEN 'NÃO INFORMADA'
	 WHEN TP_RACA_COR=7 THEN 'RECUSOU INFORMAR'
ELSE NULL END AS 'RACA/COR',
CASE WHEN DEF1 IS NOT NULL THEN 'SIM' ELSE NULL END AS DEFICIENCIA,
DT_NASCIMENTO_ALUNO,
DATEDIFF(YEAR,DT_NASCIMENTO_ALUNO,GETDATE()) AS IDADE,
CASE WHEN DATEDIFF(YEAR,DT_NASCIMENTO_ALUNO,GETDATE())>=18 THEN 'SIM' ELSE NULL END AS 'MAIOR DE IDADE',
SG_ETAPA,
SG_SERIE_ENSINO,
CASE WHEN CD_TIPO_PROGRAMA=45 THEN 'MOVA' ELSE NULL END AS MOVA


FROM SME_ALUNOS_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN PAIS_MEC C ON A.CD_PAIS_MEC=C.cd_pais_mec
WHERE (SG_ETAPA LIKE 'EJA%' OR CD_TIPO_PROGRAMA=45)



SELECT DISTINCT * FROM D_MISME_ESCOLA_TOTAL WHERE SG_TP_ESCOLA='CMCT'

