	
SELECT DISTINCT
    D.DRE,
	D.CD_ESCOLA,
	D.SG_TP_ESCOLA,
	D.NOMESC,
	A.SG_ETAPA,
	A.SG_SERIE_ENSINO,
	A.NM_ALUNO,
	A.cd_matricula,
	A.CD_ALUNO,
    B.IN_SOLICITACAO_TRANSFERENCIA AS SOLIC_TRANSF,
	CASE WHEN B.TP_ORIGEM_MATRICULA = 1 THEN 'INICIAL'
	     WHEN B.TP_ORIGEM_MATRICULA = 2 THEN 'REMANEJADO ENTRADA'
		 WHEN B.TP_ORIGEM_MATRICULA = 3 THEN 'RECLASSIFICADO ENTRADA'
	ELSE NULL END AS ORIGEM_MATRICULA,

	CASE WHEN A.tp_matricula = 1 THEN 'ANTECIPADA'
	     WHEN A.tp_matricula = 2 THEN 'REMATRICULA'
		 WHEN A.tp_matricula = 3 THEN 'COMPATIBILIZADA'
		 WHEN A.tp_matricula = 4 THEN 'DIRETA'
		 WHEN A.tp_matricula = 5 THEN 'CARGA'
		 WHEN A.tp_matricula = 6 THEN 'TRANSFERÊNCIA'
    ELSE NULL END AS TIPO_MATRICULA,
		
	CASE --WHEN B.CD_SITUACAO_ALUNO IN (1,5,6,10,13) THEN 'ATIVO' --1=ATIVO, 5=CONCLUIDO,6=PENDENTE DE REMATRICULA, 10=REMATRICULADO, 13=SEM CONTINUIDADE
	     
		 WHEN B.CD_SITUACAO_ALUNO = 1  THEN 'ATIVO'
		 WHEN B.CD_SITUACAO_ALUNO = 2  THEN 'EVADIDO'
		 WHEN B.CD_SITUACAO_ALUNO = 3  THEN 'TRANSFERIDO'
		 WHEN B.CD_SITUACAO_ALUNO = 4  THEN 'EXCLUIDO'
		 WHEN B.CD_SITUACAO_ALUNO = 5  THEN 'CONCLUIDO'
		 WHEN B.CD_SITUACAO_ALUNO = 6  THEN 'PENDENTE DE REMATRICULA'
		 WHEN B.CD_SITUACAO_ALUNO = 7  THEN 'FALECIDO'
		 WHEN B.CD_SITUACAO_ALUNO = 8  THEN 'NÃO COMPARECEU'
	   --WHEN B.CD_SITUACAO_ALUNO = 9  THEN '?'
		 WHEN B.CD_SITUACAO_ALUNO = 10 THEN 'REMATRICULADO'
		 WHEN B.CD_SITUACAO_ALUNO = 11 THEN 'DESLOCAMENTO'
		 WHEN B.CD_SITUACAO_ALUNO = 13 THEN 'SEM CONTINUIDADE'
		 WHEN B.CD_SITUACAO_ALUNO = 12 THEN 'CESSADO'
		 WHEN B.CD_SITUACAO_ALUNO = 14 THEN 'REMANEJADO SAIDA'
		 WHEN B.CD_SITUACAO_ALUNO = 15 THEN 'RECLASSIFICADO SAIDA'		 
		 WHEN B.CD_SITUACAO_ALUNO = 16 THEN 'TRANSFERIDO SED'
		 WHEN B.CD_SITUACAO_ALUNO = 17 THEN 'AFASTADO ED FISICA'
	ELSE NULL END AS SITUACAO_ALUNO,
	A.DT_STATUS_MATRICULA,
	dt_atlz_tab AS DT_MATRICULA, --dt_atz_tab é o mesmo que dt+situacao_aluno
	
	CONVERT(VARCHAR,A.CRDATE-1,103) AS DT_BASE
FROM SME_ALUNOS_DIARIO A
LEFT JOIN D_MATRICULA_TURMA_ESCOLA B ON A.CD_MATRICULA=B.cd_matricula
LEFT JOIN D_MATRICULA C ON A.CD_MATRICULA=C.cd_matricula
JOIN SME_ESCOLA_DIARIO D ON A.CD_ESCOLA=D.CD_ESCOLA



WHERE A.SG_ETAPA IS NOT NULL 
--AND C.st_matricula=
--AND A.AN_LETIVO='2023'
AND A.DT_STATUS_MATRICULA >='2023-08-31'
AND TP_ESCOLA IN (1,3,4,13,16)
AND D.DRE = 'DRE - PE'
order by CD_ALUNO


	--SELECT * FROM SME_ALUNOS_DIARIO