/*número de agrupamentos por ambiente, nas unidades da educação infantil 
(diretas, indiretas e parceiras)
*/
DROP TABLE ##AGRUPAMENTOS_POR_AMBIENTES_ED_INF
SELECT 
REDE,
--SG_TP_ESCOLA,
DC_TIPO_AMBIENTE AS AMBIENTE,
SG_SERIE_ENSINO AS AGRUPAMENTO,
COUNT (DISTINCT CASE WHEN (C.TP_ESCOLA IN (2,10,11,12,17,18,28,31) AND A.CD_TIPO_PROGRAMA IS NULL) THEN A.CD_TURMA_ESCOLA ELSE NULL END) AS QT_TURMAS

INTO ##AGRUPAMENTOS_POR_AMBIENTES_ED_INF

FROM SME_CLASSES_DIARIO A
JOIN SME_ALUNOS_DIARIO B ON A.CD_TURMA_ESCOLA=B.CD_TURMA_ESCOLA
JOIN SME_ESCOLA_DIARIO C ON A.CD_ESCOLA=C.CD_ESCOLA


WHERE C.TP_ESCOLA IN (2,10,11,12,17,18,28,31) AND A.CD_TIPO_PROGRAMA IS NULL 
GROUP BY 
REDE,
--SG_TP_ESCOLA,
DC_TIPO_AMBIENTE,
SG_SERIE_ENSINO

--SELECT * FROM ##AGRUPAMENTOS_POR_AMBIENTES_ED_INF

--@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
DROP TABLE ##AGRUPAMENTOS_POR_AMBIENTES_ED_INF_LISTA
SELECT DISTINCT
REDE,
DRE,
A.CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
DC_TIPO_AMBIENTE AS AMBIENTE,
A.CD_TURMA_ESCOLA,
SG_SERIE_ENSINO AS AGRUPAMENTO

INTO ##AGRUPAMENTOS_POR_AMBIENTES_ED_INF_LISTA

FROM SME_CLASSES_DIARIO A
JOIN SME_ALUNOS_DIARIO B ON A.CD_TURMA_ESCOLA=B.CD_TURMA_ESCOLA
JOIN SME_ESCOLA_DIARIO C ON A.CD_ESCOLA=C.CD_ESCOLA
WHERE C.TP_ESCOLA IN (2,10,11,12,17,18,28,31) AND A.CD_TIPO_PROGRAMA IS NULL 
ORDER BY CD_ESCOLA
--SELECT * FROM ##AGRUPAMENTOS_POR_AMBIENTES_ED_INF_LISTA