/*
"Por gentileza, solicitamos estudo ponto a ponto do endereço das crianças do CEI CANTINHO DO BRYAN - 
EOL 400661, Rua Peixoto Gomide, 305 - Bela Vista em relação as unidades ao redor até 3,0 km.
*/
DROP TABLE ##ALUNOS_400661
SELECT
A.cd_escola,
C.SG_TP_ESCOLA AS TIPO,
C.NOMESC AS NM_ESCOLA,
COD_ALUNO,
SG_ETAPA AS ETAPA,
SG_SERIE_ENSINO AS SERIE,
CD_TURMA_ESCOLA,
B.NM_ALUNO,
LAT_ALUNO,
LON_ALUNO,
CONCAT(TP_LOGRADOURO, ' ',ENDEREÇO,', ',A.NR,' ',A.COMPL,' ',A.BAIRRO) AS END_ALUNO,
DIST_ESCOLA,
DIST_CARRO
INTO ##ALUNOS_400661
FROM  VW_ALUNOS_ENDERECOS A
JOIN SME_ALUNOS_DIARIO B ON A.COD_ALUNO=B.CD_ALUNO
JOIN SME_ESCOLA_DIARIO C ON A.cd_escola=C.CD_ESCOLA
WHERE A.CD_ESCOLA =400661 
--SELECT * FROM ##ALUNOS_400661
/*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*/

DROP TABLE ##ESTUDO_DISTANCIA_ALU_NOVAS_ESCOLAS_400661
SELECT distinct
A.*,
B.CD_ESCOLA AS CD_ESC_DESTINO,
B.SG_TP_ESCOLA AS TP_ESC_DESTINO,
B.NOMESC AS NM_ESC_DESTINO,


--CONCAT (DRE,' ',B.CD_ESCOLA,'- ',B.SG_TP_ESCOLA,'- ',B.NOMESC) AS DESTINO,
FLOOR(FLOOR(SQRT(POWER((LAT_ALUNO * 1000000 - (CD_COORDENADA_GEO_Y * 1000000) ),2) +  
				 POWER((LON_ALUNO * 1000000 - (CD_COORDENADA_GEO_X * 1000000)),2)) / 10)/0.6) AS DISTANCIA

INTO ##ESTUDO_DISTANCIA_ALU_NOVAS_ESCOLAS_400661
FROM ##ALUNOS_400661 A, SME_ESCOLA_DIARIO B
WHERE 
FLOOR(FLOOR(SQRT(POWER((LAT_ALUNO * 1000000 - (CD_COORDENADA_GEO_Y * 1000000) ),2) +  
				 POWER((LON_ALUNO * 1000000 - (CD_COORDENADA_GEO_X * 1000000)),2)) / 10)/0.6) <=3000

AND B.TP_ESCOLA IN (10,11,12,28,31) AND B.CD_ESCOLA NOT IN(400661)
--SELECT * FROM ##ESTUDO_DISTANCIA_ALU_NOVAS_ESCOLAS_400661

--select * from SME_ALUNOS_DIARIO


