--ajustado para educacao especial

EXEC PROC_AUX_MIEST

--DECLARE @date VARCHAR(255) = '12/5/2019';  
--SELECT EOMONTH ( @date ) AS Result;  

DECLARE @DURCLASSE INT SET @DURCLASSE = 0 
DECLARE @SEMESTRE DATE SET @SEMESTRE = '2010-07-21' 

      IF (SELECT DISTINCT MIN(AN_LETIVO) FROM D_TURMA_ESCOLA) > YEAR(GETDATE()) 
         (SELECT @DURCLASSE = @DURCLASSE + 2) 
  ELSE
  
  IF MONTH(@SEMESTRE) < MONTH(GETDATE()) 
 (SELECT @DURCLASSE = @DURCLASSE + 1) 
  ELSE 
 (SELECT @DURCLASSE = @DURCLASSE + 2)


/*--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----ESSE AJUSTE SERA RODADO SOMENTE NO SEGUNDO SEMESTRE DE 2020 PARA AJUSTE DAS CLASSES PROFISISONALIZANTE E PROFISSIONALIZANTE BASICA DE SEMESTRAL PARA ANULA
-- AS CLASSES DE EJA JA FORAM AJUSTADAS NA ORIGEM...
--VERIFICAR COMO FICARÁ NO DECORRER DO MES DE AGOSTO/2020 SE FOR MANTIDO REGRA, AJUSTAR NAQUERIE DE BACKUP


 IF 
	(SELECT	MAX(AN_LETIVO) FROM D_TURMA_ESCOLA) = 2020

	update a set CD_TIPO_PERIODICIDADE = 1 

	FROM SME_CLASSES_DIARIO A
	WHERE	
			AN_LETIVO = 2020 
			AND CD_TIPO_PERIODICIDADE = 3 
			and (CD_ETAPA_ENSINO = 14 OR CD_TIPO_PROGRAMA IN (13,27,32,33,44,70))
ELSE 
	PRINT ' NÃO ATUALIZADO'

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/



IF EXISTS 
(SELECT * FROM SYSOBJECTS WHERE NAME = 'D_MISME_DRE_DISTR_SETOR')
DROP TABLE D_MISME_DRE_DISTR_SETOR

SELECT 
	NOMEDEP
	,REDE
	,DRE
	,DISTR
	,SETOR
	
/*================================================================================================
--ALUNOS
================================================================================================*/
--CRECHE/BERÇARIO
						,MT_EI = SUM(CASE WHEN CD_SERIE_ENSINO IN (1,3,4,6,11,27,28,29,23,24,297,25,26,319,320,321,322,307,308,309,311,313,314)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END) 											
																																																																																							
					,MT_CRECHE = SUM(CASE WHEN CD_SERIE_ENSINO IN (1,3,4,6,11,27,28,29,307,308,309,311,321,322)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)														
					,MT_B1 = SUM(CASE WHEN CD_SERIE_ENSINO IN (1,3,307)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																			
					,MT_B2 = SUM(CASE WHEN CD_SERIE_ENSINO IN (4,6,308)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																			
																																																																												
					--CRECHE/MINIGRUPOS																																																																														
					,MT_MG1 = SUM(CASE WHEN CD_SERIE_ENSINO IN (11,27,309)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_MG2 = SUM(CASE WHEN CD_SERIE_ENSINO IN (28,29,311)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_MG_UNI = SUM(CASE WHEN CD_SERIE_ENSINO IN (321,322)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																	
																																																																																							
					--INFANTIL/PRE ESCOLA																																																																													
					,MT_PRE = SUM(CASE WHEN CD_SERIE_ENSINO IN (23,24,297,25,26,313,314,319,320)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																
					,MT_IN1 = SUM(CASE WHEN CD_SERIE_ENSINO IN (23,24,313)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																	
					,MT_IN2 = SUM(CASE WHEN CD_SERIE_ENSINO IN (25,26,314)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_IN_UNI = SUM(CASE WHEN CD_SERIE_ENSINO IN (297,319,320)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																	
										
					
					--FUNDAMENTAL
					,MT_FUND = SUM(CASE WHEN CD_SERIE_ENSINO IN (84,250,86,251,88,252,235,253,236,254,232,255,237,256,238,257,239,258)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)	
					,MT_FINI = SUM(CASE WHEN CD_SERIE_ENSINO IN (84,250,86,251,88,252,235,253,236,254)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)										
					,MT_F1 = SUM(CASE WHEN CD_SERIE_ENSINO IN (84,250)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_F2 = SUM(CASE WHEN CD_SERIE_ENSINO IN (86,251)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_F3 = SUM(CASE WHEN CD_SERIE_ENSINO IN (88,252)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_F4 = SUM(CASE WHEN CD_SERIE_ENSINO IN (235,253)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_F5 = SUM(CASE WHEN CD_SERIE_ENSINO IN (236,254)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_FFIN = SUM(CASE WHEN CD_SERIE_ENSINO IN (232,255,237,256,238,257,239,258)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)											
					,MT_F6 = SUM(CASE WHEN CD_SERIE_ENSINO IN (232,255)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_F7 = SUM(CASE WHEN CD_SERIE_ENSINO IN (237,256)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_F8 = SUM(CASE WHEN CD_SERIE_ENSINO IN (238,257)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_F9 = SUM(CASE WHEN CD_SERIE_ENSINO IN (239,258)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					
					
					--MÉDIO
					,MT_MEDI = SUM(CASE WHEN CD_SERIE_ENSINO IN (90,98,101,102,91,99,103,104,92,100,105,106,107,108,303,304,305)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)							
					,MT_M1 = SUM(CASE WHEN CD_SERIE_ENSINO IN (90,98,101,102,303)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																
					,MT_M2 = SUM(CASE WHEN CD_SERIE_ENSINO IN (91,99,103,104,304)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																
					,MT_M3 = SUM(CASE WHEN CD_SERIE_ENSINO IN (92,100,105,106,305)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																
					,MT_M4 = SUM(CASE WHEN CD_SERIE_ENSINO IN (107,108)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
		
					--EJA ANOS INICIAIS
					,MT_EJA		 =SUM(CASE WHEN CD_SERIE_ENSINO IN (274,276,240,288,289,275,277,290,291,278,279,241,292,293,280,281,294,295,246,265,261,269,266,247,262,270,267,248,263,271,268,249,264,272,49,50,212,55,56,213,67,68,210,71,72,211,35,36,39,40,43,44,47,48)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)	 
					,MT_EJAI	 =SUM(CASE WHEN CD_SERIE_ENSINO IN (274,276,240,288,289,275,277,290,291,278,279,241,292,293,280,281,294,295,49,50,212,55,56,213,35,36,39,40)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																									 
					,MT_EJAII	 =SUM(CASE WHEN CD_SERIE_ENSINO IN (246,265,261,269,266,247,262,270,267,248,263,271,268,249,264,272,67,68,210,71,72,211,43,44,47,48)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																											 
				
					,MT_EJAALF_I =SUM(CASE WHEN CD_SERIE_ENSINO IN (274,276,240,288,289)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																											 
					,MT_EJAALF_II =SUM(CASE WHEN CD_SERIE_ENSINO IN (275,277,290,291)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																												 
					,MT_EJABAS_I =SUM(CASE WHEN CD_SERIE_ENSINO IN (278,279,241,292,293)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																											 
					,MT_EJABAS_II =SUM(CASE WHEN CD_SERIE_ENSINO IN (280,281,294,295)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																												 
					
					--EJA ANOS FINAIS
					,MT_EJACOMP_I =SUM(CASE WHEN CD_SERIE_ENSINO IN (246,265,261,269)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																													 
					,MT_EJACOMP_II =SUM(CASE WHEN CD_SERIE_ENSINO IN (266,247,262,270)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																													 
					,MT_EJAFIN_I =SUM(CASE WHEN CD_SERIE_ENSINO IN (267,248,263,271)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																														 
					,MT_EJAFIN_II =SUM(CASE WHEN CD_SERIE_ENSINO IN (268,249,264,272)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																													 
					
					--EJA MODULAR -- ANUAL - ALUNO ENTRA E SAI A QUALQUER MOMENTO
					,MT_EJAMODULAR_I =SUM(CASE WHEN CD_SERIE_ENSINO IN (49,50,212)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)		
					,MT_EJAMODULAR_II =SUM(CASE WHEN CD_SERIE_ENSINO IN (55,56,213)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)		
					,MT_EJAMODULAR_III=SUM(CASE WHEN CD_SERIE_ENSINO IN (67,68,210)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)		
					,MT_EJAMODULAR_IV=SUM(CASE WHEN CD_SERIE_ENSINO IN (71,72,211)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)		
					
					--EJA MÓDULO -- ANUAL - ALUNO ENTRA SOMENTE NO INICIO DA TURMA
					,MT_CIEJAMODULO_I =SUM(CASE WHEN CD_SERIE_ENSINO IN (35,36)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)			
					,MT_CIEJAMODULO_II =SUM(CASE WHEN CD_SERIE_ENSINO IN (39,40)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)			
					,MT_CIEJAMODULO_III =SUM(CASE WHEN CD_SERIE_ENSINO IN (43,44)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)		
					,MT_CIEJAMODULO_IV =SUM(CASE WHEN CD_SERIE_ENSINO IN (47,48)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)			
					
					--ED. PROFISSIONAL
					,MT_PROF =SUM(CASE WHEN(CD_ETAPA_ENSINO IN (14)  OR TIPO_PROG IN ('ED. PROF. ESCOLA MUSICA')) AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)
					
					--ED. PROFISSIONAL BASICA
					,MT_PROF_BASICA =SUM(CASE WHEN  TIPO_PROG IN ('ED. PROF. BASICA - CMCT')  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE   THEN AL_AT ELSE 0 END)
					
					--ATENDIMENTO EDUCACIONAL PERSONALIZADO
					,[MT_AEE_CONVENIO] =SUM(CASE WHEN TIPO_PROG IN ('CAEE - CONVENIOS ESPECIAIS')  /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  THEN AL_AT ELSE 0 END)
					
					--MOVA
					,MT_MOVA =SUM(CASE WHEN TIPO_PROG IN ('MOVA')  /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  THEN AL_AT ELSE 0 END)
					
					--SRM ANTIGO SAAI
					,MT_SRM =SUM(CASE WHEN TIPO_PROG IN ('SALA DE RECURSO MULTIFUNCIONAL')  /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  THEN AL_AT ELSE 0 END)
					
					--RECUPERACAO PARALELA
					,MT_REC_PARAL =SUM(CASE WHEN TIPO_PROG IN ('RECUPERACAO PARALELA') /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  THEN AL_AT ELSE 0 END)

					--SELECT * FROM ##TIPO_PROGRAMA
					,MT_PAP =SUM(CASE WHEN TIPO_PROG IN ('PAP RECUP.DE APRENDIZAGENS') /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  THEN AL_AT ELSE 0 END)
					
					--ATIVIDADE COMPLEMENTAR
					,MT_ATIV_COMP =SUM(CASE WHEN TIPO_PROG IN ('ATIVIDADE COMPLEMENTAR')  /*AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE*/  THEN AL_AT ELSE 0 END)
				
				/*================================================================================================
				--CLASSES
				================================================================================================*/
					
					,CL_EI = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (1,3,4,6,11,27,28,29,23,24,297,25,26,319,320,321,322,307,308,309,311,313,314)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					,CL_CRECHE = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (1,3,4,6,11,27,28,29,307,308,309,311,321,322)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_B1 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (1,3,307)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_B2 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (4,6,308)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--CRECHE/MINIGRUPOS
					,CL_MG1 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (11,27,309)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_MG2 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (28,29,311)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_MG_UNI = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (321,322)    AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--INFANTIL/PRE ESCOLA
					,CL_PRE = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (23,24,297,25,26,313,314,319,320) AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_IN1 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (23,24,313) AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_IN2 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (25,26,314) AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_IN_UNI = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (297,319,320)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					
					--FUNDAMENTAL
					,CL_FUND = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (84,250,86,251,88,252,235,253,236,254,232,255,237,256,238,257,239,258)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_FINI = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (84,250,86,251,88,252,235,253,236,254)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F1 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (84,250)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F2 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (86,251)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F3 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (88,252)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F4 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (235,253)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F5 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (236,254)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_FFIN = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (232,255,237,256,238,257,239,258)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F6 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (232,255)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F7 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (237,256)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F8 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (238,257)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F9 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (239,258)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					
					--MÉDIO
					,CL_MEDI = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (90,98,101,102,91,99,103,104,92,100,105,106,107,108,303,304,305)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_M1 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (90,98,101,102,303)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_M2 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (91,99,103,104,304)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_M3 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (92,100,105,106,305)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_M4 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (107,108)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					
					--EJA ANOS INICIAIS
					,CL_EJA		 =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (274,276,240,288,289,275,277,290,291,278,279,241,292,293,280,281,294,295,246,265,261,269,266,247,262,270,267,248,263,271,268,249,264,272,49,50,212,55,56,213,67,68,210,71,72,211,35,36,39,40,43,44,47,48)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAI	 =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (274,276,240,288,289,275,277,290,291,278,279,241,292,293,280,281,294,295,49,50,212,55,56,213,35,36,39,40)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAII	 =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (246,265,261,269,266,247,262,270,267,248,263,271,268,249,264,272,67,68,210,71,72,211,43,44,47,48)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					,CL_EJAALF_I =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (274,276,240,288,289)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAALF_II =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (275,277,290,291)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJABAS_I =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (278,279,241,292,293)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJABAS_II =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (280,281,294,295)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--EJA ANOS FINAIS
					,CL_EJACOMP_I =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (246,265,261,269)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJACOMP_II =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (266,247,262,270)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAFIN_I =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (267,248,263,271)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAFIN_II =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (268,249,264,272)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--EJA MODULAR -- ANUAL - ALUNO ENTRA E SAI A QUALQUER MOMENTO
					,CL_EJAMODULAR_I =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (49,50,212)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAMODULAR_II =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (55,56,213)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAMODULAR_III=COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (67,68,210)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAMODULAR_IV=COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (71,72,211)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--EJA MÓDULO -- ANUAL - ALUNO ENTRA SOMENTE NO INICIO DA TURMA
					,CL_CIEJAMODULO_I =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (35,36)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_CIEJAMODULO_II =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (39,40)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_CIEJAMODULO_III =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (43,44)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_CIEJAMODULO_IV =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (47,48)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--ED. PROFISSIONAL
					,CL_PROF =COUNT(DISTINCT(CASE WHEN(CD_ETAPA_ENSINO IN (14)  OR TIPO_PROG IN ('ED. PROF. ESCOLA MUSICA')) AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--ED. PROFISSIONAL BASICA
					,CL_PROF_BASICA =COUNT(DISTINCT(CASE WHEN  TIPO_PROG IN ('ED. PROF. BASICA - CMCT')  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--ATENDIMENTO EDUCACIONAL PERSONALIZADO
					,[CL_AEE_CONVENIO] =COUNT(DISTINCT(CASE WHEN TIPO_PROG IN ('CAEE - CONVENIOS ESPECIAIS')  /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--MOVA
					,CL_MOVA =COUNT(DISTINCT(CASE WHEN TIPO_PROG IN ('MOVA')  /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--SRM ANTIGO SAAI
					,CL_SRM =COUNT(DISTINCT(CASE WHEN TIPO_PROG IN ('SALA DE RECURSO MULTIFUNCIONAL')  /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--RECUPERACAO PARALELA
					,CL_REC_PARAL =COUNT(DISTINCT(CASE WHEN TIPO_PROG IN ('RECUPERACAO PARALELA') /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--PAP
					,CL_PAP = COUNT(DISTINCT(CASE WHEN TIPO_PROG IN ('PAP RECUP.DE APRENDIZAGENS') /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))

					--ATIVIDADE COMPLEMENTAR
					,CL_ATIV_COMP =COUNT(DISTINCT(CASE WHEN TIPO_PROG IN ('ATIVIDADE COMPLEMENTAR')  /*AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE*/  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					,CONVERT(NVARCHAR,A.CRDATE,103) AS CRDATE
				INTO D_MISME_DRE_DISTR_SETOR	
FROM SME_ESCOLA_DIARIO A 
LEFT JOIN SME_CLASSES_DIARIO B ON A.CD_ESCOLA = B.CD_ESCOLA
LEFT JOIN ##TIPO_PROGRAMA C ON B.CD_TIPO_PROGRAMA = C.CD_TIPO_PROGRAMA
WHERE
CD_SIT = 1 
AND TP_ESCOLA NOT IN (15,29) 
AND isnull(B.CD_MODALIDADE_ENSINO,0) <> 2
GROUP BY 
 

NOMEDEP
,REDE
,DRE
,DISTR
,SETOR
,A.CRDATE
ORDER BY 1,2,3

/*--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----MISME TOTAL POR DIR_INDIR
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/


DROP TABLE D_MISME_DIR_INDIR_TOTAL

SELECT 
	NOMEDEP
	,REDE
	,DRE
	
/*================================================================================================
--ALUNOS
================================================================================================*/
--CRECHE/BERÇARIO
						,MT_EI = SUM(CASE WHEN CD_SERIE_ENSINO IN (1,3,4,6,11,27,28,29,23,24,297,25,26,319,320,321,322,307,308,309,311,313,314)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END) 											
																																																																																							
					,MT_CRECHE = SUM(CASE WHEN CD_SERIE_ENSINO IN (1,3,4,6,11,27,28,29,307,308,309,311,321,322)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)														
					,MT_B1 = SUM(CASE WHEN CD_SERIE_ENSINO IN (1,3,307)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																			
					,MT_B2 = SUM(CASE WHEN CD_SERIE_ENSINO IN (4,6,308)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																			
																																																																												
					--CRECHE/MINIGRUPOS																																																																														
					,MT_MG1 = SUM(CASE WHEN CD_SERIE_ENSINO IN (11,27,309)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_MG2 = SUM(CASE WHEN CD_SERIE_ENSINO IN (28,29,311)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_MG_UNI = SUM(CASE WHEN CD_SERIE_ENSINO IN (321,322)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																	
																																																																																							
					--INFANTIL/PRE ESCOLA																																																																													
					,MT_PRE = SUM(CASE WHEN CD_SERIE_ENSINO IN (23,24,297,25,26,313,314,319,320)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																
					,MT_IN1 = SUM(CASE WHEN CD_SERIE_ENSINO IN (23,24,313)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																	
					,MT_IN2 = SUM(CASE WHEN CD_SERIE_ENSINO IN (25,26,314)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_IN_UNI = SUM(CASE WHEN CD_SERIE_ENSINO IN (297,319,320)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																	
										
					--FUNDAMENTAL
					,MT_FUND = SUM(CASE WHEN CD_SERIE_ENSINO IN (84,250,86,251,88,252,235,253,236,254,232,255,237,256,238,257,239,258)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)	
					,MT_FINI = SUM(CASE WHEN CD_SERIE_ENSINO IN (84,250,86,251,88,252,235,253,236,254)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)										
					,MT_F1 = SUM(CASE WHEN CD_SERIE_ENSINO IN (84,250)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_F2 = SUM(CASE WHEN CD_SERIE_ENSINO IN (86,251)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_F3 = SUM(CASE WHEN CD_SERIE_ENSINO IN (88,252)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_F4 = SUM(CASE WHEN CD_SERIE_ENSINO IN (235,253)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_F5 = SUM(CASE WHEN CD_SERIE_ENSINO IN (236,254)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_FFIN = SUM(CASE WHEN CD_SERIE_ENSINO IN (232,255,237,256,238,257,239,258)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)											
					,MT_F6 = SUM(CASE WHEN CD_SERIE_ENSINO IN (232,255)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_F7 = SUM(CASE WHEN CD_SERIE_ENSINO IN (237,256)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_F8 = SUM(CASE WHEN CD_SERIE_ENSINO IN (238,257)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					,MT_F9 = SUM(CASE WHEN CD_SERIE_ENSINO IN (239,258)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
					
					
					--MÉDIO
					,MT_MEDI = SUM(CASE WHEN CD_SERIE_ENSINO IN (90,98,101,102,91,99,103,104,92,100,105,106,107,108,303,304,305)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)							
					,MT_M1 = SUM(CASE WHEN CD_SERIE_ENSINO IN (90,98,101,102,303)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																
					,MT_M2 = SUM(CASE WHEN CD_SERIE_ENSINO IN (91,99,103,104,304)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																
					,MT_M3 = SUM(CASE WHEN CD_SERIE_ENSINO IN (92,100,105,106,305)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																
					,MT_M4 = SUM(CASE WHEN CD_SERIE_ENSINO IN (107,108)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																		
		
					--EJA ANOS INICIAIS
					,MT_EJA		 =SUM(CASE WHEN CD_SERIE_ENSINO IN (274,276,240,288,289,275,277,290,291,278,279,241,292,293,280,281,294,295,246,265,261,269,266,247,262,270,267,248,263,271,268,249,264,272,49,50,212,55,56,213,67,68,210,71,72,211,35,36,39,40,43,44,47,48)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)	 
					,MT_EJAI	 =SUM(CASE WHEN CD_SERIE_ENSINO IN (274,276,240,288,289,275,277,290,291,278,279,241,292,293,280,281,294,295,49,50,212,55,56,213,35,36,39,40)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																									 
					,MT_EJAII	 =SUM(CASE WHEN CD_SERIE_ENSINO IN (246,265,261,269,266,247,262,270,267,248,263,271,268,249,264,272,67,68,210,71,72,211,43,44,47,48)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																											 
				
					,MT_EJAALF_I =SUM(CASE WHEN CD_SERIE_ENSINO IN (274,276,240,288,289)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																											 
					,MT_EJAALF_II =SUM(CASE WHEN CD_SERIE_ENSINO IN (275,277,290,291)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																												 
					,MT_EJABAS_I =SUM(CASE WHEN CD_SERIE_ENSINO IN (278,279,241,292,293)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																											 
					,MT_EJABAS_II =SUM(CASE WHEN CD_SERIE_ENSINO IN (280,281,294,295)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																												 
					
					--EJA ANOS FINAIS
					,MT_EJACOMP_I =SUM(CASE WHEN CD_SERIE_ENSINO IN (246,265,261,269)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																													 
					,MT_EJACOMP_II =SUM(CASE WHEN CD_SERIE_ENSINO IN (266,247,262,270)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																													 
					,MT_EJAFIN_I =SUM(CASE WHEN CD_SERIE_ENSINO IN (267,248,263,271)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																														 
					,MT_EJAFIN_II =SUM(CASE WHEN CD_SERIE_ENSINO IN (268,249,264,272)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)																																													 
					
					--EJA MODULAR -- ANUAL - ALUNO ENTRA E SAI A QUALQUER MOMENTO
					,MT_EJAMODULAR_I =SUM(CASE WHEN CD_SERIE_ENSINO IN (49,50,212)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)		
					,MT_EJAMODULAR_II =SUM(CASE WHEN CD_SERIE_ENSINO IN (55,56,213)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)		
					,MT_EJAMODULAR_III=SUM(CASE WHEN CD_SERIE_ENSINO IN (67,68,210)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)		
					,MT_EJAMODULAR_IV=SUM(CASE WHEN CD_SERIE_ENSINO IN (71,72,211)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)		
					
					--EJA MÓDULO -- ANUAL - ALUNO ENTRA SOMENTE NO INICIO DA TURMA
					,MT_CIEJAMODULO_I =SUM(CASE WHEN CD_SERIE_ENSINO IN (35,36)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)			
					,MT_CIEJAMODULO_II =SUM(CASE WHEN CD_SERIE_ENSINO IN (39,40)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)			
					,MT_CIEJAMODULO_III =SUM(CASE WHEN CD_SERIE_ENSINO IN (43,44)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)		
					,MT_CIEJAMODULO_IV =SUM(CASE WHEN CD_SERIE_ENSINO IN (47,48)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)			
					
					--ED. PROFISSIONAL
					,MT_PROF =SUM(CASE WHEN(CD_ETAPA_ENSINO IN (14)  OR TIPO_PROG IN ('ED. PROF. ESCOLA MUSICA')) AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  THEN AL_AT ELSE 0 END)
					
					--ED. PROFISSIONAL BASICA
					,MT_PROF_BASICA =SUM(CASE WHEN  TIPO_PROG IN ('ED. PROF. BASICA - CMCT')  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE   THEN AL_AT ELSE 0 END)
					
					--ATENDIMENTO EDUCACIONAL PERSONALIZADO
					,[MT_AEE_CONVENIO] =SUM(CASE WHEN TIPO_PROG IN ('CAEE - CONVENIOS ESPECIAIS')  /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  THEN AL_AT ELSE 0 END)
					
					--MOVA
					,MT_MOVA =SUM(CASE WHEN TIPO_PROG IN ('MOVA')  /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  THEN AL_AT ELSE 0 END)
					
					--SRM ANTIGO SAAI
					,MT_SRM =SUM(CASE WHEN TIPO_PROG IN ('SALA DE RECURSO MULTIFUNCIONAL')  /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  THEN AL_AT ELSE 0 END)
					
					--RECUPERACAO PARALELA
					,MT_REC_PARAL =SUM(CASE WHEN TIPO_PROG IN ('RECUPERACAO PARALELA') /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  THEN AL_AT ELSE 0 END)

					--SELECT * FROM ##TIPO_PROGRAMA
					,MT_PAP =SUM(CASE WHEN TIPO_PROG IN ('PAP RECUP.DE APRENDIZAGENS') /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  THEN AL_AT ELSE 0 END)
					
					--ATIVIDADE COMPLEMENTAR
					,MT_ATIV_COMP =SUM(CASE WHEN TIPO_PROG IN ('ATIVIDADE COMPLEMENTAR')  /*AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE*/  THEN AL_AT ELSE 0 END)
				
				/*================================================================================================
				--CLASSES
				================================================================================================*/
					
					,CL_EI = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (1,3,4,6,11,27,28,29,23,24,297,25,26,319,320,321,322,307,308,309,311,313,314)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					,CL_CRECHE = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (1,3,4,6,11,27,28,29,307,308,309,311,321,322)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_B1 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (1,3,307)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_B2 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (4,6,308)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--CRECHE/MINIGRUPOS
					,CL_MG1 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (11,27,309)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_MG2 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (28,29,311)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_MG_UNI = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (321,322)    AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--INFANTIL/PRE ESCOLA
					,CL_PRE = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (23,24,297,25,26,313,314,319,320) AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_IN1 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (23,24,313) AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_IN2 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (25,26,314) AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_IN_UNI = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (297,319,320)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					
					--FUNDAMENTAL
					,CL_FUND = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (84,250,86,251,88,252,235,253,236,254,232,255,237,256,238,257,239,258)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_FINI = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (84,250,86,251,88,252,235,253,236,254)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F1 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (84,250)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F2 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (86,251)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F3 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (88,252)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F4 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (235,253)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F5 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (236,254)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_FFIN = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (232,255,237,256,238,257,239,258)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F6 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (232,255)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F7 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (237,256)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F8 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (238,257)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_F9 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (239,258)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					
					--MÉDIO
					,CL_MEDI = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (90,98,101,102,91,99,103,104,92,100,105,106,107,108,303,304,305)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_M1 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (90,98,101,102,303)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_M2 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (91,99,103,104,304)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_M3 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (92,100,105,106,305)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_M4 = COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (107,108)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					
					--EJA ANOS INICIAIS
					,CL_EJA		 =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (274,276,240,288,289,275,277,290,291,278,279,241,292,293,280,281,294,295,246,265,261,269,266,247,262,270,267,248,263,271,268,249,264,272,49,50,212,55,56,213,67,68,210,71,72,211,35,36,39,40,43,44,47,48)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAI	 =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (274,276,240,288,289,275,277,290,291,278,279,241,292,293,280,281,294,295,49,50,212,55,56,213,35,36,39,40)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAII	 =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (246,265,261,269,266,247,262,270,267,248,263,271,268,249,264,272,67,68,210,71,72,211,43,44,47,48)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					,CL_EJAALF_I =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (274,276,240,288,289)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAALF_II =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (275,277,290,291)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJABAS_I =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (278,279,241,292,293)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJABAS_II =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (280,281,294,295)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--EJA ANOS FINAIS
					,CL_EJACOMP_I =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (246,265,261,269)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJACOMP_II =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (266,247,262,270)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAFIN_I =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (267,248,263,271)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAFIN_II =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (268,249,264,272)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--EJA MODULAR -- ANUAL - ALUNO ENTRA E SAI A QUALQUER MOMENTO
					,CL_EJAMODULAR_I =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (49,50,212)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAMODULAR_II =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (55,56,213)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAMODULAR_III=COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (67,68,210)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_EJAMODULAR_IV=COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (71,72,211)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--EJA MÓDULO -- ANUAL - ALUNO ENTRA SOMENTE NO INICIO DA TURMA
					,CL_CIEJAMODULO_I =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (35,36)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_CIEJAMODULO_II =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (39,40)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_CIEJAMODULO_III =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (43,44)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					,CL_CIEJAMODULO_IV =COUNT(DISTINCT(CASE WHEN CD_SERIE_ENSINO IN (47,48)  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--ED. PROFISSIONAL
					,CL_PROF =COUNT(DISTINCT(CASE WHEN(CD_ETAPA_ENSINO IN (14)  OR TIPO_PROG IN ('ED. PROF. ESCOLA MUSICA')) AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--ED. PROFISSIONAL BASICA
					,CL_PROF_BASICA =COUNT(DISTINCT(CASE WHEN  TIPO_PROG IN ('ED. PROF. BASICA - CMCT')  AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--ATENDIMENTO EDUCACIONAL PERSONALIZADO
					,[CL_AEE_CONVENIO] =COUNT(DISTINCT(CASE WHEN TIPO_PROG IN ('CAEE - CONVENIOS ESPECIAIS')  /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--MOVA
					,CL_MOVA =COUNT(DISTINCT(CASE WHEN TIPO_PROG IN ('MOVA')  /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--SRM ANTIGO SAAI
					,CL_SRM =COUNT(DISTINCT(CASE WHEN TIPO_PROG IN ('SALA DE RECURSO MULTIFUNCIONAL')  /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--RECUPERACAO PARALELA
					,CL_REC_PARAL =COUNT(DISTINCT(CASE WHEN TIPO_PROG IN ('RECUPERACAO PARALELA') /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					--PAP
					,CL_PAP = COUNT(DISTINCT(CASE WHEN TIPO_PROG IN ('PAP RECUP.DE APRENDIZAGENS') /* AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE */  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))

					--ATIVIDADE COMPLEMENTAR
					,CL_ATIV_COMP =COUNT(DISTINCT(CASE WHEN TIPO_PROG IN ('ATIVIDADE COMPLEMENTAR')  /*AND CASE WHEN CD_TIPO_PERIODICIDADE  IN (1,2) THEN 0 WHEN CD_TIPO_PERIODICIDADE  IN (3) THEN 1 WHEN CD_TIPO_PERIODICIDADE  IN (4) THEN 2 ELSE CD_TIPO_PERIODICIDADE END <> @DURCLASSE*/  AND ST_TURMA_ESCOLA NOT IN ('E','C') THEN CD_TURMA_ESCOLA ELSE NULL END))
					
					,CONVERT(NVARCHAR,A.CRDATE,103) AS CRDATE
				INTO D_MISME_DIR_INDIR_TOTAL	

FROM SME_ESCOLA_DIARIO A 
LEFT JOIN SME_CLASSES_DIARIO B ON A.CD_ESCOLA = B.CD_ESCOLA
LEFT JOIN ##TIPO_PROGRAMA C ON B.CD_TIPO_PROGRAMA = C.CD_TIPO_PROGRAMA
WHERE
CD_SIT = 1 
AND TP_ESCOLA NOT IN (15,29) 
AND isnull(B.CD_MODALIDADE_ENSINO,0) <> 2
GROUP BY 
 NOMEDEP
 ,REDE
,DRE
,A.CRDATE
ORDER BY 1


