USE [Db_Local]
GO


drop table ##ENCAMINHADOS
SELECT	DRE,
		Distrito,
		SETOR,
		CD_ESCOLA,
		TP_ORIGEM,
		CD_ALUNO,
		CD_MODALIDADE_ENSINO,
		CD_ETAPA_ENSINO, 
		SUB_SOLICITACAO.CD_SOLICITACAO_MATRICULA,
		SUB_SOLICITACAO.[DT CADASTRO/REATIVAÇÃO],
		SUB_SOLICITACAO.[DT CARGA],
		SUB_SOLICITACAO.AGUARDANDO,
		CD_NIVEL_PRIORIDADE,
		DT_NASCIMENTO_ALUNO,
		SUB_SOLICITACAO.CD_SERIE_ENSINO,
		SUB_SOLICITACAO.CD_CICLO_ENSINO,
		SUB_SOLICITACAO.SG_SERIE_ENSINO,
		SMP.CD_SOLICITACAO_MATRICULA_PREFERENCIAL,
		SMP.CD_UNIDADE_EDUCACAO, 
		SMP.DC_OBSERVACAO_STATUS,
		SMP.DT_INICIO,
		SMP.TP_PREFERENCIA,
		SUB_SOLICITACAO.CRDATE
INTO ##ENCAMINHADOS
		FROM (	SELECT	G.NM_UNIDADE_EDUCACAO,
						RIGHT(G.NM_UNIDADE_EDUCACAO, (LEN(G.NM_UNIDADE_EDUCACAO)+1) - REVERSE(CHARINDEX('EDUCACAO', G.NM_UNIDADE_EDUCACAO))) AS DRE,
						LEFT(I.NM_MICRO_REGIAO,CHARINDEX('SETOR', I.NM_MICRO_REGIAO)-1) AS Distrito,
						RIGHT(I.NM_MICRO_REGIAO,2) SETOR,
						A.CD_UNIDADE_EDUCACAO AS CD_ESCOLA,
						A.TP_ORIGEM,
						B.CD_ALUNO, 
						A.CD_MODALIDADE_ENSINO, 
						A.CD_ETAPA_ENSINO, 
						A.CD_SERIE_ENSINO,
						A.CD_CICLO_ENSINO,
						T2.sg_serie_ensino,
						A.CD_SOLICITACAO_MATRICULA,
						DT_STATUS_SOLICITACAO,
						CONVERT(DATE,DT_STATUS_SOLICITACAO,109) AS [DT CADASTRO/REATIVAÇÃO],
						CONVERT(DATE,DT_ATLZ_TAB,109) AS [DT CARGA],
						DATEDIFF(DAY,DT_STATUS_SOLICITACAO,A.CRDATE) AS AGUARDANDO, --ver pra colocar o dia do arquivo d-1 pq esta calculando um dia mais devido a data do backup --PEGA A DATA DO ARQUIVO DO CONGELAMENTO PARA O COMPARATIVO DE DATAS
						TSP.CD_NIVEL_PRIORIDADE,
						DT_NASCIMENTO_ALUNO,
						DT_ENDERECO_BASE,
						A.CRDATE
						FROM		D_SOLICITACAO_MATRICULA A 
						LEFT JOIN	D_ALUNO B ON A.CD_ALUNO = B.CD_ALUNO 
						LEFT JOIN	D_ENDERECO_ALUNO C ON B.CD_ALUNO = C.CD_ALUNO 
						LEFT JOIN	D_ENDERECO_ALUNO_TIPO_ENDERECO D ON C.CD_ENDERECO_ALUNO = D.CD_ENDERECO_ALUNO 
						LEFT JOIN	D_ENDERECO E ON C.CI_ENDERECO = E.CI_ENDERECO
						LEFT JOIN	D_MICRO_REGIAO I ON A.CD_MICRO_REGIAO = I.CD_MICRO_REGIAO
						LEFT JOIN	D_UNIDADE_EDUCACAO F	ON A.CD_UNIDADE_EDUCACAO = F.CD_UNIDADE_EDUCACAO
						LEFT JOIN	D_UNIDADE_EDUCACAO G	ON F.CD_UNIDADE_ADMINISTRATIVA_REFERENCIA = G.CD_UNIDADE_EDUCACAO
						LEFT OUTER JOIN	(--TABELA DE SOLICITACAO DE MATRICULA PRIORIDADE AGRUPANDO TODOS OS REGISTROS DE SOLICITACAO DE MATRICULA COM A PRIORIDADE MAIS URGENTE
										 SELECT	CD_SOLICITACAO_MATRICULA, 
										 		MIN(CD_NIVEL_PRIORIDADE) AS CD_NIVEL_PRIORIDADE
										 		FROM D_SOLICITACAO_MATRICULA_PRIORIDADE AS A --RELACIONANDO A TABELA DE SOLICTACAO_MATRICULA_PRIORIDADE COM A TIPO_PRIORIDADE PARA PODER PEGAR O NÍVEL DA PRIORIDADE MAIS URGENTE
										 INNER JOIN	 D_TIPO_PRIORIDADE_LISTA AS B ON CD_PRIORIDADE_LISTA = CD_TIPO_PRIORIDADE
										 WHERE	DT_FIM IS NULL --CONSIDERANDO SOMENTE OS REGISTROS DE PRIORIDADES ATIVOS, POIS HÁ CASOS QUE HOUVERAM MUDANÇA NO NÍVEL DE PRIORIDADE DAQUELA CRIANÇA
										 GROUP BY	CD_SOLICITACAO_MATRICULA --AGRUPANDO PELO CD_SOLICITACAO_MATRICULA, POIS HÁ ALGUNS CASOS ONDE HÁ MAIS DE UM NÍVEL DE PRIORIDA ATIVO, CONSIDEROU-SE O REGISTRO COM O NÍVEL DE PRIORIDADE MAIS URGENTE
										 ) AS TSP ON A.CD_SOLICITACAO_MATRICULA = TSP.CD_SOLICITACAO_MATRICULA
										INNER JOIN	D_SERIE_ENSINO AS T2 ON A.CD_SERIE_ENSINO = T2.CD_SERIE_ENSINO
										WHERE
										A.an_letivo=year(getdate())
										AND A.CD_ETAPA_ENSINO IN (1,2,3,5,6,7,8,9,10,11,13,14,17)
										/*
										cd_etapa_ensino	sg_etapa
											1			ED INF
											2			EJA CIEJA
											3			EJA
											4			ENS FUND8A(NÃO SE USA MAIS)
											5			ENS FUND9A
											6			ENS MEDIO
											7			EJA MEDIO
											8			MEDIO INT
											9			NORMAL
											16			PROJOVEM
											10			ED INF ESP
											11			EJA ESP
											12			FUND ESP 8
											13			FUND ESP 9
											17			ESP MEDIO
											14			TEC MEDIO
										*/
										AND ST_SOLICITACAO = 'E' 
										AND TP_ORIGEM IN ('C','I','A','P')
										/*tp_origem	dc_tp_origem
											C		Cadastro Infantil
											A		Cadastro EJA
											T		Transferencia Infantil
											P		PRODESP
											I		Continuidade Infantil
											R		Transferencia EJA
										*/
										AND D.CI_TIPO_ENDERECO = 1 
										AND D.DT_FIM IS NULL 
										AND C.DT_FIM IS NULL
										AND (E.CD_MUNICIPIO=3550308 OR E.CD_CEP BETWEEN 01000000 AND 05999999 OR E.CD_CEP BETWEEN 08000000 AND 08499999)
							) AS SUB_SOLICITACAO
		left JOIN (	SELECT	DISTINCT --EM TESE NÃO DEVERIA HAVER DUPLICADAS, MAS POR SEGURANÇA
											CD_FAIXA,
											CONVERT(DATETIME,CONVERT(VARCHAR(4),DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA) + CONVERT(VARCHAR(2), MM_INICIO_FAIXA) + CONVERT(VARCHAR(2), DD_INICIO_FAIXA)) AS DT_INICIO_FAIXA,
											CONVERT(DATETIME,CONVERT(VARCHAR(4),DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_FIM_FAIXA) + CONVERT(VARCHAR(2), MM_FIM_FAIXA) + CONVERT(VARCHAR(2), DD_FIM_FAIXA)) AS DT_FIM_FAIXA,
											CASE 
											 WHEN (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ - (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA)) = 1 THEN '0 E 1 ANO'
											 ELSE CONVERT(VARCHAR(2),(DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ - (DATEPART(YYYY, GETDATE()) /*@ANO_REFERENCIA_PARAMETRO_MATRICULA*/ + AN_INCREMENTO_INICIO_FAIXA))) + ' ANOS' 
											 END AS IDADE,
											T1.CD_SERIE_ENSINO, 
											T2.DC_SERIE_ENSINO,
											T2.CD_CICLO_ENSINO,
											T2.SG_SERIE_ENSINO
						FROM		D_FAIXA_SERIE AS T1
						INNER JOIN	D_SERIE_ENSINO AS T2 ON T1.CD_SERIE_ENSINO = T2.CD_SERIE_ENSINO
						WHERE	T1.DT_INICIO <= GETDATE()
								AND (T1.DT_FIM IS NULL OR T1.DT_FIM >= CONVERT(DATE,GETDATE()))
								AND TP_FAIXA=1
					) AS SUB_FAIXA_SERIE ON SUB_SOLICITACAO.DT_NASCIMENTO_ALUNO >= SUB_FAIXA_SERIE.DT_INICIO_FAIXA AND SUB_SOLICITACAO.DT_NASCIMENTO_ALUNO <= SUB_FAIXA_SERIE.DT_FIM_FAIXA
		--WHERE CD_CICLO_ENSINO = 2
		--LEFT JOIN D_SOLICITACAO_MATRICULA_PREFERENCIAL SMP ON SUB_SOLICITACAO.CD_SOLICITACAO_MATRICULA = SMP.CD_SOLICITACAO_MATRICULA AND DT_FIM IS NULL AND convert(date,SUB_SOLICITACAO.DT_STATUS_SOLICITACAO) BETWEEN CONVERT(DATE,SMP.DT_INICIO) AND CONVERT(DATE,ISNULL(SMP.DT_FIM,'2099-12-18 00:00:00.000'))
		--DEU DIFERENÇA POR CONTA DA UTILIZAÇÃO DO ENDEREÇO BASE...FOI TROCADO TB A FORMA DO ISNULL PARA O CAMPO DATA SETADO
		LEFT JOIN Db_Local.DBO.D_SOLICITACAO_MATRICULA_PREFERENCIAL SMP ON SUB_SOLICITACAO.CD_SOLICITACAO_MATRICULA = SMP.CD_SOLICITACAO_MATRICULA AND SMP.DT_FIM IS NULL AND (convert(date,SUB_SOLICITACAO.DT_STATUS_SOLICITACAO) BETWEEN CONVERT(DATE,SMP.DT_INICIO) AND CONVERT(DATE,ISNULL(SMP.DT_FIM,CONVERT(DATE,'2099-12-18 00:00:00.000'))) or  convert(date,SUB_SOLICITACAO.DT_ENDERECO_BASE) BETWEEN CONVERT(DATE,SMP.DT_INICIO) AND CONVERT(DATE,ISNULL(SMP.DT_FIM,CONVERT(DATE,'2099-12-18 00:00:00.000')))
																																											or CONVERT(DATE,SMP.DT_INICIO) >= convert(date,SUB_SOLICITACAO.DT_STATUS_SOLICITACAO) AND SMP.DT_FIM IS NULL)
			

GO

--SELECT * FROM ##ENCAMINHADOS
