/*
Quantidade de salas de aula (FÍSICAS e REGULARES (POR TURNO)) por Unidade Educacional, 
por tipo (EMEI, CEU EMEI, CEMEI, CEU CEMEI, EMEF, CEU EMEF, EMEBS, CIEJAS, EMEFMS e CECIS) e por DRE
*/
DROP TABLE ##QT_SALAS_AULA_QT_TURMAS_POR_TURNO
SELECT DISTINCT 
B.DRE,
A.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
Count (DISTINCT CASE WHEN DC_TIPO_AMBIENTE IN 
											('SALA DE AULA PROPRIA',         
											 'SALA DE AULA ADAPTADA',        
											 'SALA DE ED. INFANTIL PROPRIA', 
											 'SALA DE ED. INFANTIL ADAPTADA',
											 'SALA DE ED. ESPECIAL PROPRIA', 
											 'BERCARIO') AND CD_TIPO_PROGRAMA IS NULL AND DT_FIM IS NULL
																	   THEN NR_SALA ELSE NULL END) AS QT_SALAS,
COUNT (DISTINCT CASE WHEN CD_TIPO_TURNO=1 AND CD_TIPO_PROGRAMA IS NULL AND DT_FIM IS NULL THEN CD_TURMA_ESCOLA ELSE NULL END) AS MANHÃ,
COUNT (DISTINCT CASE WHEN CD_TIPO_TURNO=2 AND CD_TIPO_PROGRAMA IS NULL AND DT_FIM IS NULL THEN CD_TURMA_ESCOLA ELSE NULL END) AS INTERMEDIÁRIO,
COUNT (DISTINCT CASE WHEN CD_TIPO_TURNO=3 AND CD_TIPO_PROGRAMA IS NULL AND DT_FIM IS NULL THEN CD_TURMA_ESCOLA ELSE NULL END) AS TARDE,
COUNT (DISTINCT CASE WHEN CD_TIPO_TURNO=4 AND CD_TIPO_PROGRAMA IS NULL AND DT_FIM IS NULL THEN CD_TURMA_ESCOLA ELSE NULL END) AS VESPERTINO,
COUNT (DISTINCT CASE WHEN CD_TIPO_TURNO=5 AND CD_TIPO_PROGRAMA IS NULL AND DT_FIM IS NULL THEN CD_TURMA_ESCOLA ELSE NULL END) AS NOITE,
COUNT (DISTINCT CASE WHEN CD_TIPO_TURNO=6 AND CD_TIPO_PROGRAMA IS NULL AND DT_FIM IS NULL THEN CD_TURMA_ESCOLA ELSE NULL END) AS INTEGRAL,
CONVERT(VARCHAR, A.CRDATE, 103) AS DT_BASE
INTO ##QT_SALAS_AULA_QT_TURMAS_POR_TURNO
FROM SME_CLASSES_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
WHERE B.CD_SIT=1 AND B.TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,20.28,30,31)
GROUP BY
B.DRE,
A.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
A.CRDATE
ORDER BY 1,2
--SELECT * FROM ##QT_SALAS_AULA_QT_TURMAS_POR_TURNO
------------------------------------------------------------------------------------------------------------
DROP TABLE ##QT_CEI_DIR
SELECT DISTINCT
DRE,
COUNT (DISTINCT CASE WHEN TP_ESCOLA=10 THEN CD_ESCOLA ELSE NULL END) AS CEI_DIR,
COUNT (DISTINCT CASE WHEN TP_ESCOLA=18 THEN CD_ESCOLA ELSE NULL END) AS CEU_CEI,
COUNT (DISTINCT CASE WHEN TP_ESCOLA=31 THEN CD_ESCOLA ELSE NULL END) AS CEU_CEMEI,
COUNT (DISTINCT CASE WHEN TP_ESCOLA IN (10,18,31)THEN CD_ESCOLA ELSE NULL END) AS TOTAL
INTO ##QT_CEI_DIR
FROM SME_ESCOLA_DIARIO
WHERE TP_ESCOLA IN (10,18,31) AND CD_SIT=1
GROUP BY DRE WITH ROLLUP
--SELECT * FROM ##QT_CEI_DIR

