
--ESTUDO ESCOLAS PRIORITÁRIAS


DROP TABLE ##ESCOLAS_PRIORITARIAS
SELECT 
	A.*,
	MT_FUND,
	MT_F1,
	MT_F2,
	MT_F3,
	MT_F4,
	MT_F5,
	MT_F6,
	MT_F7,
	MT_F8,
	MT_F9 
	INTO ##ESCOLAS_PRIORITARIAS
	FROM
	D_MISME_ESCOLA_TOTAL B
	JOIN (SELECT '1' AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%ULYSSES DA SYLVEIRA GUIMARAES%'
    UNION SELECT '2' AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%JUSCELINO KUBITSCHEK DE OLIVEIRA%'
    UNION SELECT '3' AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%GERALDO SESSO JUNIOR%'
    UNION SELECT '4' AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%AMORIM LIMA%'
    UNION SELECT '5' AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%8 DE MAIO%'
    UNION SELECT '6' AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%ANTONIO RODRIGUES DE CAMPOS%'
    UNION SELECT '7' AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%RENATO ANTONIO CHECCHIA%'
    UNION SELECT '8' AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%MAILSON DELANE%'
    UNION SELECT '9' AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%PLINIO MARCOS%'
    UNION SELECT '10'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%ARTUR NEIVA%'
    UNION SELECT '11'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%CECILIA MORAES DE VASCONCELOS%'
    UNION SELECT '12'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%IVETE VARGAS%'
    UNION SELECT '13'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%MAURICIO GOULART%'
    UNION SELECT '14'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%JOSE KAUFFMANN%'
    UNION SELECT '15'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%CASTRO ALVES%'
    UNION SELECT '16'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%ERICO VERISSIMO%'
    UNION SELECT '17'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%LEONEL FRANCA%'
    UNION SELECT '18'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%SATURNINO PEREIRA%'
    UNION SELECT '19'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%PAULO CARNEIRO THOMAZ ALVES%'
    UNION SELECT '20'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%MILTOM CAMPOS%'
    UNION SELECT '21'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%ANTONIO SANT ANA GALVAO%'
    UNION SELECT '22'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%PARQUE SAO CARLOS%'
    UNION SELECT '23'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%FRANCISCO DA SILVEIRA BUENO%'
    UNION SELECT '24'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%HUMBERTO DANTAS%'
    UNION SELECT '25'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%OSVALDO QUIRINO SIMOES%'
    UNION SELECT '26'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%ALVARO SILVA BRAGA%'
    UNION SELECT '27'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%FLAVIO AUGUSTO ROSA%'
    UNION SELECT '28'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%ALEXANDRE VANNUCHI LEME%'
    UNION SELECT '29'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%ARY PARREIRAS%'
    UNION SELECT '30'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%BUTANTA%'
    UNION SELECT '31'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%ANTONIO SAMPAIO%'
    UNION SELECT '32'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%JULIO DE GRAMMONT%'
    UNION SELECT '33'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%LUIZ DAVID SOBRINHO%'
    UNION SELECT '34'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%JOAO AMOS COMENIUS%'
    UNION SELECT '35'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%JOSE DE ALCANTARA MACHADO FILHO%'
    UNION SELECT '36'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%CLEMENTE PASTORE%'
    UNION SELECT '37'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%ARMANDO CRIDEY RIGHETTI%'
    UNION SELECT '38'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%RAUL POMPEIA%'
    UNION SELECT '39'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%VLADIMIR HERZOG%'
    UNION SELECT '40'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%ERNANI SILVA BRUNO%'
    UNION SELECT '41'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%GILBERTO DUPAS%'
    UNION SELECT '42'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%ALCIDES GONCALVES ETCHEGOYEN%'
    UNION SELECT '43'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%BRASILIO MACHADO NETO%'
    UNION SELECT '44'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%PEDRO DE FRONTIN%'
    UNION SELECT '45'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%PEDRO NAVA%'
    UNION SELECT '46'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%JOAO DA SILVA%'
    UNION SELECT '47'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%CONCEICAO APARECIDA DE JESUS%'
    UNION SELECT '48'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%AROLDO DE AZEVEDO%'
    UNION SELECT '49'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC	FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%JOAO SUSSUMU HIRATA%'
    UNION SELECT '50'AS POSICAO,DRE,CD_ESCOLA,SG_TP_ESCOLA,NOMESC FROM SME_ESCOLA_DIARIO WHERE SG_TP_ESCOLA LIKE '%EMEF%' AND NOMESC LIKE '%WANNY SALGADO ROCHA%') A ON A.CD_ESCOLA=B.CD_ESCOLA
--SELECT * FROM ##ESCOLAS_PRIORITARIAS