/*Prezados,

Solicitamos informações das unidades EJA / CIEJA que estejam em um raio de 4km dos endereços abaixo citados:

Rua do Ocidente, s/n - Distrito Vila Curuçá / DRE São Miguel
Estrada do Campo Limpo, 5.525 - Distrito de Campo Limpo / DRE Campo Limpo
Rua Engenheiro Milton de Alvarenga Peixoto, 20 - Distrito Jardim Ângela / DRE Campo Limpo
Avenida João Paulo I, 2100 - Distrito Brasilândia / DRE Freguesia/Brasilândia 
Rua Constelação do Esquadro, sn - Distrito Grajau / DRE Capela do Socorro
*/

/*DROP TABLE ##ENDERECOS
CREATE TABLE ##ENDERECOS (
	ID  INT IDENTITY(0,1),
	ENDERECO NVARCHAR(200) NULL,
	LAT FLOAT NULL,
	LON FLOAT NULL,
	DATA_GERACAO DATETIME NULL	)*/
TRUNCATE TABLE ##ENDERECOS


--ENDEREÇO 1
DECLARE @END NVARCHAR(200) SET @END ='Rua do Ocidente, s/n - Distrito Vila Curuçá, DRE - MP'
DECLARE @LAT_Y FLOAT SET @LAT_Y = -23.526641991109052 				    
DECLARE	@LON_X FLOAT SET @LON_X = -46.405034861214155               
INSERT INTO ##ENDERECOS  
SELECT @END,@LAT_Y, @LON_X,  SYSDATETIME() WHERE @LAT_Y IS NOT NULL
GO

--ENDEREÇO 2
DECLARE @END NVARCHAR(200) SET @END ='Estrada do Campo Limpo, 5.525 - Distrito de Campo Limpo, DRE - CL'
DECLARE @LAT_Y FLOAT SET @LAT_Y = -23.620681204680476  				    
DECLARE	@LON_X FLOAT SET @LON_X = -46.75960105189739               
INSERT INTO ##ENDERECOS  
SELECT @END,@LAT_Y, @LON_X,  SYSDATETIME() WHERE @LAT_Y IS NOT NULL
GO

--ENDEREÇO 3
DECLARE @END NVARCHAR(200) SET @END ='Rua Engenheiro Milton de Alvarenga Peixoto, 20 - Distrito Jardim Ângela, DRE - CL'
DECLARE @LAT_Y FLOAT SET @LAT_Y = -23.7220278946868  				    
DECLARE	@LON_X FLOAT SET @LON_X = -46.75702855169432              
INSERT INTO ##ENDERECOS  
SELECT @END,@LAT_Y, @LON_X,  SYSDATETIME() WHERE @LAT_Y IS NOT NULL
GO

--ENDEREÇO 4
DECLARE @END NVARCHAR(200) SET @END ='Avenida João Paulo I, 2100 - Distrito Brasilândia, DRE - FB'
DECLARE @LAT_Y FLOAT SET @LAT_Y = -23.473531291445774 				    
DECLARE	@LON_X FLOAT SET @LON_X = -46.68336255774963           
INSERT INTO ##ENDERECOS  
SELECT @END,@LAT_Y, @LON_X,  SYSDATETIME() WHERE @LAT_Y IS NOT NULL
GO

--ENDEREÇO 5
DECLARE @END NVARCHAR(200) SET @END ='Rua Constelação do Esquadro, sn - Distrito Grajau, DRE - CS'
DECLARE @LAT_Y FLOAT SET @LAT_Y = -23.77067998681957  				    
DECLARE	@LON_X FLOAT SET @LON_X = -46.70590925936277             
INSERT INTO ##ENDERECOS  
SELECT @END,@LAT_Y, @LON_X,  SYSDATETIME() WHERE @LAT_Y IS NOT NULL
GO

SELECT * FROM ##ENDERECOS


/*

SELECT 
B.ENDERECO,
FLOOR(FLOOR(SQRT(POWER((LAT *1000000 - (CD_COORDENADA_GEO_Y * 1000000) ),2) +  POWER((LON*1000000  - (CD_COORDENADA_GEO_X * 1000000)),2)) / 10)/0.6) AS DISTANCIA,
CONCAT (SG_TP_ESCOLA,NOMESC) AS CIEJA,
A.ENDERECO,
A.NR,
A.DRE
   
FROM SME_ESCOLA_DIARIO A, ##ENDERECOS B

WHERE TP_ESCOLA=13 
AND CD_SIT=1
AND FLOOR(FLOOR(SQRT(POWER((LAT *1000000 - (CD_COORDENADA_GEO_Y * 1000000) ),2) +  POWER((LON*1000000  - (CD_COORDENADA_GEO_X * 1000000)),2)) / 10)/0.6)<=4000
*/

SELECT
A.DRE,
A.CD_ESCOLA,
A.SG_TP_ESCOLA,
A.NOMESC,
A.ENDERECO,
A.NR,
A.CD_COORDENADA_GEO_Y,
A.CD_COORDENADA_GEO_X 
INTO ##ESCOLAS_COM_EJA
FROM SME_ESCOLA_DIARIO A
JOIN (SELECT DISTINCT 
		DRE,
		A.CD_ESCOLA,
		SG_TP_ESCOLA, 
		SG_ETAPA 
		FROM SME_ALUNOS_DIARIO A
	JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
 WHERE SG_ETAPA like 'EJA%') B ON A.CD_ESCOLA=B.CD_ESCOLA


 SELECT 
B.ENDERECO,
FLOOR(FLOOR(SQRT(POWER((LAT *1000000 - (CD_COORDENADA_GEO_Y * 1000000) ),2) +  POWER((LON*1000000  - (CD_COORDENADA_GEO_X * 1000000)),2)) / 10)/0.6) AS DISTANCIA,
CONCAT (SG_TP_ESCOLA,NOMESC) AS CIEJA,
A.ENDERECO,
A.NR,
A.DRE
   
FROM ##ESCOLAS_COM_EJA A, ##ENDERECOS B

WHERE FLOOR(FLOOR(SQRT(POWER((LAT *1000000 - (CD_COORDENADA_GEO_Y * 1000000) ),2) +  POWER((LON*1000000  - (CD_COORDENADA_GEO_X * 1000000)),2)) / 10)/0.6)<=4000

 