

--DROP TABLE ##CADASTRO_ESCOLAS_DIVULGACAO_EOL_COM_UNID_EXTINTAS
SELECT A.*,
B.NOVA_SITUACAO,
B.DT_EXTINCAO 

INTO ##CADASTRO_ESCOLAS_DIVULGACAO_EOL_COM_UNID_EXTINTAS

FROM [dbo].[VW_CADASTRO_ESCOLAS_DIVULGACAO_EOL_COM_UNID_EXTINTAS] A

      LEFT JOIN (SELECT
            A.*,
            B.dc_ato AS NOVA_SITUACAO,
            B.DT_SITUACAO AS DT_EXTINCAO
            FROM SME_ESCOLA_DIARIO A 
            LEFT JOIN (SELECT 
                  cd_unidade_educacao,
              	dc_ato,
              	CONVERT(VARCHAR,MAX(DT_INICIO_OCORRENCIA_UNIDADE),103) AS DT_SITUACAO FROM 
      			D_HISTORICO_UNIDADE 
                  WHERE tp_ocorrencia_historica=12 AND DT_INICIO_OCORRENCIA_UNIDADE>='2019-01-01' AND dc_ato<>'ESCOLA ATIVA'
                  GROUP BY cd_unidade_educacao,dc_ato) B ON A.CD_ESCOLA=B.cd_unidade_educacao
      WHERE TP_ESCOLA IN (1,2,3,4,10,11,12,13,14,16,17,18,28,31,32,33,38)) B ON A.CODESC=B.CD_ESCOLA
WHERE TP_ESCOLA IN (1,2,3,4,10,11,12,13,14,16,17,18,28,31,32,33,38)



--SELECT * FROM VW_CADASTRO_ESCOLAS_DIVULGACAO_EOL_COM_UNID_EXTINTAS