

--AMBIENTES DAS UNIDADES CONVENADAS PARCEIRAS - CR.PART.CONV E CEI INDIR COM INFORMAÇÕES DE ÁREAS DOS AMBIENTES



DROP TABLE ##ESCOLA_TP_11_12_AMBIENTES_COM_AREAS
SELECT 

	
	REDE =	CASE 
				WHEN C.TP_ESCOLA IN (1,2,3,4,10,13,14,16,17,18,20,23,25,27,28,30,31)THEN 'DIR'
				WHEN C.TP_ESCOLA IN (11,12,22,26) THEN 'CONV'
				
			END,
	B.NM_EXIBICAO_UNIDADE AS DRE ,
	CASE WHEN C.tp_escola=12 THEN 'CR.P.CONV'
		 WHEN C.tp_escola=11 THEN 'CEI INDIR'
	ELSE NULL END AS SG_TP_ESCOLA, 
	A.NM_UNIDADE_EDUCACAO AS NOMESC, 
	A.CD_UNIDADE_EDUCACAO AS CD_ESCOLA, 
	cd_ambiente_escola AS CD_AMBIENTE,
	DC_TIPO_AMBIENTE, 
	QT_AREA_UTIL AS AREA_AMBIENTE,
	A.CRDATE
INTO ##ESCOLA_TP_11_12_AMBIENTES_COM_AREAS
	 FROM DB_LOCAL.DBO.D_UNIDADE_EDUCACAO A
LEFT JOIN DB_LOCAL.DBO.D_UNIDADE_EDUCACAO B ON A.CD_UNIDADE_ADMINISTRATIVA_REFERENCIA = B.CD_UNIDADE_EDUCACAO
LEFT JOIN DB_LOCAL.DBO.D_ESCOLA C ON A.CD_UNIDADE_EDUCACAO = C.CD_ESCOLA
LEFT JOIN D_AMBIENTE_ESCOLA M ON A.CD_UNIDADE_EDUCACAO = M.CD_ESCOLA AND M.DT_FIM IS NULL
LEFT JOIN DB_LOCAL.DBO.D_TIPO_AMBIENTE N	WITH (NOLOCK) ON M.TP_AMBIENTE = N.TP_AMBIENTE AND N.DT_CANCELAMENTO IS NULL
WHERE 
	A.TP_UNIDADE_EDUCACAO = 1
	AND A.TP_SITUACAO_UNIDADE = 1
	AND M.DT_FIM IS NULL
	AND N.DT_CANCELAMENTO IS NULL

	AND C.tp_escola IN (11,12)
	GROUP BY 
	CASE 
		WHEN C.TP_ESCOLA IN (1,2,3,4,10,13,14,16,17,18,20,23,25,27,28,30,31)THEN 'DIR'
		WHEN C.TP_ESCOLA IN (11,12,22,26) THEN 'CONV'
	END,
	B.NM_EXIBICAO_UNIDADE ,
	B.NM_UNIDADE_EDUCACAO, 
	C.TP_ESCOLA, 
	A.NM_UNIDADE_EDUCACAO, 
	A.CD_UNIDADE_EDUCACAO, 
	A.cd_cie_unidade_educacao,
	DC_TIPO_AMBIENTE,
	A.CRDATE,
	qt_area_util,
	B.CD_UNIDADE_EDUCACAO,
	cd_ambiente_escola
--SELECT * FROM ##ESCOLA_TP_11_12_AMBIENTES_COM_AREAS
--------------------------------------------------------------------------------------------------------------------------------
DROP TABLE ##ESCOLA_TP_11_12_QTDE_AMBIENTES
SELECT 
REDE,
DRE,
SG_TP_ESCOLA,
NOMESC,
CD_ESCOLA 
[SALA DE AULA PROPRIA],
[SALA DE AULA ADAPTADA],
[SALA DE ED. INFANTIL PROPRIA],
[SALA DE ED. INFANTIL ADAPTADA],
[SALA DE ED. ESPECIAL PROPRIA],
[SALA DE ED. ESPECIAL ADAPTADA],
[SALA DE AULA OCIOSA],
[SALA DE EDUCACAO ARTISTICA],
[SALA DE LEITURA],
[SALA DE DATILOGRAFIA],
[SALA DE COMPUTACAO],
[SALA DE PROJECAO/VIDEO],
[SALA DE REUNIOES],
[SALA DE DIRETOR],
[SALA DE ASSISTENTE DO DIRETOR],
[SALA DE COORD. PEDAGOGICO],
[SALA DE PROFESSORES],
[SECRETARIA],
[ARQUIVO],
[ALMOXARIFADO],
[DESPENSA /DEPOSITO ALIMENTOS],
[DEPOSITO],
[AUDITORIO],
[PALCO],
[LABORATORIO DE CIENCIAS],
[LABORATORIO DE FISICA],
[LABORATORIO DE QUIMICA],
[LABORATORIO DE BIOLOGIA],
[LABORATORIO DE PROTESE],
[OFICINA],
[GABINETE DENTARIO],
[GABINETE MEDICO],
[COZINHA],
[REFEITORIO],
[GALPAO],
[SANITARIO ALUNOS - MASCULINO],
[SANITARIO ALUNOS - FEMININO],
[SANIT.FUNCIONARIOS-MASCULINO],
[SANIT.FUNCIONARIOS-FEMININO],
[VESTIARIO MASCULINO],
[VESTIARIO FEMININO],
[SALA DE EDUCACAO FISICA],
[SL. MAT.DESPORTIVO/FANFARRA],
[QUADRA COBERTA],
[QUADRA DESCOBERTA],
[PATIO COBERTO],
[PATIO DESCOBERTO],
[PISO CIMENTADO],
[ZELADORIA],
[GUARITA],
[CASA DE MAQUINAS],
[QUIOSQUE],
[PISCINA],
[AREA DE SERVICO],
[PLAY GROUND],
[SANITARIO ALUNOS - MISTO],
[SANIT.FUNCIONARIOS - MISTO],
[SANIT.ANEXO SL.AULA-MISTO],
[VESTIARIO DE FUNCIONARIOS],
[SL. AULA FORA ESC.- EMERGENCIA],
[DEPOSITO MAT. DIDATICO/PEDAG.],
[CAMARIM],
[SALA DE PSICOLOGO],
[SALA RECUPERACAO/APOIO PEDAG.],
[CANTINA],
[ESTACIONAMENTO],
[SALA PARA INSTIT.AUXILIARES],
[SALA DE AULA DESATIVADA],
[OUTRO AMBIENTE/SALA DE AULA],
[SALA DE RECREACAO],
[SL. TREINAMENTO/RITMICO/CORPOR],
[SL. TREINAMENTO/FONO/AUDIO],
[SL. TREINAMENTO INDIVIDUAL],
[LABORATORIO DE INFORMATICA],
[SAP],
[SAPNE],
[CADASTRO DE VAGA DE EVENTUAL],
[RAMPA DE ACESSO P/ DEFICIENTES],
[SANITARIO PARA DEFICIENTES],
[BERCARIO],
[ELEVADOR],
[SALA DE ESTUDO/PESQUISAS],
[BRINQUEDOTECA],
[LACTARIO],
[SALA DE ENFERMAGEM],
[LAVANDERIA],
[SOLARIO],
[TROCADOR],
[FOYER / EXPOSICOES],
[TEATRO],
[ATELIE],
[ESTUDIO],
[ANTECAMARA],
[RECEPCAO],
[SALA DE DANCA / GINASTICA],
[AREA DE BANHO],
[PRACA DO CAFE],
[PADARIA - ESCOLA],
[BIBLIOTECA],
[TELECENTRO],
[ANFITEATRO],
[CAMPO DE FUTEBOL],
[PISTA DE SKATE],
[VIDEOTECA],
[SALA PARA TV/VIDEO],
[GINASIO DE ESPORTES],
[PARQUE INFANTIL],
[DORMITORIO],
[FRALDARIO],
[SANITARIO FUNC FORA DO PREDIO],
[SANITARIO ALUNO FORA DO PREDIO],
[SANITARIO ADEQUADO PRE-ESCOLA],
[DEPEN/VIAS ADEQUADAS ALUNO NEE],
[CONTAINER],
[SALA EM UNIDADE FUNCIONAL],
[SALA RECURSOS MULTIFUNCIONAIS],
[SALA DE PESQUISA],
[SANITARIO ALUNOS COM CHUVEIRO],
[AREA VERDE],
[SALA DE MUSICA CORAL],
[SALA MULTIUSO MUSICA DANCA ART],
CRDATE
INTO ##ESCOLA_TP_11_12_QTDE_AMBIENTES
FROM ESCOLA_AMBIENTES_LINEAR
WHERE TP_ESCOLA IN (11,12)

--SELECT * FROM ##ESCOLA_TP_11_12_QTDE_AMBIENTES
		