

drop table ##escolas_nao_ativas
SELECT 
A.CD_ESCOLA,
A.TP_ESCOLA,
A.SG_TP_ESCOLA,
A.CD_SIT,
C.dc_tipo_situacao_unidade,
YEAR(B.DT_ATUALIZACAO) AS ANO

INTO ##escolas_nao_ativas

FROM SME_ESCOLA_DIARIO A
JOIN (SELECT 
      CD_UNIDADE_EDUCACAO,
	  MAX(DT_ATUALIZACAO_TABELA) AS DT_ATUALIZACAO
      FROM D_HISTORICO_UNIDADE WHERE tp_ocorrencia_historica IN (2,3,4,5,6,7)
      GROUP BY CD_UNIDADE_EDUCACAO) B ON A.CD_ESCOLA=B.cd_unidade_educacao
JOIN tipo_situacao_unidade C ON A.CD_SIT=C.tp_situacao_unidade
JOIN tipo_escola D ON A.TP_ESCOLA=D.tp_escola
WHERE A.CD_SIT<>1
GROUP BY
A.CD_ESCOLA,
A.TP_ESCOLA,
A.SG_TP_ESCOLA,
A.CD_SIT,
C.dc_tipo_situacao_unidade,
YEAR(B.DT_ATUALIZACAO)
--select * from ##escolas_nao_ativas


drop table ##escolas_nao_ativas_resumo
SELECT 

ANO,
SG_TP_ESCOLA,
COUNT (DISTINCT CASE WHEN CD_SIT= 2 THEN CD_ESCOLA ELSE NULL END) AS 'EXTINTA',
COUNT (DISTINCT CASE WHEN CD_SIT= 3 THEN CD_ESCOLA ELSE NULL END) AS 'REFORMA',
COUNT (DISTINCT CASE WHEN CD_SIT= 4 THEN CD_ESCOLA ELSE NULL END) AS 'TRANSF PARA SEE',
COUNT (DISTINCT CASE WHEN CD_SIT= 5 THEN CD_ESCOLA ELSE NULL END) AS 'ATIV SUSPENSAS',
COUNT (DISTINCT CASE WHEN CD_SIT= 6 THEN CD_ESCOLA ELSE NULL END) AS 'PARALISADA',
COUNT (DISTINCT CASE WHEN CD_SIT= 7 THEN CD_ESCOLA ELSE NULL END) AS 'EM OBRAS',
COUNT(CD_ESCOLA) AS TOTAL
INTO ##escolas_nao_ativas_resumo
FROM ##escolas_nao_ativas
GROUP BY 
ANO,
SG_TP_ESCOLA

--SELECT * FROM ##escolas_nao_ativas_resumo where ano = 2011