select 
TIPO,
COUNT(CD_ESCOLA) AS QTDE,
YEAR(DT_CRIACAO) AS ANO



from [dbo].[VW_ULTIMAS_ESCOLAS_CRIADAS]
WHERE YEAR(DT_CRIACAO) >2010 AND TIPO = 'CEI DIRET'
GROUP BY TIPO,YEAR(DT_CRIACAO)


SELECT * FROM [dbo].[VW_ULTIMAS_ESCOLAS_CRIADAS]


select 
YEAR(DT_CRIACAO) AS ANO,
COUNT(DISTINCT CASE WHEN TIPO = 'CEI DIRET' THEN CD_ESCOLA ELSE NULL END ) AS 'CEI DIRET',
COUNT(DISTINCT CASE WHEN TIPO = 'CEI INDIR' THEN CD_ESCOLA ELSE NULL END ) AS 'CEI INDIR',
COUNT(DISTINCT CASE WHEN TIPO = 'CEMEI' THEN CD_ESCOLA ELSE NULL END ) AS 'CEMEI',
COUNT(DISTINCT CASE WHEN TIPO = 'CEU CEI' THEN CD_ESCOLA ELSE NULL END ) AS 'CEU CEI',
COUNT(DISTINCT CASE WHEN TIPO = 'CEU CEMEI' THEN CD_ESCOLA ELSE NULL END ) AS 'CEI CEMEI',
COUNT(DISTINCT CASE WHEN TIPO = 'CEU EMEI' THEN CD_ESCOLA ELSE NULL END ) AS 'CEI EMEI',
COUNT(DISTINCT CASE WHEN TIPO = 'CR.P.CONV' THEN CD_ESCOLA ELSE NULL END ) AS 'CR.P.CONV',
--COUNT(DISTINCT CASE WHEN TIPO = 'CR.P.CONV' THEN CD_ESCOLA ELSE NULL END ) AS 'EMEF(LICEU)',
--COUNT(DISTINCT CASE WHEN TIPO = 'CR.P.CONV' THEN CD_ESCOLA ELSE NULL END ) AS 'EMEI(LICEU)',
COUNT(DISTINCT CASE WHEN TIPO = 'EMEI' THEN CD_ESCOLA ELSE NULL END ) AS 'EMEI',
COUNT(DISTINCT CASE WHEN TIPO = 'EMEF' THEN CD_ESCOLA ELSE NULL END ) AS 'EMEF'

from [dbo].[VW_ULTIMAS_ESCOLAS_CRIADAS]
--WHERE YEAR(DT_CRIACAO) <2010 --AND TIPO = 'CEI DIRET'
GROUP BY YEAR(DT_CRIACAO) WITH ROLLUP