
CREATE VIEW VW_CODIGOS_UTILIZADOS AS 
SELECT CD_ESCOLA FROM DB_EDUCACAO_1_PRODAM.SE1426.DBO.ESCOLA
UNION 
SELECT cd_unidade_administrativa FROM DB_EDUCACAO_1_PRODAM.SE1426.DBO.UNIDADE_ADMINISTRATIVA 

--SELECT TOP 5 * FROM VW_CODIGOS_UTILIZADOS WHERE CD_ESCOLA LIKE '309%' ORDER BY CD_ESCOLA DESC
--SELECT TOP 5 * FROM VW_CODIGOS_UTILIZADOS WHERE CD_ESCOLA LIKE '200%' ORDER BY CD_ESCOLA DESC
--SELECT TOP 5 * FROM VW_CODIGOS_UTILIZADOS WHERE CD_ESCOLA LIKE '400%' ORDER BY CD_ESCOLA DESC
--SELECT TOP 5 * FROM VW_CODIGOS_UTILIZADOS WHERE CD_ESCOLA LIKE '501%' ORDER BY CD_ESCOLA DESC
--SELECT TOP 5 * FROM VW_CODIGOS_UTILIZADOS WHERE CD_ESCOLA LIKE '600%' ORDER BY CD_ESCOLA DESC
--SELECT TOP 5 * FROM VW_CODIGOS_UTILIZADOS WHERE CD_ESCOLA LIKE '7000%' ORDER BY CD_ESCOLA DESC
--SELECT TOP 5 * FROM VW_CODIGOS_UTILIZADOS WHERE CD_ESCOLA LIKE '7005%' ORDER BY CD_ESCOLA DESC
--SELECT TOP 5 * FROM VW_CODIGOS_UTILIZADOS WHERE CD_ESCOLA LIKE '019%' ORDER BY CD_ESCOLA DESC