/*
Total de prédios administrativos;  
Total de salas regulares, EMEFs, EMEIs, EMEFMs, EMEBS, CEIs DIRET, CIEJAs, CEU EMEF, CEU EMEI, CEU CEI, CEU CEMEI, CECI e LICEU;
Total de sala de Informática das EMEFs, EMEFMs, EMEBS, CIEJAs, CEU EMEF, CECI e LICEU;
Total de sala de Leitura das EMEFs, EMEFMs, EMEBS, CIEJAs, CEU EMEF, CECI e LICEU.
*/

DROP TABLE ##UNIDADES_ADMINISTRATIVAS
SELECT 
DRE,
CD_UNIDADE_EDUCACAO AS CODEOL,
TP_UNIDADE,
SG_TP_ESCOLA AS TIPO,
NM_UNIDADE_EDUCACAO AS NOME_UNIDADE,
SITUACAO,
DC_TP_LOGRADOURO AS TP_LOGRADOURO,
NM_LOGRADOURO AS ENDERECO,
NR,
COMPL,
BAIRRO,
CEP,
DT_BASE

INTO ##UNIDADES_ADMINISTRATIVAS


FROM vw_unidades_diretas_setores_internos_sme_dre_ceus
WHERE TP_UNIDADE = 'UNIDADE ADMINISTRATIVA'
--SELECT * FROM ##UNIDADES_ADMINISTRATIVAS

SELECT * 
FROM vw_unidades_diretas_setores_internos_sme_dre_ceus
WHERE TP_UNIDADE = 'UNIDADE ADMINISTRATIVA'
AND CD_UNIDADE_REFERENCIA LIKE '11%'
AND CD_UNIDADE_EDUCACAO IN (301105,
308810)



--EXEC BI_ESCOLA_AMBIENTE

DROP TABLE ##SALAS_AULA_POR_SG_TP_ESCOLA
SELECT 

SG_TP_ESCOLA,

ISNULL(SUM([SALA DE AULA ADAPTADA]),0) AS SL_AULA_ADAPTADA,       
ISNULL(SUM([SALA DE AULA PROPRIA]),0) AS SL_AULA_PROPRIA,         
ISNULL(SUM([SALA DE COMPUTACAO]),0) AS SL_COMPUTACAO, 
ISNULL(SUM([LABORATORIO DE INFORMATICA]),0) AS LAB_INFORMATICA,           
ISNULL(SUM([SALA DE ED. ESPECIAL ADAPTADA]),0) AS SL_ED_ESP_ADAPTADA,
ISNULL(SUM([SALA DE ED. ESPECIAL PROPRIA]),0) AS SL_ED_ESP_PROPRIA,
ISNULL(SUM([SALA DE ED. INFANTIL ADAPTADA]),0) AS SL_ED_INF_ADAPTADA,
ISNULL(SUM([SALA DE ED. INFANTIL PROPRIA]),0) AS SL_ED_INF_PROPRIA,
ISNULL(SUM([SALA DE LEITURA]),0) AS SL_LEITURA,               
ISNULL(SUM([BERCARIO]),0) AS BERCARIO
INTO ##SALAS_AULA_POR_SG_TP_ESCOLA

FROM ##ESCOLA_AMBIENTES_LINEAR

WHERE TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31,32,33)
GROUP BY SG_TP_ESCOLA
ORDER BY 1
--SELECT * FROM ##SALAS_AULA_POR_SG_TP_ESCOLA


DROP TABLE ##LISTA_ESCOLAS_AMBIENTES_SL_AULA
SELECT DISTINCT
DRE,
CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
ENDERECO,
NR,
COMPL,
BAIRRO,
CEP,
ISNULL([SALA DE AULA ADAPTADA],0) AS SL_AULA_ADAPTADA,       
ISNULL([SALA DE AULA PROPRIA],0) AS SL_AULA_PROPRIA,         
ISNULL([SALA DE COMPUTACAO],0) AS SL_COMPUTACAO, 
ISNULL([LABORATORIO DE INFORMATICA],0) AS LAB_INFORMATICA,           
ISNULL([SALA DE ED. ESPECIAL ADAPTADA],0) AS SL_ED_ESP_ADAPTADA,
ISNULL([SALA DE ED. ESPECIAL PROPRIA],0) AS SL_ED_ESP_PROPRIA,
ISNULL([SALA DE ED. INFANTIL ADAPTADA],0) AS SL_ED_INF_ADAPTADA,
ISNULL([SALA DE ED. INFANTIL PROPRIA],0) AS SL_ED_INF_PROPRIA,
ISNULL([SALA DE LEITURA],0) AS SL_LEITURA,               
ISNULL([BERCARIO],0) AS BERCARIO,
CRDATE
INTO ##LISTA_ESCOLAS_AMBIENTES_SL_AULA
FROM  ##ESCOLA_AMBIENTES_LINEAR 
WHERE TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,28,30,31,32,33)
--SELECT * FROM ##LISTA_ESCOLAS_AMBIENTES_SL_AULA


