DROP TABLE ##TURMAS_ATIVAS_ANOS_ANTERIORES_MOVA
SELECT DISTINCT 
A.AN_LETIVO,
D.CD_SIT,
D.DRE,
D.SG_TP_ESCOLA,
D.NOMESC,
A.CD_ESCOLA,
--B.CD_TURMA_ESCOLA,
C.dc_tipo_turma,
--B.ST_TURMA_ESCOLA,
--COUNT (DISTINCT CASE WHEN B.ST_TURMA_ESCOLA ='C' THEN B.cd_turma_escola ELSE NULL END) AS TUR_CONCLUIDA,
COUNT (DISTINCT CASE WHEN B.ST_TURMA_ESCOLA IN ('A','O') THEN B.cd_turma_escola ELSE NULL END) AS TUR_ATIVA,
--COUNT (DISTINCT CASE WHEN B.ST_TURMA_ESCOLA ='O' THEN B.cd_turma_escola ELSE NULL END) AS TUR_ORGANIZ,
--COUNT (DISTINCT CASE WHEN B.ST_TURMA_ESCOLA ='E' THEN B.cd_turma_escola ELSE NULL END) AS TUR_EXTINTA,
CONVERT(VARCHAR,D.CRDATE-1,103) AS DT_BASE

INTO ##TURMAS_ATIVAS_ANOS_ANTERIORES_MOVA

FROM DB_EDUCACAO_1_PRODAM.SE1426.DBO.MATRICULA A
JOIN DB_EDUCACAO_1_PRODAM.SE1426.DBO.TURMA_ESCOLA B ON A.CD_ESCOLA =B.CD_ESCOLA
JOIN TIPO_TURMA C ON B.CD_TIPO_TURMA=C.CD_TIPO_TURMA
RIGHT JOIN SME_ESCOLA_DIARIO D ON A.CD_ESCOLA=D.cd_escola
WHERE A.AN_LETIVO <YEAR(GETDATE()) AND A.CD_TIPO_PROGRAMA ='45' AND D.CD_SIT=1

GROUP BY
D.DRE,
D.SG_TP_ESCOLA,
D.NOMESC,
A.AN_LETIVO,
D.CD_SIT,
A.CD_ESCOLA,
--B.CD_TURMA_ESCOLA,
C.dc_tipo_turma,
--B.ST_TURMA_ESCOLA,
D.CRDATE
order by 1

--SELECT * FROM ##TURMAS_ATIVAS_ANOS_ANTERIORES_MOVA

SELECT TOP 1 * FROM D_ESCOLA

SELECT * FROM D_TIPO_TURMA

SELECT * FROM D_TURMA_ESCOLA

SELECT TOP 1  * FROM DB_EDUCACAO_1_PRODAM.SE1426.DBO.historico_turma_escola





	

	SELECT DISTINCT TOP 1 * FROM DB_EDUCACAO_1_PRODAM.SE1426.DBO.MATRICULA
	SELECT DISTINCT TOP 1 * FROM DB_EDUCACAO_1_PRODAM.SE1426.DBO.TURMA_ESCOLA
	SELECT * FROM D_TURMA_ESCOLA