--AUDITORIA - SALAS DE AULA COM ÁREAS MENORES DE 20 METROS OU MAIORES DE 60 METROS





DROP TABLE ##SL_AULA_AREA
SELECT DISTINCT
CD_ESCOLA,
AN_LETIVO,
--CD_TURMA_ESCOLA,
--CD_TIPO_PROGRAMA,
--ST_TURMA_ESCOLA,
--CD_TIPO_TURNO,
--CD_ETAPA_ENSINO,
--SG_ETAPA,
--CD_SERIE_ENSINO, 
--DC_SERIE_ENSINO,
--QT_VAGA_OFERECIDA,
DC_TIPO_AMBIENTE,
NR_SALA,
ISNULL(QT_AREA_UTIL,0)AS AREA_AMBIENTE,
--QT_IDEAL_PESSOA,
--QT_REAL_PESSOA,
--AL_AT,
CRDATE
INTO ##SL_AULA_AREA
FROM SME_CLASSES_DIARIO
WHERE CD_TIPO_PROGRAMA IS NULL 
AND DC_TIPO_AMBIENTE IN('SALA DE AULA ADAPTADA','SALA DE AULA PROPRIA','SALA DE ED. ESPECIAL PROPRIA','SALA DE ED. INFANTIL ADAPTADA','SALA DE ED. INFANTIL PROPRIA','BERCARIO')
order by CD_ESCOLA,NR_SALA
--select * from ##SL_AULA_AREA ORDER BY 1

SELECT 
COUNT( CASE WHEN AREA_AMBIENTE <20 THEN DC_TIPO_AMBIENTE ELSE NULL END) AS '<20 M2',
COUNT( CASE WHEN AREA_AMBIENTE BETWEEN 20 AND 29 THEN DC_TIPO_AMBIENTE ELSE NULL END) AS '20 A 29 M2',
COUNT( CASE WHEN AREA_AMBIENTE BETWEEN 30 AND 39 THEN DC_TIPO_AMBIENTE ELSE NULL END) AS '30 A 39 M2',
COUNT( CASE WHEN AREA_AMBIENTE BETWEEN 40 AND 49 THEN DC_TIPO_AMBIENTE ELSE NULL END) AS '40 A 49 M2',
COUNT( CASE WHEN AREA_AMBIENTE BETWEEN 50 AND 59 THEN DC_TIPO_AMBIENTE ELSE NULL END) AS '50 A 59 M2',
COUNT( CASE WHEN AREA_AMBIENTE BETWEEN 60 AND 69 THEN DC_TIPO_AMBIENTE ELSE NULL END) AS '60 A 69 M2',
COUNT( CASE WHEN AREA_AMBIENTE BETWEEN 70 AND 79 THEN DC_TIPO_AMBIENTE ELSE NULL END) AS '70 A 79 M2',
COUNT( CASE WHEN AREA_AMBIENTE BETWEEN 80 AND 89 THEN DC_TIPO_AMBIENTE ELSE NULL END) AS '80 A 89 M2',
COUNT( CASE WHEN AREA_AMBIENTE BETWEEN 90 AND 99 THEN DC_TIPO_AMBIENTE ELSE NULL END) AS '90 A 99 M2',
COUNT( CASE WHEN AREA_AMBIENTE >100 THEN DC_TIPO_AMBIENTE ELSE NULL END) AS '>=100 M2',
COUNT( DC_TIPO_AMBIENTE) AS TOTAL
FROM ##SL_AULA_AREA

DROP TABLE ##SL_AULA_REVISAR_AREA
SELECT
DRE,
A.CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
DC_TIPO_AMBIENTE,
NR_SALA,
AREA_AMBIENTE,
--AL_AT AS MATRIC,
--CASE WHEN AL_AT>0 THEN cast(cast(AREA_AMBIENTE as decimal(7,2))/AL_AT as decimal(7,2)) ELSE NULL END AS M2_POR_ALUNO,
CONVERT(VARCHAR,A.CRDATE-1,103) AS DT_BASE
INTO ##SL_AULA_REVISAR_AREA
FROM ##SL_AULA_AREA A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
WHERE AREA_AMBIENTE <20 OR AREA_AMBIENTE >=60 AND CD_SIT=1

DROP TABLE ##BT SELECT * INTO ##BT FROM ##SL_AULA_REVISAR_AREA  WHERE DRE = 'DRE - BT'
DROP TABLE ##CL SELECT * INTO ##CL FROM ##SL_AULA_REVISAR_AREA  WHERE DRE = 'DRE - CL'
DROP TABLE ##CS SELECT * INTO ##CS FROM ##SL_AULA_REVISAR_AREA  WHERE DRE = 'DRE - CS'
DROP TABLE ##FB SELECT * INTO ##FB FROM ##SL_AULA_REVISAR_AREA  WHERE DRE = 'DRE - FB'
DROP TABLE ##G SELECT * INTO ##G FROM ##SL_AULA_REVISAR_AREA  WHERE DRE = 'DRE - G'
DROP TABLE ##IP SELECT * INTO ##IP FROM ##SL_AULA_REVISAR_AREA  WHERE DRE = 'DRE - IP'
DROP TABLE ##IQ SELECT * INTO ##IQ FROM ##SL_AULA_REVISAR_AREA  WHERE DRE = 'DRE - IQ'
DROP TABLE ##JT SELECT * INTO ##JT FROM ##SL_AULA_REVISAR_AREA  WHERE DRE = 'DRE - JT'
DROP TABLE ##MP SELECT * INTO ##MP FROM ##SL_AULA_REVISAR_AREA  WHERE DRE = 'DRE - MP'
DROP TABLE ##PE SELECT * INTO ##PE FROM ##SL_AULA_REVISAR_AREA  WHERE DRE = 'DRE - PE'
DROP TABLE ##PJ SELECT * INTO ##PJ FROM ##SL_AULA_REVISAR_AREA  WHERE DRE = 'DRE - PJ'
DROP TABLE ##SA SELECT * INTO ##SA FROM ##SL_AULA_REVISAR_AREA  WHERE DRE = 'DRE - SA'
DROP TABLE ##SM SELECT * INTO ##SM FROM ##SL_AULA_REVISAR_AREA  WHERE DRE = 'DRE - SM'