
SELECT DISTINCT
DRE,
A.CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
A.NR_SALA,

M.DC_TURMA_ESCOLA MANHÃ
--T.DC_TURMA_ESCOLA TARDE,
--N.DC_TURMA_ESCOLA TNOITE,
--G.DC_TURMA_ESCOLA INTEGRAL

FROM SME_CLASSES_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN (SELECT CD_ESCOLA, NR_SALA,CD_TIPO_TURNO,DC_TURMA_ESCOLA FROM SME_CLASSES_DIARIO WHERE SG_ETAPA IS NOT NULL AND CD_TIPO_TURNO =1) M ON A.CD_ESCOLA=M.CD_ESCOLA
JOIN (SELECT CD_ESCOLA, NR_SALA,CD_TIPO_TURNO,DC_TURMA_ESCOLA FROM SME_CLASSES_DIARIO WHERE SG_ETAPA IS NOT NULL AND CD_TIPO_TURNO =3) T ON A.CD_ESCOLA=T.CD_ESCOLA
JOIN (SELECT CD_ESCOLA, NR_SALA,CD_TIPO_TURNO,DC_TURMA_ESCOLA FROM SME_CLASSES_DIARIO WHERE SG_ETAPA IS NOT NULL AND CD_TIPO_TURNO =5) N ON A.CD_ESCOLA=N.CD_ESCOLA
JOIN (SELECT CD_ESCOLA, NR_SALA,CD_TIPO_TURNO,DC_TURMA_ESCOLA FROM SME_CLASSES_DIARIO WHERE SG_ETAPA IS NOT NULL AND CD_TIPO_TURNO =6) G ON A.CD_ESCOLA=G.CD_ESCOLA
WHERE SG_ETAPA IS NOT NULL


ORDER BY 2,5


SELECT CD_ESCOLA, NR_SALA,CD_TIPO_TURNO,DC_TURMA_ESCOLA FROM SME_CLASSES_DIARIO WHERE SG_ETAPA IS NOT NULL AND CD_TIPO_TURNOORDER BY 1,2