--ESTUDO ESCOLAS COM ACESSIBILIDADE

USE Db_Local
DROP TABLE ##LISTA_ESCOLAS_ELEVADOR_RAMPA_SANIDEF
SELECT 
DRE,
REDE, 
A.CD_ESCOLA,  
SG_TP_ESCOLA, 
NOMESC,
COUNT (DISTINCT CASE WHEN B.TP_AMBIENTE = 114 THEN A.CD_ESCOLA ELSE NULL END) AS RAMPA,
COUNT (DISTINCT CASE WHEN B.TP_AMBIENTE = 117 THEN A.CD_ESCOLA ELSE NULL END) AS ELEVADOR,
COUNT (DISTINCT CASE WHEN B.TP_AMBIENTE = 115 THEN A.CD_ESCOLA ELSE NULL END) AS SANITARIO_DEF,
CONVERT (VARCHAR,A.CRDATE-1, 103) AS DT_BASE
INTO ##LISTA_ESCOLAS_ELEVADOR_RAMPA_SANIDEF
FROM SME_ESCOLA_DIARIO A
JOIN D_AMBIENTE_ESCOLA B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN D_TIPO_AMBIENTE C ON B.tp_ambiente=C.tp_ambiente

WHERE A.CD_SIT = 1 AND  C.dt_cancelamento IS NULL AND B.DT_FIM IS NULL  AND TP_ESCOLA IN (1,2,3,4,10,11,12,13,14,16,17,18,28,30,31)
AND B.tp_ambiente IN (114,115,117)
GROUP BY
DRE,
REDE, 
A.CD_ESCOLA, 
SG_TP_ESCOLA, 
NOMESC,
A.CRDATE
ORDER BY 1,2,3
--SELECT * FROM ##LISTA_ESCOLAS_ELEVADOR_RAMPA_SANIDEF
-----------------------------------------------------------------------------

