

DROP TABLE ##estudo_salas_aula_turmas_por_turno
SELECT 
DRE,
A.CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
NR_SALA,
COUNT(DISTINCT CASE WHEN CD_TIPO_TURNO=1 THEN DC_TURMA_ESCOLA ELSE NULL END) AS MANHA,
COUNT(DISTINCT CASE WHEN CD_TIPO_TURNO=2 THEN DC_TURMA_ESCOLA ELSE NULL END) AS INTERMEDIARIO,
COUNT(DISTINCT CASE WHEN CD_TIPO_TURNO=3 THEN DC_TURMA_ESCOLA ELSE NULL END) AS TARDE,
COUNT(DISTINCT CASE WHEN CD_TIPO_TURNO=4 THEN DC_TURMA_ESCOLA ELSE NULL END) AS VESPERINO,
COUNT(DISTINCT CASE WHEN CD_TIPO_TURNO=5 THEN DC_TURMA_ESCOLA ELSE NULL END) AS NOITE,
COUNT(DISTINCT CASE WHEN CD_TIPO_TURNO=6 THEN DC_TURMA_ESCOLA ELSE NULL END) AS INTEGRAL

INTO ##estudo_salas_aula_turmas_por_turno

FROM SME_CLASSES_DIARIO A 
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA=B.CD_ESCOLA
WHERE SG_ETAPA IS NOT NULL AND TP_ESCOLA<>15

GROUP BY 
DRE,
A.CD_ESCOLA,
SG_TP_ESCOLA,
NOMESC,
NR_SALA


ORDER BY 2,5
--SELECT * FROM  ##estudo_salas_aula_turmas_por_turno



