


select dre,cd_escola,sg_tp_escola,nomesc from Db_local..SME_ESCOLA_DIARIO
WHERE
 
   NOMESC LIKE 'ADOLFINO D%'
OR NOMESC LIKE 'ARTHUR GUI%'
OR NOMESC LIKE 'DALILA DE %'
OR NOMESC LIKE 'EDSON LUIZ%'
OR NOMESC LIKE 'ERASMO BRA%'
OR NOMESC LIKE 'ERNESTINO %'
OR NOMESC LIKE 'FELICIA DE%'
OR NOMESC LIKE 'FULVIO ABR%'
OR NOMESC LIKE 'GERSON DE %'
OR NOMESC LIKE 'INES BREGA%'
OR NOMESC LIKE 'JAIME CORT%'
OR NOMESC LIKE 'JOSE CAVAL%'
OR NOMESC LIKE 'JULIO MAIA%'
OR NOMESC LIKE 'LAURO CELI%'
OR NOMESC LIKE 'LUIZA MARC%'
OR NOMESC LIKE 'LUZIA GODO%'
OR NOMESC LIKE 'MARIA JOSE B%'
OR NOMESC LIKE 'MARIA LUIS%'
OR NOMESC LIKE 'NIPO BRASI%'
OR NOMESC LIKE 'PAULO MACH%'
OR NOMESC LIKE 'PIO XII%'
OR NOMESC LIKE 'TAUNAY%'
OR NOMESC LIKE 'THOMAZ ROD%'
OR NOMESC LIKE 'VALENTIM C%'
OR NOMESC LIKE 'WALTER BEL%'


SELECT

*,
left(NOME_ESCOLA,10) FROM [dbo].[tratadas$] WHERE ANO=2025