DROP view ALUNO_CLASSIFICADO_TRANSPORTE

CREATE view ALUNO_CLASSIFICADO_TRANSPORTE AS
      SELECT ACT.* 
      FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.[DBO].[ALUNO_CLASSIFICADO_TRANSPORTE] ACT
      JOIN DB_EDUCACAO_1_PRODAM.SE1426_ss.dbo.veiculo_viagem_aluno VVA ON ACT.CD_ALUNO_CLASSIFICADO_TRANSPORTE = VVA.CD_ALUNO_CLASSIFICADO_TRANSPORTE
      WHERE VVA.DT_FIM IS NULL  
--SELECT * FROM ALUNO_CLASSIFICADO_TRANSPORTE