DROP view ALUNO_CANDIDATO_TRANSPORTE
      SELECT ACT.* 
	  FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.[DBO].[ALUNO_CANDIDATO_TRANSPORTE] ACT
      WHERE AN_LETIVO = YEAR(GETDATE())
--SELECT * FROM ALUNO_CANDIDATO_TRANSPORTE 
