


--MATRICULAS MOVA

SELECT 
B.DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
CONCAT(B.ENDERECO,', ',B.NR) AS ENDEREÇO, 
SUM(QT_VAGA_OFERECIDA) AS VAGOFER,SUM(AL_AT) AS MATR, 
CONVERT(VARCHAR,A.CRDATE-1,103) AS DT_BASE 
FROM SME_CLASSES_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA = B.CD_ESCOLA
WHERE B.TP_ESCOLA=22
GROUP BY
B.DRE,
B.CD_ESCOLA,
B.SG_TP_ESCOLA,
B.NOMESC,
A.CRDATE,
B.ENDERECO,
B.NR
 

--MATRICULAS CCA LISTA

SELECT B.DRE,B.CD_ESCOLA,B.SG_TP_ESCOLA,B.NOMESC, C.DC_TIPO_PROGRAMA,COUNT (CASE WHEN A.CD_TIPO_PROGRAMA=430 THEN CD_ALUNO ELSE NULL END) AS MATR FROM SME_ALUNOS A
JOIN SME_ESCOLA B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN D_TIPO_PROGRAMA C ON A.CD_TIPO_PROGRAMA=C.cd_tipo_programa

WHERE TP_ESCOLA=29
GROUP BY B.DRE,B.CD_ESCOLA,B.SG_TP_ESCOLA,B.NOMESC, C.DC_TIPO_PROGRAMA

--MATRICULAS CCA POR DRE

SELECT B.DRE,B.SG_TP_ESCOLA,COUNT (CASE WHEN A.CD_TIPO_PROGRAMA=430 THEN CD_ALUNO ELSE NULL END) AS MATR FROM SME_ALUNOS A
JOIN SME_ESCOLA B ON A.CD_ESCOLA=B.CD_ESCOLA
JOIN D_TIPO_PROGRAMA C ON A.CD_TIPO_PROGRAMA=C.cd_tipo_programa
WHERE TP_ESCOLA=29
GROUP BY B.DRE,B.SG_TP_ESCOLA,C.DC_TIPO_PROGRAMA





/*********************************************************************************************************************/

SELECT B.DRE,B.CD_ESCOLA,B.SG_TP_ESCOLA,B.NOMESC,CONCAT(B.ENDERECO,', ',B.NR) AS ENDEREÇO, CD_TURMA_ESCOLA,SUM(QT_VAGA_OFERECIDA) AS VAGOFER,SUM(AL_AT) AS MATR, CONVERT(VARCHAR,A.CRDATE-1,103) AS DT_BASE 
FROM SME_CLASSES_DIARIO A
JOIN SME_ESCOLA_DIARIO B ON A.CD_ESCOLA = B.CD_ESCOLA


WHERE B.TP_ESCOLA=22 AND B.CD_ESCOLA IN (500974,501483,501609,501600)

GROUP BY B.DRE,B.CD_ESCOLA,B.SG_TP_ESCOLA,B.NOMESC,B.ENDERECO,B.NR,A.CRDATE, CD_TURMA_ESCOLA
ORDER BY B.DRE,B.NOMESC

SELECT TOP 10 * FROM SME_CLASSES_DIARIO

select * from sme_escola_diario where cd_escola=501600

