

DROP TABLE tipo_abastecimento_agua	SELECT *,GETDATE() AS CRDATE INTO tipo_abastecimento_agua FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_abastecimento_agua
DROP TABLE tipo_abastecimento_energia_eletrica	SELECT *,GETDATE() AS CRDATE INTO tipo_abastecimento_energia_eletrica FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_abastecimento_energia_eletrica
DROP TABLE tipo_abastecimento_gas	SELECT *,GETDATE() AS CRDATE INTO tipo_abastecimento_gas FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_abastecimento_gas
DROP TABLE tipo_ambiente	SELECT *,GETDATE() AS CRDATE INTO tipo_ambiente FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_ambiente
DROP TABLE tipo_andamento_expediente	SELECT *,GETDATE() AS CRDATE INTO tipo_andamento_expediente FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_andamento_expediente
DROP TABLE tipo_atendimento	SELECT *,GETDATE() AS CRDATE INTO tipo_atendimento FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_atendimento
DROP TABLE tipo_atividade_mec	SELECT *,GETDATE() AS CRDATE INTO tipo_atividade_mec FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_atividade_mec
DROP TABLE tipo_ato	SELECT *,GETDATE() AS CRDATE INTO tipo_ato FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_ato
DROP TABLE tipo_barreira_fisica	SELECT *,GETDATE() AS CRDATE INTO tipo_barreira_fisica FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_barreira_fisica
DROP TABLE tipo_cadastro_convenio	SELECT *,GETDATE() AS CRDATE INTO tipo_cadastro_convenio FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_cadastro_convenio
DROP TABLE tipo_calculo_cargo	SELECT *,GETDATE() AS CRDATE INTO tipo_calculo_cargo FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_calculo_cargo
DROP TABLE tipo_categoria_area_mec	SELECT *,GETDATE() AS CRDATE INTO tipo_categoria_area_mec FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_categoria_area_mec
DROP TABLE tipo_categoria_escola_privada	SELECT *,GETDATE() AS CRDATE INTO tipo_categoria_escola_privada FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_categoria_escola_privada
DROP TABLE tipo_classe_quadro	SELECT *,GETDATE() AS CRDATE INTO tipo_classe_quadro FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_classe_quadro
DROP TABLE tipo_complemento_resposta	SELECT *,GETDATE() AS CRDATE INTO tipo_complemento_resposta FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_complemento_resposta
DROP TABLE tipo_concurso	SELECT *,GETDATE() AS CRDATE INTO tipo_concurso FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_concurso
DROP TABLE tipo_conexao_internet	SELECT *,GETDATE() AS CRDATE INTO tipo_conexao_internet FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_conexao_internet
DROP TABLE tipo_construcao	SELECT *,GETDATE() AS CRDATE INTO tipo_construcao FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_construcao
DROP TABLE tipo_contrato	SELECT *,GETDATE() AS CRDATE INTO tipo_contrato FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_contrato
DROP TABLE tipo_convenio	SELECT *,GETDATE() AS CRDATE INTO tipo_convenio FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_convenio
DROP TABLE tipo_convenio_escola_privada	SELECT *,GETDATE() AS CRDATE INTO tipo_convenio_escola_privada FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_convenio_escola_privada
DROP TABLE tipo_credenciamento	SELECT *,GETDATE() AS CRDATE INTO tipo_credenciamento FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_credenciamento
DROP TABLE tipo_credenciamento_instituicao	SELECT *,GETDATE() AS CRDATE INTO tipo_credenciamento_instituicao FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_credenciamento_instituicao
DROP TABLE tipo_critica_correcao_retorno	SELECT *,GETDATE() AS CRDATE INTO tipo_critica_correcao_retorno FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_critica_correcao_retorno
DROP TABLE tipo_curso_especifico	SELECT *,GETDATE() AS CRDATE INTO tipo_curso_especifico FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_curso_especifico
DROP TABLE tipo_dado_parametro	SELECT *,GETDATE() AS CRDATE INTO tipo_dado_parametro FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_dado_parametro
DROP TABLE tipo_dependencia_administrativa	SELECT *,GETDATE() AS CRDATE INTO tipo_dependencia_administrativa FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_dependencia_administrativa
DROP TABLE tipo_despesa	SELECT *,GETDATE() AS CRDATE INTO tipo_despesa FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_despesa
DROP TABLE tipo_despesa_prestacao_conta	SELECT *,GETDATE() AS CRDATE INTO tipo_despesa_prestacao_conta FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_despesa_prestacao_conta
DROP TABLE tipo_dispositivo_comunicacao	SELECT *,GETDATE() AS CRDATE INTO tipo_dispositivo_comunicacao FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_dispositivo_comunicacao
DROP TABLE tipo_dispositivo_dejeto	SELECT *,GETDATE() AS CRDATE INTO tipo_dispositivo_dejeto FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_dispositivo_dejeto
DROP TABLE tipo_dispositivo_lixo	SELECT *,GETDATE() AS CRDATE INTO tipo_dispositivo_lixo FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_dispositivo_lixo
DROP TABLE tipo_documento	SELECT *,GETDATE() AS CRDATE INTO tipo_documento FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_documento
DROP TABLE tipo_documento_estrangeiro	SELECT *,GETDATE() AS CRDATE INTO tipo_documento_estrangeiro FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_documento_estrangeiro
DROP TABLE tipo_documento_filtro_documento	SELECT *,GETDATE() AS CRDATE INTO tipo_documento_filtro_documento FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_documento_filtro_documento
DROP TABLE tipo_documento_fiscal	SELECT *,GETDATE() AS CRDATE INTO tipo_documento_fiscal FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_documento_fiscal
DROP TABLE tipo_documento_fiscal_despesa	SELECT *,GETDATE() AS CRDATE INTO tipo_documento_fiscal_despesa FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_documento_fiscal_despesa
DROP TABLE tipo_educacao_especializada	SELECT *,GETDATE() AS CRDATE INTO tipo_educacao_especializada FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_educacao_especializada
DROP TABLE tipo_endereco	SELECT *,GETDATE() AS CRDATE INTO tipo_endereco FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_endereco
DROP TABLE tipo_ensino_estado	SELECT *,GETDATE() AS CRDATE INTO tipo_ensino_estado FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_ensino_estado
DROP TABLE tipo_equipamento	SELECT *,GETDATE() AS CRDATE INTO tipo_equipamento FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_equipamento
DROP TABLE tipo_equipamento_escola	SELECT *,GETDATE() AS CRDATE INTO tipo_equipamento_escola FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_equipamento_escola
DROP TABLE tipo_escola	SELECT *,GETDATE() AS CRDATE INTO tipo_escola FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_escola
DROP TABLE tipo_escola_cargo_concurso	SELECT *,GETDATE() AS CRDATE INTO tipo_escola_cargo_concurso FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_escola_cargo_concurso
DROP TABLE tipo_escola_cargo_concurso_bak	SELECT *,GETDATE() AS CRDATE INTO tipo_escola_cargo_concurso_bak FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_escola_cargo_concurso_bak
DROP TABLE tipo_escola_faixa_etaria_papa	SELECT *,GETDATE() AS CRDATE INTO tipo_escola_faixa_etaria_papa FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_escola_faixa_etaria_papa
DROP TABLE tipo_escola_procedencia	SELECT *,GETDATE() AS CRDATE INTO tipo_escola_procedencia FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_escola_procedencia
DROP TABLE tipo_etapa_ensino_2007_2007	SELECT *,GETDATE() AS CRDATE INTO tipo_etapa_ensino_2007_2007 FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_etapa_ensino_2007_2007
DROP TABLE tipo_evento_leve_leite	SELECT *,GETDATE() AS CRDATE INTO tipo_evento_leve_leite FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_evento_leve_leite
DROP TABLE tipo_experiencia_pedagogica	SELECT *,GETDATE() AS CRDATE INTO tipo_experiencia_pedagogica FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_experiencia_pedagogica
DROP TABLE tipo_feriado	SELECT *,GETDATE() AS CRDATE INTO tipo_feriado FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_feriado
DROP TABLE tipo_forma_ocupacao_predio	SELECT *,GETDATE() AS CRDATE INTO tipo_forma_ocupacao_predio FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_forma_ocupacao_predio
DROP TABLE tipo_forma_organizacao_ensino	SELECT *,GETDATE() AS CRDATE INTO tipo_forma_organizacao_ensino FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_forma_organizacao_ensino
DROP TABLE tipo_funcao_atividade	SELECT *,GETDATE() AS CRDATE INTO tipo_funcao_atividade FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_funcao_atividade
DROP TABLE tipo_funcionario_externo	SELECT *,GETDATE() AS CRDATE INTO tipo_funcionario_externo FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_funcionario_externo
DROP TABLE tipo_grade	SELECT *,GETDATE() AS CRDATE INTO tipo_grade FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_grade
DROP TABLE tipo_habilitacao_profissional	SELECT *,GETDATE() AS CRDATE INTO tipo_habilitacao_profissional FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_habilitacao_profissional
DROP TABLE tipo_habilitacao_profissional_mec	SELECT *,GETDATE() AS CRDATE INTO tipo_habilitacao_profissional_mec FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_habilitacao_profissional_mec
DROP TABLE tipo_jornada	SELECT *,GETDATE() AS CRDATE INTO tipo_jornada FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_jornada
DROP TABLE tipo_jornada_estado_outro	SELECT *,GETDATE() AS CRDATE INTO tipo_jornada_estado_outro FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_jornada_estado_outro
DROP TABLE tipo_lingua_indigena	SELECT *,GETDATE() AS CRDATE INTO tipo_lingua_indigena FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_lingua_indigena
DROP TABLE tipo_local_funcionamento_escola	SELECT *,GETDATE() AS CRDATE INTO tipo_local_funcionamento_escola FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_local_funcionamento_escola
DROP TABLE tipo_local_reservatorio_agua	SELECT *,GETDATE() AS CRDATE INTO tipo_local_reservatorio_agua FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_local_reservatorio_agua
DROP TABLE tipo_logradouro	SELECT *,GETDATE() AS CRDATE INTO tipo_logradouro FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_logradouro
DROP TABLE tipo_mantenedora_privada	SELECT *,GETDATE() AS CRDATE INTO tipo_mantenedora_privada FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_mantenedora_privada
DROP TABLE tipo_manual	SELECT *,GETDATE() AS CRDATE INTO tipo_manual FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_manual
DROP TABLE tipo_material_socio_cultural_pedagogico	SELECT *,GETDATE() AS CRDATE INTO tipo_material_socio_cultural_pedagogico FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_material_socio_cultural_pedagogico
DROP TABLE tipo_modalidade_ensino_2007_2007	SELECT *,GETDATE() AS CRDATE INTO tipo_modalidade_ensino_2007_2007 FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_modalidade_ensino_2007_2007
DROP TABLE tipo_motivo_ajuste	SELECT *,GETDATE() AS CRDATE INTO tipo_motivo_ajuste FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_motivo_ajuste
DROP TABLE tipo_motivo_ajuste_faturamento	SELECT *,GETDATE() AS CRDATE INTO tipo_motivo_ajuste_faturamento FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_motivo_ajuste_faturamento
DROP TABLE tipo_motivo_encerramento_contrato	SELECT *,GETDATE() AS CRDATE INTO tipo_motivo_encerramento_contrato FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_motivo_encerramento_contrato
DROP TABLE tipo_motivo_insucesso	SELECT *,GETDATE() AS CRDATE INTO tipo_motivo_insucesso FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_motivo_insucesso
DROP TABLE tipo_motivo_recusa_matricula	SELECT *,GETDATE() AS CRDATE INTO tipo_motivo_recusa_matricula FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_motivo_recusa_matricula
DROP TABLE tipo_muro_fecho	SELECT *,GETDATE() AS CRDATE INTO tipo_muro_fecho FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_muro_fecho
DROP TABLE tipo_necessidade_especial	SELECT *,GETDATE() AS CRDATE INTO tipo_necessidade_especial FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_necessidade_especial
DROP TABLE tipo_necessidade_especial_combinacao_multipla	SELECT *,GETDATE() AS CRDATE INTO tipo_necessidade_especial_combinacao_multipla FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_necessidade_especial_combinacao_multipla
DROP TABLE tipo_necessidade_especial_estado	SELECT *,GETDATE() AS CRDATE INTO tipo_necessidade_especial_estado FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_necessidade_especial_estado
DROP TABLE tipo_necessidade_especial_incompativel	SELECT *,GETDATE() AS CRDATE INTO tipo_necessidade_especial_incompativel FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_necessidade_especial_incompativel
DROP TABLE tipo_nivel_manual	SELECT *,GETDATE() AS CRDATE INTO tipo_nivel_manual FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_nivel_manual
DROP TABLE tipo_ocorrencia	SELECT *,GETDATE() AS CRDATE INTO tipo_ocorrencia FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_ocorrencia
DROP TABLE tipo_ocorrencia_historica	SELECT *,GETDATE() AS CRDATE INTO tipo_ocorrencia_historica FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_ocorrencia_historica
DROP TABLE tipo_opcao_turno	SELECT *,GETDATE() AS CRDATE INTO tipo_opcao_turno FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_opcao_turno
DROP TABLE tipo_operacao	SELECT *,GETDATE() AS CRDATE INTO tipo_operacao FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_operacao
DROP TABLE tipo_ordem_servico	SELECT *,GETDATE() AS CRDATE INTO tipo_ordem_servico FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_ordem_servico
DROP TABLE tipo_orgao_colegiado	SELECT *,GETDATE() AS CRDATE INTO tipo_orgao_colegiado FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_orgao_colegiado
DROP TABLE tipo_para_raio	SELECT *,GETDATE() AS CRDATE INTO tipo_para_raio FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_para_raio
DROP TABLE tipo_parentesco	SELECT *,GETDATE() AS CRDATE INTO tipo_parentesco FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_parentesco
DROP TABLE tipo_periodicidade	SELECT *,GETDATE() AS CRDATE INTO tipo_periodicidade FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_periodicidade
DROP TABLE tipo_periodo_limpeza_caixa_agua	SELECT *,GETDATE() AS CRDATE INTO tipo_periodo_limpeza_caixa_agua FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_periodo_limpeza_caixa_agua
DROP TABLE tipo_pessoa_responsavel	SELECT *,GETDATE() AS CRDATE INTO tipo_pessoa_responsavel FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_pessoa_responsavel
DROP TABLE tipo_pontuacao_atribuicao	SELECT *,GETDATE() AS CRDATE INTO tipo_pontuacao_atribuicao FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_pontuacao_atribuicao
DROP TABLE tipo_prestacao_conta	SELECT *,GETDATE() AS CRDATE INTO tipo_prestacao_conta FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_prestacao_conta
DROP TABLE tipo_prioridade_lista	SELECT *,GETDATE() AS CRDATE INTO tipo_prioridade_lista FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_prioridade_lista
DROP TABLE tipo_processamento_carga_prodesp	SELECT *,GETDATE() AS CRDATE INTO tipo_processamento_carga_prodesp FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_processamento_carga_prodesp
DROP TABLE tipo_produto	SELECT *,GETDATE() AS CRDATE INTO tipo_produto FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_produto
DROP TABLE tipo_programa	SELECT *,GETDATE() AS CRDATE INTO tipo_programa FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_programa
DROP TABLE tipo_programa_atividade_mec	SELECT *,GETDATE() AS CRDATE INTO tipo_programa_atividade_mec FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_programa_atividade_mec
DROP TABLE tipo_programa_social	SELECT *,GETDATE() AS CRDATE INTO tipo_programa_social FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_programa_social
DROP TABLE tipo_projeto	SELECT *,GETDATE() AS CRDATE INTO tipo_projeto FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_projeto
DROP TABLE tipo_proprietario	SELECT *,GETDATE() AS CRDATE INTO tipo_proprietario FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_proprietario
DROP TABLE tipo_quadro	SELECT *,GETDATE() AS CRDATE INTO tipo_quadro FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_quadro
DROP TABLE tipo_questionario	SELECT *,GETDATE() AS CRDATE INTO tipo_questionario FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_questionario
DROP TABLE tipo_raca_cor	SELECT *,GETDATE() AS CRDATE INTO tipo_raca_cor FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_raca_cor
DROP TABLE tipo_recurso_aluno	SELECT *,GETDATE() AS CRDATE INTO tipo_recurso_aluno FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_recurso_aluno
DROP TABLE tipo_recurso_aluno_incompativel	SELECT *,GETDATE() AS CRDATE INTO tipo_recurso_aluno_incompativel FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_recurso_aluno_incompativel
DROP TABLE tipo_secao_documento	SELECT *,GETDATE() AS CRDATE INTO tipo_secao_documento FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_secao_documento
DROP TABLE tipo_sigilo	SELECT *,GETDATE() AS CRDATE INTO tipo_sigilo FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_sigilo
DROP TABLE tipo_situacao_ajuste_pagamento_teg	SELECT *,GETDATE() AS CRDATE INTO tipo_situacao_ajuste_pagamento_teg FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_situacao_ajuste_pagamento_teg
DROP TABLE tipo_situacao_unidade	SELECT *,GETDATE() AS CRDATE INTO tipo_situacao_unidade FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_situacao_unidade
DROP TABLE tipo_transporte_escolar	SELECT *,GETDATE() AS CRDATE INTO tipo_transporte_escolar FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_transporte_escolar
DROP TABLE tipo_tratamento_lixo	SELECT *,GETDATE() AS CRDATE INTO tipo_tratamento_lixo FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_tratamento_lixo
DROP TABLE tipo_turma	SELECT *,GETDATE() AS CRDATE INTO tipo_turma FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_turma
DROP TABLE tipo_turno	SELECT *,GETDATE() AS CRDATE INTO tipo_turno FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_turno
DROP TABLE tipo_unidade_administrativa	SELECT *,GETDATE() AS CRDATE INTO tipo_unidade_administrativa FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_unidade_administrativa
DROP TABLE tipo_unidade_educacao	SELECT *,GETDATE() AS CRDATE INTO tipo_unidade_educacao FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_unidade_educacao
DROP TABLE tipo_uso_tic	SELECT *,GETDATE() AS CRDATE INTO tipo_uso_tic FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_uso_tic
DROP TABLE tipo_viagem	SELECT *,GETDATE() AS CRDATE INTO tipo_viagem FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_viagem
DROP TABLE tipo_vinculo_expediente	SELECT *,GETDATE() AS CRDATE INTO tipo_vinculo_expediente FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_vinculo_expediente
DROP TABLE tipo_voltagem	SELECT *,GETDATE() AS CRDATE INTO tipo_voltagem FROM DB_EDUCACAO_1_PRODAM.SE1426_SS.DBO.tipo_voltagem
