
/*Venho solicitar que seja fornecida uma relação com:
- todas as Unidades Escolares da Administração Direta , 
- todos CEUs,
-todos os prédios administrativos da SME e locais onde estão instaladas as unidades. 

A informação deverá conter também os endereços e a quantidade de servidores públicos que trabalham no local.

Solicito, ainda, que tal informação seja fornecida com urgência, eis que se faz necessária para instruir procedimentos urgentes. 
Muito obrigada
*/

drop table unidade_educacao_dados_gerais
select *,getdate() AS CRDATE into unidade_educacao_dados_gerais from DB_EDUCACAO_1_PRODAM.se1426_ss.dbo.v_unidade_educacao_dados_gerais

--DROP TABLE ##UNIDADES_DIRETAS_E_SETORES
SELECT 
CASE WHEN TP_ESCOLA IN (1,2,3,4,10,13,16,17,18,19,25,28,30,31) THEN 'DIR'
      WHEN TP_ESCOLA IN (11,12,22,26) THEN 'CONV'
 ELSE NULL END AS REDE,
  
CD_UNIDADE_ADMINISTRATIVA_REFERENCIA AS CD_UNIDADE_REFERENCIA,
CASE WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA ='108100' THEN 'DRE - BT'
     WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA ='108200' THEN 'DRE - CL'
     WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA ='108300' THEN 'DRE - CS'
     WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA ='108400' THEN 'DRE - FO'
     WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA ='108500' THEN 'DRE - G'
     WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA ='108600' THEN 'DRE - IP'
     WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA ='108700' THEN 'DRE - IQ'
     WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA ='108800' THEN 'DRE - JT'
     WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA ='108900' THEN 'DRE - PE'
     WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA ='109000' THEN 'DRE - PJ'
     WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA ='109100' THEN 'DRE - SA'
     WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA ='109200' THEN 'DRE - SM'
     WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA ='109300' THEN 'DRE - MP'
ELSE NULL END AS DRE,
CD_UNIDADE_EDUCACAO,
dc_tipo_unidade_educacao AS TP_UNIDADE,
CASE WHEN CD_UNIDADE_EDUCACAO=CODEOL THEN 'CEU' 
     WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA IN 
	 (110000,110043,110086,120000,120049,120200,121000,122000,123000,125121,126000,127000) THEN 'SME'
     WHEN CD_UNIDADE_ADMINISTRATIVA_REFERENCIA IN 
	 (108100,108200,108300,108400,108500,108600,108700,108800,108900,109000,109100,109200,109300) THEN 'DRE'
	 
ELSE NULL END AS TP_DEPENDENCIA,
CASE WHEN CD_UNIDADE_EDUCACAO=CODEOL THEN 'CEU' ELSE SG_TP_ESCOLA END AS SG_TP_ESCOLA,

NM_UNIDADE_EDUCACAO,
SG_TIPO_SITUACAO_UNIDADE AS SITUACAO,
DC_TP_LOGRADOURO,
NM_LOGRADOURO,
CD_NR_ENDERECO AS NR,
DC_COMPLEMENTO_ENDERECO AS COMPL,
NM_BAIRRO AS BAIRRO,
CD_CEP AS CEP,
NM_DISTRITO_MEC AS DISTRITO,
NM_MICRO_REGIAO AS MICRO_REGIAO,
CD_SETOR_DISTRITO AS SETOR,
DC_SUB_PREFEITURA AS SUBPREF,
CD_COORDENADA_GEO_Y AS LATITUDE,
CD_COORDENADA_GEO_X AS LONGITUDE,
CD_ENDERECO_GRH AS GRH,
dc_tipo_local_funcionamento_escola AS LOC_FUNCIONAMENTO,
dc_tipo_dependencia_administrativa AS DEPEND_ADMINISTRATIVA,
dc_tipo_forma_ocupacao_predio AS FORMA_OCUPACAO,
dc_tipo_proprietario AS TP_PROPRIETARIO,
CONVERT(VARCHAR,CRDATE-1,103) AS DT_BASE
INTO ##UNIDADES_DIRETAS_E_SETORES
FROM unidade_educacao_dados_gerais A
LEFT JOIN VW_CEUS B ON A.CD_UNIDADE_EDUCACAO=B.CODEOL
WHERE tp_unidade_administrativa in (8,19,24,25,26) 
AND TP_SITUACAO_UNIDADE=1 AND dc_tipo_unidade_educacao NOT IN ('INSTITUICAO', 'UNIDADE EXTERNA') AND CD_UNIDADE_ADMINISTRATIVA_REFERENCIA <>'999000'

--select * from ##UNIDADES_DIRETAS_E_SETORES

--select * from ##UNIDADES_DIRETAS_E_SETORES WHERE TP_DEPENDENCIA='CEU'
---------------------------------------------------------------------------------------------
--SELECT * INTO ##UNIDADES_DIRETAS_E_SETORES1 FROM  ##UNIDADES_DIRETAS_E_SETORES WHERE (REDE ='DIR' OR REDE IS NULL)



--select * from ##UNIDADES_DIRETAS_E_SETORES1

SELECT * INTO ##predios_administrativos_dre_ceus FROM ##UNIDADES_DIRETAS_E_SETORES1 where tp_unidade='UNIDADE ADMINISTRATIVA'

/*
DROP TABLE ##emefs_andre
SELECT 
DRE,
cd_unidade_educacao,
SG_TP_ESCOLA,
nm_unidade_educacao,
CONCAT(DC_TP_LOGRADOURO, ' ',NM_LOGRADOURO,', ',NR, ' ',BAIRRO) AS ENDERECO,
DT_BASE
into ##emefs_andre
FROM ##UNIDADES_DIRETAS_E_SETORES

WHERE SG_TP_ESCOLA IN ('emef', 'emefm','emebs','ceu', 'ceu emef', 'emef p fom') and situacao = 'ativa' --order by SG_TP_ESCOLA
--SELECT * FROM ##emefs_andre



select 
DRE,
CD_UNIDADE_EDUCACAO AS CODEOL,
SG_TP_ESCOLA AS TIPO,
NM_UNIDADE_EDUCACAO AS NOME,
CONCAT(
DC_TP_LOGRADOURO,
' ',
NM_LOGRADOURO,
', ',
NR,
COMPL,
' ',
BAIRRO) AS ENDEREÇO,
DT_BASE

from ##UNIDADES_DIRETAS_E_SETORES where nm_unidade_educacao like '%tres pontes%' order by TP_UNIDADE

*/
