
CREATE VIEW VW_ALUNOS_ENDERECOS_OUTROS_MUNICIPIOS AS

SELECT B.nm_municipio AS MUNICIPIO,A.*  
FROM VW_ALUNOS_ENDERECOS A
JOIN D_MUNICIPIO B ON A.CD_MUNICIPIO=B.cd_municipio
WHERE A.CD_MUNICIPIO<>3550308

--SELECT * FROM VW_ALUNOS_ENDERECOS_OUTROS_MUNICIPIOS
